// ==============================================================
// Generated by Vitis HLS v2024.2
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2024 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

module system_v_gamma_lut_0_0_AXIvideo2MultiPixStream (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_continue,
        ap_idle,
        ap_ready,
        s_axis_video_TDATA,
        s_axis_video_TVALID,
        s_axis_video_TREADY,
        s_axis_video_TKEEP,
        s_axis_video_TSTRB,
        s_axis_video_TUSER,
        s_axis_video_TLAST,
        s_axis_video_TID,
        s_axis_video_TDEST,
        imgRgb_din,
        imgRgb_full_n,
        imgRgb_write,
        imgRgb_num_data_valid,
        imgRgb_fifo_cap,
        height,
        width
);

parameter    ap_ST_fsm_state1 = 9'd1;
parameter    ap_ST_fsm_state2 = 9'd2;
parameter    ap_ST_fsm_state3 = 9'd4;
parameter    ap_ST_fsm_state4 = 9'd8;
parameter    ap_ST_fsm_state5 = 9'd16;
parameter    ap_ST_fsm_state6 = 9'd32;
parameter    ap_ST_fsm_state7 = 9'd64;
parameter    ap_ST_fsm_state8 = 9'd128;
parameter    ap_ST_fsm_state9 = 9'd256;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
input   ap_continue;
output   ap_idle;
output   ap_ready;
input  [31:0] s_axis_video_TDATA;
input   s_axis_video_TVALID;
output   s_axis_video_TREADY;
input  [3:0] s_axis_video_TKEEP;
input  [3:0] s_axis_video_TSTRB;
input  [0:0] s_axis_video_TUSER;
input  [0:0] s_axis_video_TLAST;
input  [0:0] s_axis_video_TID;
input  [0:0] s_axis_video_TDEST;
output  [29:0] imgRgb_din;
input   imgRgb_full_n;
output   imgRgb_write;
input  [4:0] imgRgb_num_data_valid;
input  [4:0] imgRgb_fifo_cap;
input  [15:0] height;
input  [15:0] width;

reg ap_done;
reg ap_idle;
reg ap_ready;

reg    ap_done_reg;
(* fsm_encoding = "none" *) reg   [8:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
wire   [11:0] grp_reg_unsigned_short_s_fu_216_ap_return;
reg   [11:0] rows_reg_436;
wire    ap_CS_fsm_state4;
wire   [11:0] grp_reg_unsigned_short_s_fu_222_ap_return;
reg   [11:0] cols_reg_441;
wire   [0:0] cmp10252_i_fu_267_p2;
reg   [0:0] cmp10252_i_reg_449;
wire   [0:0] xor_ln216_fu_273_p2;
reg   [0:0] xor_ln216_reg_454;
wire   [0:0] and_ln216_fu_297_p2;
reg   [0:0] and_ln216_reg_465;
wire    ap_CS_fsm_state5;
wire   [0:0] select_ln216_fu_351_p3;
reg   [0:0] select_ln216_reg_476;
wire    ap_CS_fsm_state7;
wire    grp_AXIvideo2MultiPixStream_Pipeline_loop_wait_for_start_fu_132_ap_start;
wire    grp_AXIvideo2MultiPixStream_Pipeline_loop_wait_for_start_fu_132_ap_done;
wire    grp_AXIvideo2MultiPixStream_Pipeline_loop_wait_for_start_fu_132_ap_idle;
wire    grp_AXIvideo2MultiPixStream_Pipeline_loop_wait_for_start_fu_132_ap_ready;
wire    grp_AXIvideo2MultiPixStream_Pipeline_loop_wait_for_start_fu_132_s_axis_video_TREADY;
wire   [29:0] grp_AXIvideo2MultiPixStream_Pipeline_loop_wait_for_start_fu_132_axi_data_out;
wire    grp_AXIvideo2MultiPixStream_Pipeline_loop_wait_for_start_fu_132_axi_data_out_ap_vld;
wire   [0:0] grp_AXIvideo2MultiPixStream_Pipeline_loop_wait_for_start_fu_132_axi_last_out;
wire    grp_AXIvideo2MultiPixStream_Pipeline_loop_wait_for_start_fu_132_axi_last_out_ap_vld;
wire    grp_AXIvideo2MultiPixStream_Pipeline_loop_width_fu_152_ap_start;
wire    grp_AXIvideo2MultiPixStream_Pipeline_loop_width_fu_152_ap_done;
wire    grp_AXIvideo2MultiPixStream_Pipeline_loop_width_fu_152_ap_idle;
wire    grp_AXIvideo2MultiPixStream_Pipeline_loop_width_fu_152_ap_ready;
wire   [29:0] grp_AXIvideo2MultiPixStream_Pipeline_loop_width_fu_152_imgRgb_din;
wire    grp_AXIvideo2MultiPixStream_Pipeline_loop_width_fu_152_imgRgb_write;
wire    grp_AXIvideo2MultiPixStream_Pipeline_loop_width_fu_152_s_axis_video_TREADY;
wire   [0:0] grp_AXIvideo2MultiPixStream_Pipeline_loop_width_fu_152_eol_out;
wire    grp_AXIvideo2MultiPixStream_Pipeline_loop_width_fu_152_eol_out_ap_vld;
wire   [29:0] grp_AXIvideo2MultiPixStream_Pipeline_loop_width_fu_152_axi_data_3_out;
wire    grp_AXIvideo2MultiPixStream_Pipeline_loop_width_fu_152_axi_data_3_out_ap_vld;
wire    grp_AXIvideo2MultiPixStream_Pipeline_loop_wait_for_eol_fu_180_ap_start;
wire    grp_AXIvideo2MultiPixStream_Pipeline_loop_wait_for_eol_fu_180_ap_done;
wire    grp_AXIvideo2MultiPixStream_Pipeline_loop_wait_for_eol_fu_180_ap_idle;
wire    grp_AXIvideo2MultiPixStream_Pipeline_loop_wait_for_eol_fu_180_ap_ready;
wire    grp_AXIvideo2MultiPixStream_Pipeline_loop_wait_for_eol_fu_180_s_axis_video_TREADY;
wire   [29:0] grp_AXIvideo2MultiPixStream_Pipeline_loop_wait_for_eol_fu_180_axi_data_4_out;
wire    grp_AXIvideo2MultiPixStream_Pipeline_loop_wait_for_eol_fu_180_axi_data_4_out_ap_vld;
wire   [0:0] grp_AXIvideo2MultiPixStream_Pipeline_loop_wait_for_eol_fu_180_axi_last_4_out;
wire    grp_AXIvideo2MultiPixStream_Pipeline_loop_wait_for_eol_fu_180_axi_last_4_out_ap_vld;
wire    grp_reg_unsigned_short_s_fu_216_ap_start;
wire    grp_reg_unsigned_short_s_fu_216_ap_done;
wire    grp_reg_unsigned_short_s_fu_216_ap_idle;
wire    grp_reg_unsigned_short_s_fu_216_ap_ready;
reg    grp_reg_unsigned_short_s_fu_216_ap_ce;
wire   [11:0] grp_reg_unsigned_short_s_fu_216_d;
wire    ap_CS_fsm_state3;
wire    grp_reg_unsigned_short_s_fu_222_ap_start;
wire    grp_reg_unsigned_short_s_fu_222_ap_done;
wire    grp_reg_unsigned_short_s_fu_222_ap_idle;
wire    grp_reg_unsigned_short_s_fu_222_ap_ready;
reg    grp_reg_unsigned_short_s_fu_222_ap_ce;
wire   [11:0] grp_reg_unsigned_short_s_fu_222_d;
reg   [0:0] sof_reg_110;
wire    ap_CS_fsm_state9;
reg   [0:0] axi_last_2_reg_122;
reg    grp_AXIvideo2MultiPixStream_Pipeline_loop_wait_for_start_fu_132_ap_start_reg;
wire    ap_CS_fsm_state2;
reg   [29:0] axi_data_2_fu_74;
reg    grp_AXIvideo2MultiPixStream_Pipeline_loop_width_fu_152_ap_start_reg;
wire   [0:0] icmp_ln188_fu_282_p2;
wire    ap_CS_fsm_state6;
reg    grp_AXIvideo2MultiPixStream_Pipeline_loop_wait_for_eol_fu_180_ap_start_reg;
wire    ap_CS_fsm_state8;
reg   [0:0] axi_last_4_loc_fu_82;
reg    grp_reg_unsigned_short_s_fu_216_ap_start_reg;
reg   [8:0] ap_NS_fsm;
wire    ap_NS_fsm_state3;
reg    grp_reg_unsigned_short_s_fu_222_ap_start_reg;
reg   [11:0] i_fu_78;
wire   [11:0] i_5_fu_287_p2;
reg    ap_block_state1;
reg    ap_ST_fsm_state1_blk;
wire    ap_ST_fsm_state2_blk;
reg    ap_ST_fsm_state3_blk;
wire    ap_ST_fsm_state4_blk;
wire    ap_ST_fsm_state5_blk;
reg    ap_ST_fsm_state6_blk;
wire    ap_ST_fsm_state7_blk;
reg    ap_ST_fsm_state8_blk;
wire    ap_ST_fsm_state9_blk;
wire    regslice_both_s_axis_video_V_data_V_U_apdone_blk;
wire   [31:0] s_axis_video_TDATA_int_regslice;
wire    s_axis_video_TVALID_int_regslice;
reg    s_axis_video_TREADY_int_regslice;
wire    regslice_both_s_axis_video_V_data_V_U_ack_in;
wire    regslice_both_s_axis_video_V_keep_V_U_apdone_blk;
wire   [3:0] s_axis_video_TKEEP_int_regslice;
wire    regslice_both_s_axis_video_V_keep_V_U_vld_out;
wire    regslice_both_s_axis_video_V_keep_V_U_ack_in;
wire    regslice_both_s_axis_video_V_strb_V_U_apdone_blk;
wire   [3:0] s_axis_video_TSTRB_int_regslice;
wire    regslice_both_s_axis_video_V_strb_V_U_vld_out;
wire    regslice_both_s_axis_video_V_strb_V_U_ack_in;
wire    regslice_both_s_axis_video_V_user_V_U_apdone_blk;
wire   [0:0] s_axis_video_TUSER_int_regslice;
wire    regslice_both_s_axis_video_V_user_V_U_vld_out;
wire    regslice_both_s_axis_video_V_user_V_U_ack_in;
wire    regslice_both_s_axis_video_V_last_V_U_apdone_blk;
wire   [0:0] s_axis_video_TLAST_int_regslice;
wire    regslice_both_s_axis_video_V_last_V_U_vld_out;
wire    regslice_both_s_axis_video_V_last_V_U_ack_in;
wire    regslice_both_s_axis_video_V_id_V_U_apdone_blk;
wire   [0:0] s_axis_video_TID_int_regslice;
wire    regslice_both_s_axis_video_V_id_V_U_vld_out;
wire    regslice_both_s_axis_video_V_id_V_U_ack_in;
wire    regslice_both_s_axis_video_V_dest_V_U_apdone_blk;
wire   [0:0] s_axis_video_TDEST_int_regslice;
wire    regslice_both_s_axis_video_V_dest_V_U_vld_out;
wire    regslice_both_s_axis_video_V_dest_V_U_ack_in;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_done_reg = 1'b0;
#0 ap_CS_fsm = 9'd1;
#0 grp_AXIvideo2MultiPixStream_Pipeline_loop_wait_for_start_fu_132_ap_start_reg = 1'b0;
#0 grp_AXIvideo2MultiPixStream_Pipeline_loop_width_fu_152_ap_start_reg = 1'b0;
#0 grp_AXIvideo2MultiPixStream_Pipeline_loop_wait_for_eol_fu_180_ap_start_reg = 1'b0;
#0 grp_reg_unsigned_short_s_fu_216_ap_start_reg = 1'b0;
#0 grp_reg_unsigned_short_s_fu_222_ap_start_reg = 1'b0;
#0 i_fu_78 = 12'd0;
end

system_v_gamma_lut_0_0_AXIvideo2MultiPixStream_Pipeline_loop_wait_for_start grp_AXIvideo2MultiPixStream_Pipeline_loop_wait_for_start_fu_132(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_AXIvideo2MultiPixStream_Pipeline_loop_wait_for_start_fu_132_ap_start),
    .ap_done(grp_AXIvideo2MultiPixStream_Pipeline_loop_wait_for_start_fu_132_ap_done),
    .ap_idle(grp_AXIvideo2MultiPixStream_Pipeline_loop_wait_for_start_fu_132_ap_idle),
    .ap_ready(grp_AXIvideo2MultiPixStream_Pipeline_loop_wait_for_start_fu_132_ap_ready),
    .s_axis_video_TVALID(s_axis_video_TVALID_int_regslice),
    .s_axis_video_TDATA(s_axis_video_TDATA_int_regslice),
    .s_axis_video_TREADY(grp_AXIvideo2MultiPixStream_Pipeline_loop_wait_for_start_fu_132_s_axis_video_TREADY),
    .s_axis_video_TKEEP(s_axis_video_TKEEP_int_regslice),
    .s_axis_video_TSTRB(s_axis_video_TSTRB_int_regslice),
    .s_axis_video_TUSER(s_axis_video_TUSER_int_regslice),
    .s_axis_video_TLAST(s_axis_video_TLAST_int_regslice),
    .s_axis_video_TID(s_axis_video_TID_int_regslice),
    .s_axis_video_TDEST(s_axis_video_TDEST_int_regslice),
    .axi_data_out(grp_AXIvideo2MultiPixStream_Pipeline_loop_wait_for_start_fu_132_axi_data_out),
    .axi_data_out_ap_vld(grp_AXIvideo2MultiPixStream_Pipeline_loop_wait_for_start_fu_132_axi_data_out_ap_vld),
    .axi_last_out(grp_AXIvideo2MultiPixStream_Pipeline_loop_wait_for_start_fu_132_axi_last_out),
    .axi_last_out_ap_vld(grp_AXIvideo2MultiPixStream_Pipeline_loop_wait_for_start_fu_132_axi_last_out_ap_vld)
);

system_v_gamma_lut_0_0_AXIvideo2MultiPixStream_Pipeline_loop_width grp_AXIvideo2MultiPixStream_Pipeline_loop_width_fu_152(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_AXIvideo2MultiPixStream_Pipeline_loop_width_fu_152_ap_start),
    .ap_done(grp_AXIvideo2MultiPixStream_Pipeline_loop_width_fu_152_ap_done),
    .ap_idle(grp_AXIvideo2MultiPixStream_Pipeline_loop_width_fu_152_ap_idle),
    .ap_ready(grp_AXIvideo2MultiPixStream_Pipeline_loop_width_fu_152_ap_ready),
    .s_axis_video_TVALID(s_axis_video_TVALID_int_regslice),
    .imgRgb_din(grp_AXIvideo2MultiPixStream_Pipeline_loop_width_fu_152_imgRgb_din),
    .imgRgb_full_n(imgRgb_full_n),
    .imgRgb_write(grp_AXIvideo2MultiPixStream_Pipeline_loop_width_fu_152_imgRgb_write),
    .imgRgb_num_data_valid(5'd0),
    .imgRgb_fifo_cap(5'd0),
    .sof_4(sof_reg_110),
    .axi_last_2(axi_last_2_reg_122),
    .axi_data_2(axi_data_2_fu_74),
    .cols(cols_reg_441),
    .s_axis_video_TDATA(s_axis_video_TDATA_int_regslice),
    .s_axis_video_TREADY(grp_AXIvideo2MultiPixStream_Pipeline_loop_width_fu_152_s_axis_video_TREADY),
    .s_axis_video_TKEEP(s_axis_video_TKEEP_int_regslice),
    .s_axis_video_TSTRB(s_axis_video_TSTRB_int_regslice),
    .s_axis_video_TUSER(s_axis_video_TUSER_int_regslice),
    .s_axis_video_TLAST(s_axis_video_TLAST_int_regslice),
    .s_axis_video_TID(s_axis_video_TID_int_regslice),
    .s_axis_video_TDEST(s_axis_video_TDEST_int_regslice),
    .eol_out(grp_AXIvideo2MultiPixStream_Pipeline_loop_width_fu_152_eol_out),
    .eol_out_ap_vld(grp_AXIvideo2MultiPixStream_Pipeline_loop_width_fu_152_eol_out_ap_vld),
    .axi_data_3_out(grp_AXIvideo2MultiPixStream_Pipeline_loop_width_fu_152_axi_data_3_out),
    .axi_data_3_out_ap_vld(grp_AXIvideo2MultiPixStream_Pipeline_loop_width_fu_152_axi_data_3_out_ap_vld)
);

system_v_gamma_lut_0_0_AXIvideo2MultiPixStream_Pipeline_loop_wait_for_eol grp_AXIvideo2MultiPixStream_Pipeline_loop_wait_for_eol_fu_180(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_AXIvideo2MultiPixStream_Pipeline_loop_wait_for_eol_fu_180_ap_start),
    .ap_done(grp_AXIvideo2MultiPixStream_Pipeline_loop_wait_for_eol_fu_180_ap_done),
    .ap_idle(grp_AXIvideo2MultiPixStream_Pipeline_loop_wait_for_eol_fu_180_ap_idle),
    .ap_ready(grp_AXIvideo2MultiPixStream_Pipeline_loop_wait_for_eol_fu_180_ap_ready),
    .s_axis_video_TVALID(s_axis_video_TVALID_int_regslice),
    .axi_data_3_reload(grp_AXIvideo2MultiPixStream_Pipeline_loop_width_fu_152_axi_data_3_out),
    .select_ln216(select_ln216_reg_476),
    .eol_reload(grp_AXIvideo2MultiPixStream_Pipeline_loop_width_fu_152_eol_out),
    .s_axis_video_TDATA(s_axis_video_TDATA_int_regslice),
    .s_axis_video_TREADY(grp_AXIvideo2MultiPixStream_Pipeline_loop_wait_for_eol_fu_180_s_axis_video_TREADY),
    .s_axis_video_TKEEP(s_axis_video_TKEEP_int_regslice),
    .s_axis_video_TSTRB(s_axis_video_TSTRB_int_regslice),
    .s_axis_video_TUSER(s_axis_video_TUSER_int_regslice),
    .s_axis_video_TLAST(s_axis_video_TLAST_int_regslice),
    .s_axis_video_TID(s_axis_video_TID_int_regslice),
    .s_axis_video_TDEST(s_axis_video_TDEST_int_regslice),
    .axi_data_4_out(grp_AXIvideo2MultiPixStream_Pipeline_loop_wait_for_eol_fu_180_axi_data_4_out),
    .axi_data_4_out_ap_vld(grp_AXIvideo2MultiPixStream_Pipeline_loop_wait_for_eol_fu_180_axi_data_4_out_ap_vld),
    .axi_last_4_out(grp_AXIvideo2MultiPixStream_Pipeline_loop_wait_for_eol_fu_180_axi_last_4_out),
    .axi_last_4_out_ap_vld(grp_AXIvideo2MultiPixStream_Pipeline_loop_wait_for_eol_fu_180_axi_last_4_out_ap_vld)
);

system_v_gamma_lut_0_0_reg_unsigned_short_s grp_reg_unsigned_short_s_fu_216(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_reg_unsigned_short_s_fu_216_ap_start),
    .ap_done(grp_reg_unsigned_short_s_fu_216_ap_done),
    .ap_idle(grp_reg_unsigned_short_s_fu_216_ap_idle),
    .ap_ready(grp_reg_unsigned_short_s_fu_216_ap_ready),
    .ap_ce(grp_reg_unsigned_short_s_fu_216_ap_ce),
    .d(grp_reg_unsigned_short_s_fu_216_d),
    .ap_return(grp_reg_unsigned_short_s_fu_216_ap_return)
);

system_v_gamma_lut_0_0_reg_unsigned_short_s grp_reg_unsigned_short_s_fu_222(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_reg_unsigned_short_s_fu_222_ap_start),
    .ap_done(grp_reg_unsigned_short_s_fu_222_ap_done),
    .ap_idle(grp_reg_unsigned_short_s_fu_222_ap_idle),
    .ap_ready(grp_reg_unsigned_short_s_fu_222_ap_ready),
    .ap_ce(grp_reg_unsigned_short_s_fu_222_ap_ce),
    .d(grp_reg_unsigned_short_s_fu_222_d),
    .ap_return(grp_reg_unsigned_short_s_fu_222_ap_return)
);

system_v_gamma_lut_0_0_regslice_both #(
    .DataWidth( 32 ))
regslice_both_s_axis_video_V_data_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .data_in(s_axis_video_TDATA),
    .vld_in(s_axis_video_TVALID),
    .ack_in(regslice_both_s_axis_video_V_data_V_U_ack_in),
    .data_out(s_axis_video_TDATA_int_regslice),
    .vld_out(s_axis_video_TVALID_int_regslice),
    .ack_out(s_axis_video_TREADY_int_regslice),
    .apdone_blk(regslice_both_s_axis_video_V_data_V_U_apdone_blk)
);

system_v_gamma_lut_0_0_regslice_both #(
    .DataWidth( 4 ))
regslice_both_s_axis_video_V_keep_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .data_in(s_axis_video_TKEEP),
    .vld_in(s_axis_video_TVALID),
    .ack_in(regslice_both_s_axis_video_V_keep_V_U_ack_in),
    .data_out(s_axis_video_TKEEP_int_regslice),
    .vld_out(regslice_both_s_axis_video_V_keep_V_U_vld_out),
    .ack_out(s_axis_video_TREADY_int_regslice),
    .apdone_blk(regslice_both_s_axis_video_V_keep_V_U_apdone_blk)
);

system_v_gamma_lut_0_0_regslice_both #(
    .DataWidth( 4 ))
regslice_both_s_axis_video_V_strb_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .data_in(s_axis_video_TSTRB),
    .vld_in(s_axis_video_TVALID),
    .ack_in(regslice_both_s_axis_video_V_strb_V_U_ack_in),
    .data_out(s_axis_video_TSTRB_int_regslice),
    .vld_out(regslice_both_s_axis_video_V_strb_V_U_vld_out),
    .ack_out(s_axis_video_TREADY_int_regslice),
    .apdone_blk(regslice_both_s_axis_video_V_strb_V_U_apdone_blk)
);

system_v_gamma_lut_0_0_regslice_both #(
    .DataWidth( 1 ))
regslice_both_s_axis_video_V_user_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .data_in(s_axis_video_TUSER),
    .vld_in(s_axis_video_TVALID),
    .ack_in(regslice_both_s_axis_video_V_user_V_U_ack_in),
    .data_out(s_axis_video_TUSER_int_regslice),
    .vld_out(regslice_both_s_axis_video_V_user_V_U_vld_out),
    .ack_out(s_axis_video_TREADY_int_regslice),
    .apdone_blk(regslice_both_s_axis_video_V_user_V_U_apdone_blk)
);

system_v_gamma_lut_0_0_regslice_both #(
    .DataWidth( 1 ))
regslice_both_s_axis_video_V_last_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .data_in(s_axis_video_TLAST),
    .vld_in(s_axis_video_TVALID),
    .ack_in(regslice_both_s_axis_video_V_last_V_U_ack_in),
    .data_out(s_axis_video_TLAST_int_regslice),
    .vld_out(regslice_both_s_axis_video_V_last_V_U_vld_out),
    .ack_out(s_axis_video_TREADY_int_regslice),
    .apdone_blk(regslice_both_s_axis_video_V_last_V_U_apdone_blk)
);

system_v_gamma_lut_0_0_regslice_both #(
    .DataWidth( 1 ))
regslice_both_s_axis_video_V_id_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .data_in(s_axis_video_TID),
    .vld_in(s_axis_video_TVALID),
    .ack_in(regslice_both_s_axis_video_V_id_V_U_ack_in),
    .data_out(s_axis_video_TID_int_regslice),
    .vld_out(regslice_both_s_axis_video_V_id_V_U_vld_out),
    .ack_out(s_axis_video_TREADY_int_regslice),
    .apdone_blk(regslice_both_s_axis_video_V_id_V_U_apdone_blk)
);

system_v_gamma_lut_0_0_regslice_both #(
    .DataWidth( 1 ))
regslice_both_s_axis_video_V_dest_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .data_in(s_axis_video_TDEST),
    .vld_in(s_axis_video_TVALID),
    .ack_in(regslice_both_s_axis_video_V_dest_V_U_ack_in),
    .data_out(s_axis_video_TDEST_int_regslice),
    .vld_out(regslice_both_s_axis_video_V_dest_V_U_vld_out),
    .ack_out(s_axis_video_TREADY_int_regslice),
    .apdone_blk(regslice_both_s_axis_video_V_dest_V_U_apdone_blk)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((1'b1 == ap_CS_fsm_state5) & (icmp_ln188_fu_282_p2 == 1'd1))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_AXIvideo2MultiPixStream_Pipeline_loop_wait_for_eol_fu_180_ap_start_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_state7)) begin
            grp_AXIvideo2MultiPixStream_Pipeline_loop_wait_for_eol_fu_180_ap_start_reg <= 1'b1;
        end else if ((grp_AXIvideo2MultiPixStream_Pipeline_loop_wait_for_eol_fu_180_ap_ready == 1'b1)) begin
            grp_AXIvideo2MultiPixStream_Pipeline_loop_wait_for_eol_fu_180_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_AXIvideo2MultiPixStream_Pipeline_loop_wait_for_start_fu_132_ap_start_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_state2)) begin
            grp_AXIvideo2MultiPixStream_Pipeline_loop_wait_for_start_fu_132_ap_start_reg <= 1'b1;
        end else if ((grp_AXIvideo2MultiPixStream_Pipeline_loop_wait_for_start_fu_132_ap_ready == 1'b1)) begin
            grp_AXIvideo2MultiPixStream_Pipeline_loop_wait_for_start_fu_132_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_AXIvideo2MultiPixStream_Pipeline_loop_width_fu_152_ap_start_reg <= 1'b0;
    end else begin
        if (((1'b1 == ap_CS_fsm_state5) & (icmp_ln188_fu_282_p2 == 1'd0))) begin
            grp_AXIvideo2MultiPixStream_Pipeline_loop_width_fu_152_ap_start_reg <= 1'b1;
        end else if ((grp_AXIvideo2MultiPixStream_Pipeline_loop_width_fu_152_ap_ready == 1'b1)) begin
            grp_AXIvideo2MultiPixStream_Pipeline_loop_width_fu_152_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_reg_unsigned_short_s_fu_216_ap_start_reg <= 1'b0;
    end else begin
        if (((1'b1 == ap_NS_fsm_state3) & (1'b1 == ap_CS_fsm_state2))) begin
            grp_reg_unsigned_short_s_fu_216_ap_start_reg <= 1'b1;
        end else if ((grp_reg_unsigned_short_s_fu_216_ap_ready == 1'b1)) begin
            grp_reg_unsigned_short_s_fu_216_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_reg_unsigned_short_s_fu_222_ap_start_reg <= 1'b0;
    end else begin
        if (((1'b1 == ap_NS_fsm_state3) & (1'b1 == ap_CS_fsm_state2))) begin
            grp_reg_unsigned_short_s_fu_222_ap_start_reg <= 1'b1;
        end else if ((grp_reg_unsigned_short_s_fu_222_ap_ready == 1'b1)) begin
            grp_reg_unsigned_short_s_fu_222_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state8) & (grp_AXIvideo2MultiPixStream_Pipeline_loop_wait_for_eol_fu_180_axi_data_4_out_ap_vld == 1'b1))) begin
        axi_data_2_fu_74 <= grp_AXIvideo2MultiPixStream_Pipeline_loop_wait_for_eol_fu_180_axi_data_4_out;
    end else if (((grp_AXIvideo2MultiPixStream_Pipeline_loop_wait_for_start_fu_132_axi_data_out_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state3))) begin
        axi_data_2_fu_74 <= grp_AXIvideo2MultiPixStream_Pipeline_loop_wait_for_start_fu_132_axi_data_out;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state9)) begin
        axi_last_2_reg_122 <= axi_last_4_loc_fu_82;
    end else if ((1'b1 == ap_CS_fsm_state4)) begin
        axi_last_2_reg_122 <= grp_AXIvideo2MultiPixStream_Pipeline_loop_wait_for_start_fu_132_axi_last_out;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_state1) & (1'b1 == ap_CS_fsm_state1))) begin
        i_fu_78 <= 12'd0;
    end else if (((1'b1 == ap_CS_fsm_state5) & (icmp_ln188_fu_282_p2 == 1'd0))) begin
        i_fu_78 <= i_5_fu_287_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state9)) begin
        sof_reg_110 <= and_ln216_reg_465;
    end else if ((1'b1 == ap_CS_fsm_state4)) begin
        sof_reg_110 <= 1'd1;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state5)) begin
        and_ln216_reg_465 <= and_ln216_fu_297_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state8) & (grp_AXIvideo2MultiPixStream_Pipeline_loop_wait_for_eol_fu_180_axi_last_4_out_ap_vld == 1'b1))) begin
        axi_last_4_loc_fu_82 <= grp_AXIvideo2MultiPixStream_Pipeline_loop_wait_for_eol_fu_180_axi_last_4_out;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        cmp10252_i_reg_449 <= cmp10252_i_fu_267_p2;
        cols_reg_441 <= grp_reg_unsigned_short_s_fu_222_ap_return;
        rows_reg_436 <= grp_reg_unsigned_short_s_fu_216_ap_return;
        xor_ln216_reg_454 <= xor_ln216_fu_273_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state7)) begin
        select_ln216_reg_476 <= select_ln216_fu_351_p3;
    end
end

always @ (*) begin
    if ((1'b1 == ap_block_state1)) begin
        ap_ST_fsm_state1_blk = 1'b1;
    end else begin
        ap_ST_fsm_state1_blk = 1'b0;
    end
end

assign ap_ST_fsm_state2_blk = 1'b0;

always @ (*) begin
    if ((grp_AXIvideo2MultiPixStream_Pipeline_loop_wait_for_start_fu_132_ap_done == 1'b0)) begin
        ap_ST_fsm_state3_blk = 1'b1;
    end else begin
        ap_ST_fsm_state3_blk = 1'b0;
    end
end

assign ap_ST_fsm_state4_blk = 1'b0;

assign ap_ST_fsm_state5_blk = 1'b0;

always @ (*) begin
    if ((grp_AXIvideo2MultiPixStream_Pipeline_loop_width_fu_152_ap_done == 1'b0)) begin
        ap_ST_fsm_state6_blk = 1'b1;
    end else begin
        ap_ST_fsm_state6_blk = 1'b0;
    end
end

assign ap_ST_fsm_state7_blk = 1'b0;

always @ (*) begin
    if ((grp_AXIvideo2MultiPixStream_Pipeline_loop_wait_for_eol_fu_180_ap_done == 1'b0)) begin
        ap_ST_fsm_state8_blk = 1'b1;
    end else begin
        ap_ST_fsm_state8_blk = 1'b0;
    end
end

assign ap_ST_fsm_state9_blk = 1'b0;

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state5) & (icmp_ln188_fu_282_p2 == 1'd1))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = ap_done_reg;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state5) & (icmp_ln188_fu_282_p2 == 1'd1))) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state4) | ((grp_AXIvideo2MultiPixStream_Pipeline_loop_wait_for_start_fu_132_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state3)))) begin
        grp_reg_unsigned_short_s_fu_216_ap_ce = 1'b1;
    end else begin
        grp_reg_unsigned_short_s_fu_216_ap_ce = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state4) | ((grp_AXIvideo2MultiPixStream_Pipeline_loop_wait_for_start_fu_132_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state3)))) begin
        grp_reg_unsigned_short_s_fu_222_ap_ce = 1'b1;
    end else begin
        grp_reg_unsigned_short_s_fu_222_ap_ce = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state8)) begin
        s_axis_video_TREADY_int_regslice = grp_AXIvideo2MultiPixStream_Pipeline_loop_wait_for_eol_fu_180_s_axis_video_TREADY;
    end else if ((1'b1 == ap_CS_fsm_state6)) begin
        s_axis_video_TREADY_int_regslice = grp_AXIvideo2MultiPixStream_Pipeline_loop_width_fu_152_s_axis_video_TREADY;
    end else if ((1'b1 == ap_CS_fsm_state3)) begin
        s_axis_video_TREADY_int_regslice = grp_AXIvideo2MultiPixStream_Pipeline_loop_wait_for_start_fu_132_s_axis_video_TREADY;
    end else begin
        s_axis_video_TREADY_int_regslice = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if (((1'b0 == ap_block_state1) & (1'b1 == ap_CS_fsm_state1))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_state2 : begin
            ap_NS_fsm = ap_ST_fsm_state3;
        end
        ap_ST_fsm_state3 : begin
            if (((grp_AXIvideo2MultiPixStream_Pipeline_loop_wait_for_start_fu_132_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state3))) begin
                ap_NS_fsm = ap_ST_fsm_state4;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state3;
            end
        end
        ap_ST_fsm_state4 : begin
            ap_NS_fsm = ap_ST_fsm_state5;
        end
        ap_ST_fsm_state5 : begin
            if (((1'b1 == ap_CS_fsm_state5) & (icmp_ln188_fu_282_p2 == 1'd1))) begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state6;
            end
        end
        ap_ST_fsm_state6 : begin
            if (((grp_AXIvideo2MultiPixStream_Pipeline_loop_width_fu_152_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state6))) begin
                ap_NS_fsm = ap_ST_fsm_state7;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state6;
            end
        end
        ap_ST_fsm_state7 : begin
            ap_NS_fsm = ap_ST_fsm_state8;
        end
        ap_ST_fsm_state8 : begin
            if (((1'b1 == ap_CS_fsm_state8) & (grp_AXIvideo2MultiPixStream_Pipeline_loop_wait_for_eol_fu_180_ap_done == 1'b1))) begin
                ap_NS_fsm = ap_ST_fsm_state9;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state8;
            end
        end
        ap_ST_fsm_state9 : begin
            ap_NS_fsm = ap_ST_fsm_state5;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign and_ln216_fu_297_p2 = (xor_ln216_reg_454 & sof_reg_110);

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state2 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_state3 = ap_CS_fsm[32'd2];

assign ap_CS_fsm_state4 = ap_CS_fsm[32'd3];

assign ap_CS_fsm_state5 = ap_CS_fsm[32'd4];

assign ap_CS_fsm_state6 = ap_CS_fsm[32'd5];

assign ap_CS_fsm_state7 = ap_CS_fsm[32'd6];

assign ap_CS_fsm_state8 = ap_CS_fsm[32'd7];

assign ap_CS_fsm_state9 = ap_CS_fsm[32'd8];

assign ap_NS_fsm_state3 = ap_NS_fsm[32'd2];

always @ (*) begin
    ap_block_state1 = ((ap_done_reg == 1'b1) | (ap_start == 1'b0));
end

assign cmp10252_i_fu_267_p2 = ((grp_reg_unsigned_short_s_fu_222_ap_return != 12'd0) ? 1'b1 : 1'b0);

assign grp_AXIvideo2MultiPixStream_Pipeline_loop_wait_for_eol_fu_180_ap_start = grp_AXIvideo2MultiPixStream_Pipeline_loop_wait_for_eol_fu_180_ap_start_reg;

assign grp_AXIvideo2MultiPixStream_Pipeline_loop_wait_for_start_fu_132_ap_start = grp_AXIvideo2MultiPixStream_Pipeline_loop_wait_for_start_fu_132_ap_start_reg;

assign grp_AXIvideo2MultiPixStream_Pipeline_loop_width_fu_152_ap_start = grp_AXIvideo2MultiPixStream_Pipeline_loop_width_fu_152_ap_start_reg;

assign grp_reg_unsigned_short_s_fu_216_ap_start = grp_reg_unsigned_short_s_fu_216_ap_start_reg;

assign grp_reg_unsigned_short_s_fu_216_d = height[11:0];

assign grp_reg_unsigned_short_s_fu_222_ap_start = grp_reg_unsigned_short_s_fu_222_ap_start_reg;

assign grp_reg_unsigned_short_s_fu_222_d = width[11:0];

assign i_5_fu_287_p2 = (i_fu_78 + 12'd1);

assign icmp_ln188_fu_282_p2 = ((i_fu_78 == rows_reg_436) ? 1'b1 : 1'b0);

assign imgRgb_din = grp_AXIvideo2MultiPixStream_Pipeline_loop_width_fu_152_imgRgb_din;

assign imgRgb_write = grp_AXIvideo2MultiPixStream_Pipeline_loop_width_fu_152_imgRgb_write;

assign s_axis_video_TREADY = regslice_both_s_axis_video_V_data_V_U_ack_in;

assign select_ln216_fu_351_p3 = ((cmp10252_i_reg_449[0:0] == 1'b1) ? grp_AXIvideo2MultiPixStream_Pipeline_loop_width_fu_152_eol_out : axi_last_2_reg_122);

assign xor_ln216_fu_273_p2 = (cmp10252_i_fu_267_p2 ^ 1'd1);

endmodule //system_v_gamma_lut_0_0_AXIvideo2MultiPixStream
