-- ==============================================================
-- Generated by Vitis HLS v2024.2
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2024 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity system_v_tpg_0_0_MultiPixStream2AXIvideo is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_continue : IN STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    ovrlayYUV_dout : IN STD_LOGIC_VECTOR (29 downto 0);
    ovrlayYUV_empty_n : IN STD_LOGIC;
    ovrlayYUV_read : OUT STD_LOGIC;
    ovrlayYUV_num_data_valid : IN STD_LOGIC_VECTOR (4 downto 0);
    ovrlayYUV_fifo_cap : IN STD_LOGIC_VECTOR (4 downto 0);
    m_axis_video_TDATA : OUT STD_LOGIC_VECTOR (31 downto 0);
    m_axis_video_TVALID : OUT STD_LOGIC;
    m_axis_video_TREADY : IN STD_LOGIC;
    m_axis_video_TKEEP : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axis_video_TSTRB : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axis_video_TUSER : OUT STD_LOGIC_VECTOR (0 downto 0);
    m_axis_video_TLAST : OUT STD_LOGIC_VECTOR (0 downto 0);
    m_axis_video_TID : OUT STD_LOGIC_VECTOR (0 downto 0);
    m_axis_video_TDEST : OUT STD_LOGIC_VECTOR (0 downto 0);
    height_val5_dout : IN STD_LOGIC_VECTOR (11 downto 0);
    height_val5_empty_n : IN STD_LOGIC;
    height_val5_read : OUT STD_LOGIC;
    height_val5_num_data_valid : IN STD_LOGIC_VECTOR (2 downto 0);
    height_val5_fifo_cap : IN STD_LOGIC_VECTOR (2 downto 0);
    width_val10_dout : IN STD_LOGIC_VECTOR (12 downto 0);
    width_val10_empty_n : IN STD_LOGIC;
    width_val10_read : OUT STD_LOGIC;
    width_val10_num_data_valid : IN STD_LOGIC_VECTOR (2 downto 0);
    width_val10_fifo_cap : IN STD_LOGIC_VECTOR (2 downto 0);
    colorFormat_val27_dout : IN STD_LOGIC_VECTOR (7 downto 0);
    colorFormat_val27_empty_n : IN STD_LOGIC;
    colorFormat_val27_read : OUT STD_LOGIC;
    colorFormat_val27_num_data_valid : IN STD_LOGIC_VECTOR (2 downto 0);
    colorFormat_val27_fifo_cap : IN STD_LOGIC_VECTOR (2 downto 0);
    fid_in_val12_dout : IN STD_LOGIC_VECTOR (0 downto 0);
    fid_in_val12_empty_n : IN STD_LOGIC;
    fid_in_val12_read : OUT STD_LOGIC;
    fid_in_val12_num_data_valid : IN STD_LOGIC_VECTOR (3 downto 0);
    fid_in_val12_fifo_cap : IN STD_LOGIC_VECTOR (3 downto 0);
    fid : OUT STD_LOGIC_VECTOR (0 downto 0);
    fid_ap_vld : OUT STD_LOGIC;
    field_id_val11_dout : IN STD_LOGIC_VECTOR (15 downto 0);
    field_id_val11_empty_n : IN STD_LOGIC;
    field_id_val11_read : OUT STD_LOGIC;
    field_id_val11_num_data_valid : IN STD_LOGIC_VECTOR (3 downto 0);
    field_id_val11_fifo_cap : IN STD_LOGIC_VECTOR (3 downto 0) );
end;


architecture behav of system_v_tpg_0_0_MultiPixStream2AXIvideo is 
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_state1 : STD_LOGIC_VECTOR (3 downto 0) := "0001";
    constant ap_ST_fsm_state2 : STD_LOGIC_VECTOR (3 downto 0) := "0010";
    constant ap_ST_fsm_state3 : STD_LOGIC_VECTOR (3 downto 0) := "0100";
    constant ap_ST_fsm_state4 : STD_LOGIC_VECTOR (3 downto 0) := "1000";
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_lv1_0 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    constant ap_const_lv16_0 : STD_LOGIC_VECTOR (15 downto 0) := "0000000000000000";
    constant ap_const_boolean_0 : BOOLEAN := false;
    constant ap_const_lv32_1 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000001";
    constant ap_const_lv32_2 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000010";
    constant ap_const_lv1_1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv12_0 : STD_LOGIC_VECTOR (11 downto 0) := "000000000000";
    constant ap_const_lv32_3 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000011";
    constant ap_const_lv13_1FFF : STD_LOGIC_VECTOR (12 downto 0) := "1111111111111";
    constant ap_const_lv16_3 : STD_LOGIC_VECTOR (15 downto 0) := "0000000000000011";
    constant ap_const_lv13_0 : STD_LOGIC_VECTOR (12 downto 0) := "0000000000000";
    constant ap_const_lv32_F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001111";
    constant ap_const_lv16_1 : STD_LOGIC_VECTOR (15 downto 0) := "0000000000000001";
    constant ap_const_lv12_1 : STD_LOGIC_VECTOR (11 downto 0) := "000000000001";
    constant ap_const_lv5_0 : STD_LOGIC_VECTOR (4 downto 0) := "00000";

attribute shreg_extract : string;
    signal ap_done_reg : STD_LOGIC := '0';
    signal ap_CS_fsm : STD_LOGIC_VECTOR (3 downto 0) := "0001";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_state1 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state1 : signal is "none";
    signal fidStored : STD_LOGIC_VECTOR (0 downto 0) := "0";
    signal counter : STD_LOGIC_VECTOR (15 downto 0) := "0000000000000000";
    signal height_val5_blk_n : STD_LOGIC;
    signal width_val10_blk_n : STD_LOGIC;
    signal colorFormat_val27_blk_n : STD_LOGIC;
    signal fid_in_val12_blk_n : STD_LOGIC;
    signal field_id_val11_blk_n : STD_LOGIC;
    signal colorFormat_val27_read_reg_411 : STD_LOGIC_VECTOR (7 downto 0);
    signal ap_block_state1 : BOOLEAN;
    signal fid_in_val12_read_reg_416 : STD_LOGIC_VECTOR (0 downto 0);
    signal cols_reg_421 : STD_LOGIC_VECTOR (12 downto 0);
    signal rows_reg_426 : STD_LOGIC_VECTOR (11 downto 0);
    signal sub_i_fu_207_p2 : STD_LOGIC_VECTOR (12 downto 0);
    signal sub_i_reg_431 : STD_LOGIC_VECTOR (12 downto 0);
    signal cmp104_i_fu_213_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal cmp104_i_reg_436 : STD_LOGIC_VECTOR (0 downto 0);
    signal cmp20177_i_fu_219_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal cmp20177_i_reg_441 : STD_LOGIC_VECTOR (0 downto 0);
    signal switch_i_fu_225_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal switch_i_reg_445 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln1038_fu_249_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln1038_reg_450 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln1038_1_fu_255_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln1038_1_reg_455 : STD_LOGIC_VECTOR (0 downto 0);
    signal i_2_fu_293_p2 : STD_LOGIC_VECTOR (11 downto 0);
    signal i_2_reg_463 : STD_LOGIC_VECTOR (11 downto 0);
    signal ap_CS_fsm_state2 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state2 : signal is "none";
    signal grp_MultiPixStream2AXIvideo_Pipeline_VITIS_LOOP_981_2_fu_173_ap_start : STD_LOGIC;
    signal grp_MultiPixStream2AXIvideo_Pipeline_VITIS_LOOP_981_2_fu_173_ap_done : STD_LOGIC;
    signal grp_MultiPixStream2AXIvideo_Pipeline_VITIS_LOOP_981_2_fu_173_ap_idle : STD_LOGIC;
    signal grp_MultiPixStream2AXIvideo_Pipeline_VITIS_LOOP_981_2_fu_173_ap_ready : STD_LOGIC;
    signal grp_MultiPixStream2AXIvideo_Pipeline_VITIS_LOOP_981_2_fu_173_ovrlayYUV_read : STD_LOGIC;
    signal grp_MultiPixStream2AXIvideo_Pipeline_VITIS_LOOP_981_2_fu_173_m_axis_video_TDATA : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_MultiPixStream2AXIvideo_Pipeline_VITIS_LOOP_981_2_fu_173_m_axis_video_TVALID : STD_LOGIC;
    signal grp_MultiPixStream2AXIvideo_Pipeline_VITIS_LOOP_981_2_fu_173_m_axis_video_TREADY : STD_LOGIC;
    signal grp_MultiPixStream2AXIvideo_Pipeline_VITIS_LOOP_981_2_fu_173_m_axis_video_TKEEP : STD_LOGIC_VECTOR (3 downto 0);
    signal grp_MultiPixStream2AXIvideo_Pipeline_VITIS_LOOP_981_2_fu_173_m_axis_video_TSTRB : STD_LOGIC_VECTOR (3 downto 0);
    signal grp_MultiPixStream2AXIvideo_Pipeline_VITIS_LOOP_981_2_fu_173_m_axis_video_TUSER : STD_LOGIC_VECTOR (0 downto 0);
    signal grp_MultiPixStream2AXIvideo_Pipeline_VITIS_LOOP_981_2_fu_173_m_axis_video_TLAST : STD_LOGIC_VECTOR (0 downto 0);
    signal grp_MultiPixStream2AXIvideo_Pipeline_VITIS_LOOP_981_2_fu_173_m_axis_video_TID : STD_LOGIC_VECTOR (0 downto 0);
    signal grp_MultiPixStream2AXIvideo_Pipeline_VITIS_LOOP_981_2_fu_173_m_axis_video_TDEST : STD_LOGIC_VECTOR (0 downto 0);
    signal grp_MultiPixStream2AXIvideo_Pipeline_VITIS_LOOP_981_2_fu_173_counter_loc_1_i_out : STD_LOGIC_VECTOR (15 downto 0);
    signal grp_MultiPixStream2AXIvideo_Pipeline_VITIS_LOOP_981_2_fu_173_counter_loc_1_i_out_ap_vld : STD_LOGIC;
    signal grp_MultiPixStream2AXIvideo_Pipeline_VITIS_LOOP_981_2_fu_173_phi_ln1036_out : STD_LOGIC_VECTOR (0 downto 0);
    signal grp_MultiPixStream2AXIvideo_Pipeline_VITIS_LOOP_981_2_fu_173_phi_ln1036_out_ap_vld : STD_LOGIC;
    signal grp_MultiPixStream2AXIvideo_Pipeline_VITIS_LOOP_981_2_fu_173_counter : STD_LOGIC_VECTOR (15 downto 0);
    signal grp_MultiPixStream2AXIvideo_Pipeline_VITIS_LOOP_981_2_fu_173_counter_ap_vld : STD_LOGIC;
    signal grp_MultiPixStream2AXIvideo_Pipeline_VITIS_LOOP_981_2_fu_173_ap_start_reg : STD_LOGIC := '0';
    signal icmp_ln979_fu_288_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_CS_fsm_state3 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state3 : signal is "none";
    signal m_axis_video_TDATA_reg : STD_LOGIC_VECTOR (31 downto 0);
    signal m_axis_video_TKEEP_reg : STD_LOGIC_VECTOR (3 downto 0);
    signal m_axis_video_TSTRB_reg : STD_LOGIC_VECTOR (3 downto 0);
    signal m_axis_video_TUSER_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal m_axis_video_TLAST_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal m_axis_video_TID_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal m_axis_video_TDEST_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal counter_loc_1_i_loc_fu_132 : STD_LOGIC_VECTOR (15 downto 0);
    signal phi_ln1036_loc_fu_128 : STD_LOGIC_VECTOR (0 downto 0);
    signal i_fu_112 : STD_LOGIC_VECTOR (11 downto 0) := "000000000000";
    signal ap_CS_fsm_state4 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state4 : signal is "none";
    signal counter_loc_0_i_fu_116 : STD_LOGIC_VECTOR (15 downto 0) := "0000000000000000";
    signal sof_fu_120 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    signal empty_fu_124 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    signal select_ln1038_fu_344_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal fid_preg : STD_LOGIC_VECTOR (0 downto 0) := "0";
    signal tmp_s_fu_231_p4 : STD_LOGIC_VECTOR (14 downto 0);
    signal tmp_17_fu_241_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal and_ln1038_fu_322_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal xor_ln1053_fu_332_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal or_ln1038_fu_327_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal select_ln1051_fu_338_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_NS_fsm : STD_LOGIC_VECTOR (3 downto 0);
    signal ap_ST_fsm_state1_blk : STD_LOGIC;
    signal ap_ST_fsm_state2_blk : STD_LOGIC;
    signal ap_ST_fsm_state3_blk : STD_LOGIC;
    signal ap_ST_fsm_state4_blk : STD_LOGIC;
    signal ap_ce_reg : STD_LOGIC;

    component system_v_tpg_0_0_MultiPixStream2AXIvideo_Pipeline_VITIS_LOOP_981_2 IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_idle : OUT STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        counter_loc_0_i : IN STD_LOGIC_VECTOR (15 downto 0);
        sof : IN STD_LOGIC_VECTOR (0 downto 0);
        cols : IN STD_LOGIC_VECTOR (12 downto 0);
        ovrlayYUV_dout : IN STD_LOGIC_VECTOR (29 downto 0);
        ovrlayYUV_empty_n : IN STD_LOGIC;
        ovrlayYUV_read : OUT STD_LOGIC;
        ovrlayYUV_num_data_valid : IN STD_LOGIC_VECTOR (4 downto 0);
        ovrlayYUV_fifo_cap : IN STD_LOGIC_VECTOR (4 downto 0);
        colorFormat_val27_load : IN STD_LOGIC_VECTOR (7 downto 0);
        m_axis_video_TDATA : OUT STD_LOGIC_VECTOR (31 downto 0);
        m_axis_video_TVALID : OUT STD_LOGIC;
        m_axis_video_TREADY : IN STD_LOGIC;
        m_axis_video_TKEEP : OUT STD_LOGIC_VECTOR (3 downto 0);
        m_axis_video_TSTRB : OUT STD_LOGIC_VECTOR (3 downto 0);
        m_axis_video_TUSER : OUT STD_LOGIC_VECTOR (0 downto 0);
        m_axis_video_TLAST : OUT STD_LOGIC_VECTOR (0 downto 0);
        m_axis_video_TID : OUT STD_LOGIC_VECTOR (0 downto 0);
        m_axis_video_TDEST : OUT STD_LOGIC_VECTOR (0 downto 0);
        sub_cast_i : IN STD_LOGIC_VECTOR (12 downto 0);
        counter_loc_1_i_out : OUT STD_LOGIC_VECTOR (15 downto 0);
        counter_loc_1_i_out_ap_vld : OUT STD_LOGIC;
        phi_ln1036_out : OUT STD_LOGIC_VECTOR (0 downto 0);
        phi_ln1036_out_ap_vld : OUT STD_LOGIC;
        counter : OUT STD_LOGIC_VECTOR (15 downto 0);
        counter_ap_vld : OUT STD_LOGIC );
    end component;



begin
    grp_MultiPixStream2AXIvideo_Pipeline_VITIS_LOOP_981_2_fu_173 : component system_v_tpg_0_0_MultiPixStream2AXIvideo_Pipeline_VITIS_LOOP_981_2
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => grp_MultiPixStream2AXIvideo_Pipeline_VITIS_LOOP_981_2_fu_173_ap_start,
        ap_done => grp_MultiPixStream2AXIvideo_Pipeline_VITIS_LOOP_981_2_fu_173_ap_done,
        ap_idle => grp_MultiPixStream2AXIvideo_Pipeline_VITIS_LOOP_981_2_fu_173_ap_idle,
        ap_ready => grp_MultiPixStream2AXIvideo_Pipeline_VITIS_LOOP_981_2_fu_173_ap_ready,
        counter_loc_0_i => counter_loc_0_i_fu_116,
        sof => sof_fu_120,
        cols => cols_reg_421,
        ovrlayYUV_dout => ovrlayYUV_dout,
        ovrlayYUV_empty_n => ovrlayYUV_empty_n,
        ovrlayYUV_read => grp_MultiPixStream2AXIvideo_Pipeline_VITIS_LOOP_981_2_fu_173_ovrlayYUV_read,
        ovrlayYUV_num_data_valid => ap_const_lv5_0,
        ovrlayYUV_fifo_cap => ap_const_lv5_0,
        colorFormat_val27_load => colorFormat_val27_read_reg_411,
        m_axis_video_TDATA => grp_MultiPixStream2AXIvideo_Pipeline_VITIS_LOOP_981_2_fu_173_m_axis_video_TDATA,
        m_axis_video_TVALID => grp_MultiPixStream2AXIvideo_Pipeline_VITIS_LOOP_981_2_fu_173_m_axis_video_TVALID,
        m_axis_video_TREADY => grp_MultiPixStream2AXIvideo_Pipeline_VITIS_LOOP_981_2_fu_173_m_axis_video_TREADY,
        m_axis_video_TKEEP => grp_MultiPixStream2AXIvideo_Pipeline_VITIS_LOOP_981_2_fu_173_m_axis_video_TKEEP,
        m_axis_video_TSTRB => grp_MultiPixStream2AXIvideo_Pipeline_VITIS_LOOP_981_2_fu_173_m_axis_video_TSTRB,
        m_axis_video_TUSER => grp_MultiPixStream2AXIvideo_Pipeline_VITIS_LOOP_981_2_fu_173_m_axis_video_TUSER,
        m_axis_video_TLAST => grp_MultiPixStream2AXIvideo_Pipeline_VITIS_LOOP_981_2_fu_173_m_axis_video_TLAST,
        m_axis_video_TID => grp_MultiPixStream2AXIvideo_Pipeline_VITIS_LOOP_981_2_fu_173_m_axis_video_TID,
        m_axis_video_TDEST => grp_MultiPixStream2AXIvideo_Pipeline_VITIS_LOOP_981_2_fu_173_m_axis_video_TDEST,
        sub_cast_i => sub_i_reg_431,
        counter_loc_1_i_out => grp_MultiPixStream2AXIvideo_Pipeline_VITIS_LOOP_981_2_fu_173_counter_loc_1_i_out,
        counter_loc_1_i_out_ap_vld => grp_MultiPixStream2AXIvideo_Pipeline_VITIS_LOOP_981_2_fu_173_counter_loc_1_i_out_ap_vld,
        phi_ln1036_out => grp_MultiPixStream2AXIvideo_Pipeline_VITIS_LOOP_981_2_fu_173_phi_ln1036_out,
        phi_ln1036_out_ap_vld => grp_MultiPixStream2AXIvideo_Pipeline_VITIS_LOOP_981_2_fu_173_phi_ln1036_out_ap_vld,
        counter => grp_MultiPixStream2AXIvideo_Pipeline_VITIS_LOOP_981_2_fu_173_counter,
        counter_ap_vld => grp_MultiPixStream2AXIvideo_Pipeline_VITIS_LOOP_981_2_fu_173_counter_ap_vld);





    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_CS_fsm <= ap_ST_fsm_state1;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    ap_done_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_done_reg <= ap_const_logic_0;
            else
                if ((ap_continue = ap_const_logic_1)) then 
                    ap_done_reg <= ap_const_logic_0;
                elsif (((ap_const_logic_1 = ap_CS_fsm_state2) and (icmp_ln979_fu_288_p2 = ap_const_lv1_1))) then 
                    ap_done_reg <= ap_const_logic_1;
                end if; 
            end if;
        end if;
    end process;


    fid_preg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                fid_preg <= ap_const_lv1_0;
            else
                if (((ap_const_logic_1 = ap_CS_fsm_state4) and (cmp20177_i_reg_441 = ap_const_lv1_0))) then 
                    fid_preg <= select_ln1038_fu_344_p3;
                elsif (((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_const_boolean_0 = ap_block_state1))) then 
                    fid_preg <= fidStored;
                end if; 
            end if;
        end if;
    end process;


    grp_MultiPixStream2AXIvideo_Pipeline_VITIS_LOOP_981_2_fu_173_ap_start_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                grp_MultiPixStream2AXIvideo_Pipeline_VITIS_LOOP_981_2_fu_173_ap_start_reg <= ap_const_logic_0;
            else
                if (((ap_const_logic_1 = ap_CS_fsm_state2) and (icmp_ln979_fu_288_p2 = ap_const_lv1_0))) then 
                    grp_MultiPixStream2AXIvideo_Pipeline_VITIS_LOOP_981_2_fu_173_ap_start_reg <= ap_const_logic_1;
                elsif ((grp_MultiPixStream2AXIvideo_Pipeline_VITIS_LOOP_981_2_fu_173_ap_ready = ap_const_logic_1)) then 
                    grp_MultiPixStream2AXIvideo_Pipeline_VITIS_LOOP_981_2_fu_173_ap_start_reg <= ap_const_logic_0;
                end if; 
            end if;
        end if;
    end process;


    counter_loc_0_i_fu_116_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_const_boolean_0 = ap_block_state1))) then 
                counter_loc_0_i_fu_116 <= counter;
            elsif ((ap_const_logic_1 = ap_CS_fsm_state4)) then 
                counter_loc_0_i_fu_116 <= counter_loc_1_i_loc_fu_132;
            end if; 
        end if;
    end process;

    empty_fu_124_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_const_boolean_0 = ap_block_state1))) then 
                empty_fu_124 <= fidStored;
            elsif (((ap_const_logic_1 = ap_CS_fsm_state4) and (cmp20177_i_reg_441 = ap_const_lv1_0))) then 
                empty_fu_124 <= select_ln1038_fu_344_p3;
            end if; 
        end if;
    end process;

    i_fu_112_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_const_boolean_0 = ap_block_state1))) then 
                i_fu_112 <= ap_const_lv12_0;
            elsif ((ap_const_logic_1 = ap_CS_fsm_state4)) then 
                i_fu_112 <= i_2_reg_463;
            end if; 
        end if;
    end process;

    sof_fu_120_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_const_boolean_0 = ap_block_state1))) then 
                sof_fu_120 <= ap_const_lv1_1;
            elsif (((ap_const_logic_1 = ap_CS_fsm_state4) and (cmp20177_i_reg_441 = ap_const_lv1_0))) then 
                sof_fu_120 <= ap_const_lv1_0;
            end if; 
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_const_boolean_0 = ap_block_state1))) then
                cmp104_i_reg_436 <= cmp104_i_fu_213_p2;
                cmp20177_i_reg_441 <= cmp20177_i_fu_219_p2;
                colorFormat_val27_read_reg_411 <= colorFormat_val27_dout;
                cols_reg_421 <= width_val10_dout;
                fid_in_val12_read_reg_416 <= fid_in_val12_dout;
                icmp_ln1038_1_reg_455 <= icmp_ln1038_1_fu_255_p2;
                icmp_ln1038_reg_450 <= icmp_ln1038_fu_249_p2;
                rows_reg_426 <= height_val5_dout;
                sub_i_reg_431 <= sub_i_fu_207_p2;
                switch_i_reg_445 <= switch_i_fu_225_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_state3) and (grp_MultiPixStream2AXIvideo_Pipeline_VITIS_LOOP_981_2_fu_173_counter_ap_vld = ap_const_logic_1))) then
                counter <= grp_MultiPixStream2AXIvideo_Pipeline_VITIS_LOOP_981_2_fu_173_counter;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_state3) and (grp_MultiPixStream2AXIvideo_Pipeline_VITIS_LOOP_981_2_fu_173_counter_loc_1_i_out_ap_vld = ap_const_logic_1))) then
                counter_loc_1_i_loc_fu_132 <= grp_MultiPixStream2AXIvideo_Pipeline_VITIS_LOOP_981_2_fu_173_counter_loc_1_i_out;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_state2) and (icmp_ln979_fu_288_p2 = ap_const_lv1_1))) then
                fidStored <= empty_fu_124;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state2)) then
                i_2_reg_463 <= i_2_fu_293_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_state3) and (grp_MultiPixStream2AXIvideo_Pipeline_VITIS_LOOP_981_2_fu_173_m_axis_video_TVALID = ap_const_logic_1))) then
                m_axis_video_TDATA_reg <= grp_MultiPixStream2AXIvideo_Pipeline_VITIS_LOOP_981_2_fu_173_m_axis_video_TDATA;
                m_axis_video_TDEST_reg <= grp_MultiPixStream2AXIvideo_Pipeline_VITIS_LOOP_981_2_fu_173_m_axis_video_TDEST;
                m_axis_video_TID_reg <= grp_MultiPixStream2AXIvideo_Pipeline_VITIS_LOOP_981_2_fu_173_m_axis_video_TID;
                m_axis_video_TKEEP_reg <= grp_MultiPixStream2AXIvideo_Pipeline_VITIS_LOOP_981_2_fu_173_m_axis_video_TKEEP;
                m_axis_video_TLAST_reg <= grp_MultiPixStream2AXIvideo_Pipeline_VITIS_LOOP_981_2_fu_173_m_axis_video_TLAST;
                m_axis_video_TSTRB_reg <= grp_MultiPixStream2AXIvideo_Pipeline_VITIS_LOOP_981_2_fu_173_m_axis_video_TSTRB;
                m_axis_video_TUSER_reg <= grp_MultiPixStream2AXIvideo_Pipeline_VITIS_LOOP_981_2_fu_173_m_axis_video_TUSER;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_state3) and (grp_MultiPixStream2AXIvideo_Pipeline_VITIS_LOOP_981_2_fu_173_phi_ln1036_out_ap_vld = ap_const_logic_1))) then
                phi_ln1036_loc_fu_128 <= grp_MultiPixStream2AXIvideo_Pipeline_VITIS_LOOP_981_2_fu_173_phi_ln1036_out;
            end if;
        end if;
    end process;

    ap_NS_fsm_assign_proc : process (ap_CS_fsm, ap_CS_fsm_state1, ap_block_state1, ap_CS_fsm_state2, grp_MultiPixStream2AXIvideo_Pipeline_VITIS_LOOP_981_2_fu_173_ap_done, icmp_ln979_fu_288_p2, ap_CS_fsm_state3)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_state1 => 
                if (((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_const_boolean_0 = ap_block_state1))) then
                    ap_NS_fsm <= ap_ST_fsm_state2;
                else
                    ap_NS_fsm <= ap_ST_fsm_state1;
                end if;
            when ap_ST_fsm_state2 => 
                if (((ap_const_logic_1 = ap_CS_fsm_state2) and (icmp_ln979_fu_288_p2 = ap_const_lv1_1))) then
                    ap_NS_fsm <= ap_ST_fsm_state1;
                else
                    ap_NS_fsm <= ap_ST_fsm_state3;
                end if;
            when ap_ST_fsm_state3 => 
                if (((ap_const_logic_1 = ap_CS_fsm_state3) and (grp_MultiPixStream2AXIvideo_Pipeline_VITIS_LOOP_981_2_fu_173_ap_done = ap_const_logic_1))) then
                    ap_NS_fsm <= ap_ST_fsm_state4;
                else
                    ap_NS_fsm <= ap_ST_fsm_state3;
                end if;
            when ap_ST_fsm_state4 => 
                ap_NS_fsm <= ap_ST_fsm_state2;
            when others =>  
                ap_NS_fsm <= "XXXX";
        end case;
    end process;
    and_ln1038_fu_322_p2 <= (phi_ln1036_loc_fu_128 and icmp_ln1038_reg_450);
    ap_CS_fsm_state1 <= ap_CS_fsm(0);
    ap_CS_fsm_state2 <= ap_CS_fsm(1);
    ap_CS_fsm_state3 <= ap_CS_fsm(2);
    ap_CS_fsm_state4 <= ap_CS_fsm(3);

    ap_ST_fsm_state1_blk_assign_proc : process(ap_block_state1)
    begin
        if ((ap_const_boolean_1 = ap_block_state1)) then 
            ap_ST_fsm_state1_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state1_blk <= ap_const_logic_0;
        end if; 
    end process;

    ap_ST_fsm_state2_blk <= ap_const_logic_0;

    ap_ST_fsm_state3_blk_assign_proc : process(grp_MultiPixStream2AXIvideo_Pipeline_VITIS_LOOP_981_2_fu_173_ap_done)
    begin
        if ((grp_MultiPixStream2AXIvideo_Pipeline_VITIS_LOOP_981_2_fu_173_ap_done = ap_const_logic_0)) then 
            ap_ST_fsm_state3_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state3_blk <= ap_const_logic_0;
        end if; 
    end process;

    ap_ST_fsm_state4_blk <= ap_const_logic_0;

    ap_block_state1_assign_proc : process(ap_start, ap_done_reg, height_val5_empty_n, width_val10_empty_n, colorFormat_val27_empty_n, fid_in_val12_empty_n, field_id_val11_empty_n)
    begin
                ap_block_state1 <= ((ap_start = ap_const_logic_0) or (field_id_val11_empty_n = ap_const_logic_0) or (fid_in_val12_empty_n = ap_const_logic_0) or (colorFormat_val27_empty_n = ap_const_logic_0) or (width_val10_empty_n = ap_const_logic_0) or (height_val5_empty_n = ap_const_logic_0) or (ap_done_reg = ap_const_logic_1));
    end process;


    ap_done_assign_proc : process(ap_done_reg, ap_CS_fsm_state2, icmp_ln979_fu_288_p2)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state2) and (icmp_ln979_fu_288_p2 = ap_const_lv1_1))) then 
            ap_done <= ap_const_logic_1;
        else 
            ap_done <= ap_done_reg;
        end if; 
    end process;


    ap_idle_assign_proc : process(ap_start, ap_CS_fsm_state1)
    begin
        if (((ap_start = ap_const_logic_0) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;


    ap_ready_assign_proc : process(ap_CS_fsm_state2, icmp_ln979_fu_288_p2)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state2) and (icmp_ln979_fu_288_p2 = ap_const_lv1_1))) then 
            ap_ready <= ap_const_logic_1;
        else 
            ap_ready <= ap_const_logic_0;
        end if; 
    end process;

    cmp104_i_fu_213_p2 <= "1" when (field_id_val11_dout = ap_const_lv16_3) else "0";
    cmp20177_i_fu_219_p2 <= "1" when (width_val10_dout = ap_const_lv13_0) else "0";

    colorFormat_val27_blk_n_assign_proc : process(ap_start, ap_done_reg, ap_CS_fsm_state1, colorFormat_val27_empty_n)
    begin
        if ((not(((ap_start = ap_const_logic_0) or (ap_done_reg = ap_const_logic_1))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            colorFormat_val27_blk_n <= colorFormat_val27_empty_n;
        else 
            colorFormat_val27_blk_n <= ap_const_logic_1;
        end if; 
    end process;


    colorFormat_val27_read_assign_proc : process(ap_CS_fsm_state1, ap_block_state1)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_const_boolean_0 = ap_block_state1))) then 
            colorFormat_val27_read <= ap_const_logic_1;
        else 
            colorFormat_val27_read <= ap_const_logic_0;
        end if; 
    end process;


    fid_assign_proc : process(ap_CS_fsm_state1, fidStored, ap_block_state1, cmp20177_i_reg_441, ap_CS_fsm_state4, select_ln1038_fu_344_p3, fid_preg)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state4) and (cmp20177_i_reg_441 = ap_const_lv1_0))) then 
            fid <= select_ln1038_fu_344_p3;
        elsif (((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_const_boolean_0 = ap_block_state1))) then 
            fid <= fidStored;
        else 
            fid <= fid_preg;
        end if; 
    end process;


    fid_ap_vld_assign_proc : process(ap_CS_fsm_state1, ap_block_state1, cmp20177_i_reg_441, ap_CS_fsm_state4)
    begin
        if ((((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_const_boolean_0 = ap_block_state1)) or ((ap_const_logic_1 = ap_CS_fsm_state4) and (cmp20177_i_reg_441 = ap_const_lv1_0)))) then 
            fid_ap_vld <= ap_const_logic_1;
        else 
            fid_ap_vld <= ap_const_logic_0;
        end if; 
    end process;


    fid_in_val12_blk_n_assign_proc : process(ap_start, ap_done_reg, ap_CS_fsm_state1, fid_in_val12_empty_n)
    begin
        if ((not(((ap_start = ap_const_logic_0) or (ap_done_reg = ap_const_logic_1))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            fid_in_val12_blk_n <= fid_in_val12_empty_n;
        else 
            fid_in_val12_blk_n <= ap_const_logic_1;
        end if; 
    end process;


    fid_in_val12_read_assign_proc : process(ap_CS_fsm_state1, ap_block_state1)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_const_boolean_0 = ap_block_state1))) then 
            fid_in_val12_read <= ap_const_logic_1;
        else 
            fid_in_val12_read <= ap_const_logic_0;
        end if; 
    end process;


    field_id_val11_blk_n_assign_proc : process(ap_start, ap_done_reg, ap_CS_fsm_state1, field_id_val11_empty_n)
    begin
        if ((not(((ap_start = ap_const_logic_0) or (ap_done_reg = ap_const_logic_1))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            field_id_val11_blk_n <= field_id_val11_empty_n;
        else 
            field_id_val11_blk_n <= ap_const_logic_1;
        end if; 
    end process;


    field_id_val11_read_assign_proc : process(ap_CS_fsm_state1, ap_block_state1)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_const_boolean_0 = ap_block_state1))) then 
            field_id_val11_read <= ap_const_logic_1;
        else 
            field_id_val11_read <= ap_const_logic_0;
        end if; 
    end process;

    grp_MultiPixStream2AXIvideo_Pipeline_VITIS_LOOP_981_2_fu_173_ap_start <= grp_MultiPixStream2AXIvideo_Pipeline_VITIS_LOOP_981_2_fu_173_ap_start_reg;
    grp_MultiPixStream2AXIvideo_Pipeline_VITIS_LOOP_981_2_fu_173_m_axis_video_TREADY <= (m_axis_video_TREADY and ap_CS_fsm_state3);

    height_val5_blk_n_assign_proc : process(ap_start, ap_done_reg, ap_CS_fsm_state1, height_val5_empty_n)
    begin
        if ((not(((ap_start = ap_const_logic_0) or (ap_done_reg = ap_const_logic_1))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            height_val5_blk_n <= height_val5_empty_n;
        else 
            height_val5_blk_n <= ap_const_logic_1;
        end if; 
    end process;


    height_val5_read_assign_proc : process(ap_CS_fsm_state1, ap_block_state1)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_const_boolean_0 = ap_block_state1))) then 
            height_val5_read <= ap_const_logic_1;
        else 
            height_val5_read <= ap_const_logic_0;
        end if; 
    end process;

    i_2_fu_293_p2 <= std_logic_vector(unsigned(i_fu_112) + unsigned(ap_const_lv12_1));
    icmp_ln1038_1_fu_255_p2 <= "0" when (tmp_17_fu_241_p3 = ap_const_lv16_1) else "1";
    icmp_ln1038_fu_249_p2 <= "0" when (field_id_val11_dout = ap_const_lv16_0) else "1";
    icmp_ln979_fu_288_p2 <= "1" when (i_fu_112 = rows_reg_426) else "0";

    m_axis_video_TDATA_assign_proc : process(grp_MultiPixStream2AXIvideo_Pipeline_VITIS_LOOP_981_2_fu_173_m_axis_video_TDATA, grp_MultiPixStream2AXIvideo_Pipeline_VITIS_LOOP_981_2_fu_173_m_axis_video_TVALID, ap_CS_fsm_state3, m_axis_video_TDATA_reg)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state3) and (grp_MultiPixStream2AXIvideo_Pipeline_VITIS_LOOP_981_2_fu_173_m_axis_video_TVALID = ap_const_logic_1))) then 
            m_axis_video_TDATA <= grp_MultiPixStream2AXIvideo_Pipeline_VITIS_LOOP_981_2_fu_173_m_axis_video_TDATA;
        else 
            m_axis_video_TDATA <= m_axis_video_TDATA_reg;
        end if; 
    end process;


    m_axis_video_TDEST_assign_proc : process(grp_MultiPixStream2AXIvideo_Pipeline_VITIS_LOOP_981_2_fu_173_m_axis_video_TVALID, grp_MultiPixStream2AXIvideo_Pipeline_VITIS_LOOP_981_2_fu_173_m_axis_video_TDEST, ap_CS_fsm_state3, m_axis_video_TDEST_reg)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state3) and (grp_MultiPixStream2AXIvideo_Pipeline_VITIS_LOOP_981_2_fu_173_m_axis_video_TVALID = ap_const_logic_1))) then 
            m_axis_video_TDEST <= grp_MultiPixStream2AXIvideo_Pipeline_VITIS_LOOP_981_2_fu_173_m_axis_video_TDEST;
        else 
            m_axis_video_TDEST <= m_axis_video_TDEST_reg;
        end if; 
    end process;


    m_axis_video_TID_assign_proc : process(grp_MultiPixStream2AXIvideo_Pipeline_VITIS_LOOP_981_2_fu_173_m_axis_video_TVALID, grp_MultiPixStream2AXIvideo_Pipeline_VITIS_LOOP_981_2_fu_173_m_axis_video_TID, ap_CS_fsm_state3, m_axis_video_TID_reg)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state3) and (grp_MultiPixStream2AXIvideo_Pipeline_VITIS_LOOP_981_2_fu_173_m_axis_video_TVALID = ap_const_logic_1))) then 
            m_axis_video_TID <= grp_MultiPixStream2AXIvideo_Pipeline_VITIS_LOOP_981_2_fu_173_m_axis_video_TID;
        else 
            m_axis_video_TID <= m_axis_video_TID_reg;
        end if; 
    end process;


    m_axis_video_TKEEP_assign_proc : process(grp_MultiPixStream2AXIvideo_Pipeline_VITIS_LOOP_981_2_fu_173_m_axis_video_TVALID, grp_MultiPixStream2AXIvideo_Pipeline_VITIS_LOOP_981_2_fu_173_m_axis_video_TKEEP, ap_CS_fsm_state3, m_axis_video_TKEEP_reg)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state3) and (grp_MultiPixStream2AXIvideo_Pipeline_VITIS_LOOP_981_2_fu_173_m_axis_video_TVALID = ap_const_logic_1))) then 
            m_axis_video_TKEEP <= grp_MultiPixStream2AXIvideo_Pipeline_VITIS_LOOP_981_2_fu_173_m_axis_video_TKEEP;
        else 
            m_axis_video_TKEEP <= m_axis_video_TKEEP_reg;
        end if; 
    end process;


    m_axis_video_TLAST_assign_proc : process(grp_MultiPixStream2AXIvideo_Pipeline_VITIS_LOOP_981_2_fu_173_m_axis_video_TVALID, grp_MultiPixStream2AXIvideo_Pipeline_VITIS_LOOP_981_2_fu_173_m_axis_video_TLAST, ap_CS_fsm_state3, m_axis_video_TLAST_reg)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state3) and (grp_MultiPixStream2AXIvideo_Pipeline_VITIS_LOOP_981_2_fu_173_m_axis_video_TVALID = ap_const_logic_1))) then 
            m_axis_video_TLAST <= grp_MultiPixStream2AXIvideo_Pipeline_VITIS_LOOP_981_2_fu_173_m_axis_video_TLAST;
        else 
            m_axis_video_TLAST <= m_axis_video_TLAST_reg;
        end if; 
    end process;


    m_axis_video_TSTRB_assign_proc : process(grp_MultiPixStream2AXIvideo_Pipeline_VITIS_LOOP_981_2_fu_173_m_axis_video_TVALID, grp_MultiPixStream2AXIvideo_Pipeline_VITIS_LOOP_981_2_fu_173_m_axis_video_TSTRB, ap_CS_fsm_state3, m_axis_video_TSTRB_reg)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state3) and (grp_MultiPixStream2AXIvideo_Pipeline_VITIS_LOOP_981_2_fu_173_m_axis_video_TVALID = ap_const_logic_1))) then 
            m_axis_video_TSTRB <= grp_MultiPixStream2AXIvideo_Pipeline_VITIS_LOOP_981_2_fu_173_m_axis_video_TSTRB;
        else 
            m_axis_video_TSTRB <= m_axis_video_TSTRB_reg;
        end if; 
    end process;


    m_axis_video_TUSER_assign_proc : process(grp_MultiPixStream2AXIvideo_Pipeline_VITIS_LOOP_981_2_fu_173_m_axis_video_TVALID, grp_MultiPixStream2AXIvideo_Pipeline_VITIS_LOOP_981_2_fu_173_m_axis_video_TUSER, ap_CS_fsm_state3, m_axis_video_TUSER_reg)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state3) and (grp_MultiPixStream2AXIvideo_Pipeline_VITIS_LOOP_981_2_fu_173_m_axis_video_TVALID = ap_const_logic_1))) then 
            m_axis_video_TUSER <= grp_MultiPixStream2AXIvideo_Pipeline_VITIS_LOOP_981_2_fu_173_m_axis_video_TUSER;
        else 
            m_axis_video_TUSER <= m_axis_video_TUSER_reg;
        end if; 
    end process;

    m_axis_video_TVALID <= grp_MultiPixStream2AXIvideo_Pipeline_VITIS_LOOP_981_2_fu_173_m_axis_video_TVALID;
    or_ln1038_fu_327_p2 <= (icmp_ln1038_1_reg_455 or and_ln1038_fu_322_p2);
    ovrlayYUV_read <= grp_MultiPixStream2AXIvideo_Pipeline_VITIS_LOOP_981_2_fu_173_ovrlayYUV_read;
    select_ln1038_fu_344_p3 <= 
        or_ln1038_fu_327_p2 when (switch_i_reg_445(0) = '1') else 
        select_ln1051_fu_338_p3;
    select_ln1051_fu_338_p3 <= 
        xor_ln1053_fu_332_p2 when (cmp104_i_reg_436(0) = '1') else 
        fid_in_val12_read_reg_416;
    sub_i_fu_207_p2 <= std_logic_vector(unsigned(width_val10_dout) + unsigned(ap_const_lv13_1FFF));
    switch_i_fu_225_p2 <= "1" when (unsigned(field_id_val11_dout) < unsigned(ap_const_lv16_3)) else "0";
    tmp_17_fu_241_p3 <= (tmp_s_fu_231_p4 & ap_const_lv1_1);
    tmp_s_fu_231_p4 <= field_id_val11_dout(15 downto 1);

    width_val10_blk_n_assign_proc : process(ap_start, ap_done_reg, ap_CS_fsm_state1, width_val10_empty_n)
    begin
        if ((not(((ap_start = ap_const_logic_0) or (ap_done_reg = ap_const_logic_1))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            width_val10_blk_n <= width_val10_empty_n;
        else 
            width_val10_blk_n <= ap_const_logic_1;
        end if; 
    end process;


    width_val10_read_assign_proc : process(ap_CS_fsm_state1, ap_block_state1)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_const_boolean_0 = ap_block_state1))) then 
            width_val10_read <= ap_const_logic_1;
        else 
            width_val10_read <= ap_const_logic_0;
        end if; 
    end process;

    xor_ln1053_fu_332_p2 <= (phi_ln1036_loc_fu_128 xor ap_const_lv1_1);
end behav;
