-- ==============================================================
-- Generated by Vitis HLS v2024.2
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2024 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity system_v_tpg_0_0_tpgForeground_Pipeline_VITIS_LOOP_774_2 is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    bckgndYUV_dout : IN STD_LOGIC_VECTOR (29 downto 0);
    bckgndYUV_empty_n : IN STD_LOGIC;
    bckgndYUV_read : OUT STD_LOGIC;
    bckgndYUV_num_data_valid : IN STD_LOGIC_VECTOR (4 downto 0);
    bckgndYUV_fifo_cap : IN STD_LOGIC_VECTOR (4 downto 0);
    ovrlayYUV_din : OUT STD_LOGIC_VECTOR (29 downto 0);
    ovrlayYUV_full_n : IN STD_LOGIC;
    ovrlayYUV_write : OUT STD_LOGIC;
    ovrlayYUV_num_data_valid : IN STD_LOGIC_VECTOR (31 downto 0);
    ovrlayYUV_fifo_cap : IN STD_LOGIC_VECTOR (31 downto 0);
    loopWidth : IN STD_LOGIC_VECTOR (15 downto 0);
    boxColorB : IN STD_LOGIC_VECTOR (9 downto 0);
    conv2_i_i_i129 : IN STD_LOGIC_VECTOR (9 downto 0);
    boxColorR : IN STD_LOGIC_VECTOR (9 downto 0);
    patternId_val_load : IN STD_LOGIC_VECTOR (7 downto 0);
    boxSize : IN STD_LOGIC_VECTOR (15 downto 0);
    y : IN STD_LOGIC_VECTOR (15 downto 0);
    vMax : IN STD_LOGIC_VECTOR (15 downto 0);
    motionSpeed : IN STD_LOGIC_VECTOR (7 downto 0);
    hMax : IN STD_LOGIC_VECTOR (15 downto 0);
    zext_ln1889 : IN STD_LOGIC_VECTOR (8 downto 0);
    icmp : IN STD_LOGIC_VECTOR (0 downto 0);
    boxColorG : IN STD_LOGIC_VECTOR (9 downto 0);
    crossHairX : IN STD_LOGIC_VECTOR (15 downto 0);
    cmp2_i : IN STD_LOGIC_VECTOR (0 downto 0);
    color : IN STD_LOGIC_VECTOR (7 downto 0);
    maskId : IN STD_LOGIC_VECTOR (7 downto 0);
    cmp31_i : IN STD_LOGIC_VECTOR (0 downto 0);
    empty_46 : IN STD_LOGIC_VECTOR (0 downto 0);
    empty_47 : IN STD_LOGIC_VECTOR (0 downto 0);
    empty : IN STD_LOGIC_VECTOR (0 downto 0);
    boxHCoord_loc_1_out_i : IN STD_LOGIC_VECTOR (15 downto 0);
    boxHCoord_loc_1_out_o : OUT STD_LOGIC_VECTOR (15 downto 0);
    boxHCoord_loc_1_out_o_ap_vld : OUT STD_LOGIC;
    boxVCoord_loc_1_out_i : IN STD_LOGIC_VECTOR (15 downto 0);
    boxVCoord_loc_1_out_o : OUT STD_LOGIC_VECTOR (15 downto 0);
    boxVCoord_loc_1_out_o_ap_vld : OUT STD_LOGIC;
    boxVCoord : OUT STD_LOGIC_VECTOR (15 downto 0);
    boxVCoord_ap_vld : OUT STD_LOGIC;
    boxHCoord : OUT STD_LOGIC_VECTOR (15 downto 0);
    boxHCoord_ap_vld : OUT STD_LOGIC );
end;


architecture behav of system_v_tpg_0_0_tpgForeground_Pipeline_VITIS_LOOP_774_2 is 
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_pp0_stage0 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_lv1_0 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    constant ap_const_lv1_1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_boolean_0 : BOOLEAN := false;
    constant ap_const_lv8_2 : STD_LOGIC_VECTOR (7 downto 0) := "00000010";
    constant ap_const_lv8_0 : STD_LOGIC_VECTOR (7 downto 0) := "00000000";
    constant ap_const_lv8_1 : STD_LOGIC_VECTOR (7 downto 0) := "00000001";
    constant ap_const_lv2_1 : STD_LOGIC_VECTOR (1 downto 0) := "01";
    constant ap_const_lv10_3C0 : STD_LOGIC_VECTOR (9 downto 0) := "1111000000";
    constant ap_const_lv16_0 : STD_LOGIC_VECTOR (15 downto 0) := "0000000000000000";
    constant ap_const_lv16_1 : STD_LOGIC_VECTOR (15 downto 0) := "0000000000000001";
    constant ap_const_lv2_2 : STD_LOGIC_VECTOR (1 downto 0) := "10";
    constant ap_const_lv32_A : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001010";
    constant ap_const_lv32_13 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000010011";
    constant ap_const_lv32_14 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000010100";
    constant ap_const_lv32_1D : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000011101";
    constant ap_const_lv10_0 : STD_LOGIC_VECTOR (9 downto 0) := "0000000000";

attribute shreg_extract : string;
    signal ap_CS_fsm : STD_LOGIC_VECTOR (0 downto 0) := "1";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_pp0_stage0 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_pp0_stage0 : signal is "none";
    signal ap_enable_reg_pp0_iter0 : STD_LOGIC;
    signal ap_enable_reg_pp0_iter1 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter2 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter3 : STD_LOGIC := '0';
    signal ap_idle_pp0 : STD_LOGIC;
    signal icmp_ln774_reg_846 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln774_reg_846_pp0_iter1_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_block_state3_pp0_stage0_iter2 : BOOLEAN;
    signal ap_block_state4_pp0_stage0_iter3 : BOOLEAN;
    signal ap_block_pp0_stage0_subdone : BOOLEAN;
    signal icmp_ln774_fu_397_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_condition_exit_pp0_iter0_stage0 : STD_LOGIC;
    signal ap_loop_exit_ready : STD_LOGIC;
    signal ap_ready_int : STD_LOGIC;
    signal vDir : STD_LOGIC_VECTOR (0 downto 0) := "0";
    signal hDir : STD_LOGIC_VECTOR (0 downto 0) := "0";
    signal whiYuv_2_address0 : STD_LOGIC_VECTOR (1 downto 0);
    signal whiYuv_2_q0 : STD_LOGIC_VECTOR (9 downto 0);
    signal ovrlayYUV_blk_n : STD_LOGIC;
    signal ap_block_pp0_stage0 : BOOLEAN;
    signal bckgndYUV_blk_n : STD_LOGIC;
    signal color_read_read_fu_168_p2 : STD_LOGIC_VECTOR (7 downto 0);
    signal color_read_reg_747 : STD_LOGIC_VECTOR (7 downto 0);
    signal ap_block_pp0_stage0_11001 : BOOLEAN;
    signal patternId_val_load_read_read_fu_234_p2 : STD_LOGIC_VECTOR (7 downto 0);
    signal patternId_val_load_read_reg_783 : STD_LOGIC_VECTOR (7 downto 0);
    signal zext_ln1889_cast_fu_357_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal zext_ln1889_cast_reg_804 : STD_LOGIC_VECTOR (15 downto 0);
    signal motionSpeed_cast_fu_361_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal motionSpeed_cast_reg_810 : STD_LOGIC_VECTOR (15 downto 0);
    signal tobool_fu_365_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tobool_reg_818 : STD_LOGIC_VECTOR (0 downto 0);
    signal and26_i_fu_371_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal and26_i_reg_825 : STD_LOGIC_VECTOR (0 downto 0);
    signal and10_i_fu_377_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal and10_i_reg_830 : STD_LOGIC_VECTOR (0 downto 0);
    signal and4_i_fu_383_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal and4_i_reg_835 : STD_LOGIC_VECTOR (0 downto 0);
    signal x_1_reg_840 : STD_LOGIC_VECTOR (15 downto 0);
    signal x_1_reg_840_pp0_iter1_reg : STD_LOGIC_VECTOR (15 downto 0);
    signal icmp_ln774_reg_846_pp0_iter2_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal trunc_ln774_fu_409_p1 : STD_LOGIC_VECTOR (0 downto 0);
    signal trunc_ln774_reg_850 : STD_LOGIC_VECTOR (0 downto 0);
    signal trunc_ln774_reg_850_pp0_iter1_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln1884_fu_419_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln1884_reg_855 : STD_LOGIC_VECTOR (0 downto 0);
    signal or_ln1963_fu_431_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal or_ln1963_reg_859 : STD_LOGIC_VECTOR (0 downto 0);
    signal select_ln1975_fu_437_p3 : STD_LOGIC_VECTOR (1 downto 0);
    signal select_ln1975_reg_863 : STD_LOGIC_VECTOR (1 downto 0);
    signal pixIn_fu_565_p1 : STD_LOGIC_VECTOR (9 downto 0);
    signal pixIn_reg_891 : STD_LOGIC_VECTOR (9 downto 0);
    signal pixIn_5_reg_898 : STD_LOGIC_VECTOR (9 downto 0);
    signal pixIn_6_reg_905 : STD_LOGIC_VECTOR (9 downto 0);
    signal and_ln1942_fu_671_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln1942_reg_912 : STD_LOGIC_VECTOR (0 downto 0);
    signal pixOut_5_fu_681_p3 : STD_LOGIC_VECTOR (9 downto 0);
    signal pixOut_5_reg_916 : STD_LOGIC_VECTOR (9 downto 0);
    signal ap_phi_mux_phi_ln1975_phi_fu_294_p4 : STD_LOGIC_VECTOR (1 downto 0);
    signal ap_phi_reg_pp0_iter1_phi_ln1975_reg_290 : STD_LOGIC_VECTOR (1 downto 0);
    signal ap_phi_reg_pp0_iter0_phi_ln1975_reg_290 : STD_LOGIC_VECTOR (1 downto 0);
    signal ap_phi_mux_pix_4_phi_fu_304_p12 : STD_LOGIC_VECTOR (9 downto 0);
    signal ap_phi_reg_pp0_iter0_pix_4_reg_301 : STD_LOGIC_VECTOR (9 downto 0);
    signal ap_phi_reg_pp0_iter1_pix_4_reg_301 : STD_LOGIC_VECTOR (9 downto 0);
    signal ap_phi_reg_pp0_iter2_pix_4_reg_301 : STD_LOGIC_VECTOR (9 downto 0);
    signal ap_phi_reg_pp0_iter3_pix_4_reg_301 : STD_LOGIC_VECTOR (9 downto 0);
    signal ap_predicate_pred288_state3 : BOOLEAN;
    signal ap_predicate_pred294_state3 : BOOLEAN;
    signal ap_predicate_pred260_state3 : BOOLEAN;
    signal ap_phi_mux_pix_3_phi_fu_322_p12 : STD_LOGIC_VECTOR (9 downto 0);
    signal ap_phi_reg_pp0_iter0_pix_3_reg_318 : STD_LOGIC_VECTOR (9 downto 0);
    signal ap_phi_reg_pp0_iter1_pix_3_reg_318 : STD_LOGIC_VECTOR (9 downto 0);
    signal ap_phi_reg_pp0_iter2_pix_3_reg_318 : STD_LOGIC_VECTOR (9 downto 0);
    signal ap_phi_reg_pp0_iter3_pix_3_reg_318 : STD_LOGIC_VECTOR (9 downto 0);
    signal ap_phi_mux_pix_phi_fu_341_p12 : STD_LOGIC_VECTOR (9 downto 0);
    signal ap_phi_reg_pp0_iter0_pix_reg_337 : STD_LOGIC_VECTOR (9 downto 0);
    signal ap_phi_reg_pp0_iter1_pix_reg_337 : STD_LOGIC_VECTOR (9 downto 0);
    signal ap_phi_reg_pp0_iter2_pix_reg_337 : STD_LOGIC_VECTOR (9 downto 0);
    signal ap_phi_reg_pp0_iter3_pix_reg_337 : STD_LOGIC_VECTOR (9 downto 0);
    signal zext_ln1975_fu_560_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal sub_ln1914_fu_462_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal add_ln1912_fu_467_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal hDir_load_load_fu_454_p1 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln1889_fu_472_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln1894_fu_489_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_block_pp0_stage0_grp0 : BOOLEAN;
    signal ap_predicate_pred335_state3 : BOOLEAN;
    signal ap_predicate_pred375_state3 : BOOLEAN;
    signal sub_ln1918_fu_516_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal add_ln1916_fu_521_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal vDir_load_load_fu_458_p1 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln1906_fu_537_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln1901_fu_526_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_block_pp0_stage0_11001_grp0 : BOOLEAN;
    signal ap_block_pp0_stage0_subdone_grp0_done_reg : BOOLEAN := false;
    signal ap_block_pp0_stage0_subdone_grp0 : BOOLEAN;
    signal x_fu_134 : STD_LOGIC_VECTOR (15 downto 0) := "0000000000000000";
    signal x_2_fu_403_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal ap_loop_init : STD_LOGIC;
    signal ap_sig_allocacmp_x_1 : STD_LOGIC_VECTOR (15 downto 0);
    signal ap_block_pp0_stage0_01001 : BOOLEAN;
    signal whiYuv_2_ce0_local : STD_LOGIC;
    signal or_ln1884_fu_413_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal icmp_ln1963_fu_425_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln1932_fu_627_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal boxBottom_fu_622_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal icmp_ln1937_fu_643_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal boxRight_fu_617_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal icmp_ln1937_1_fu_654_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal xor_ln1937_fu_648_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal xor_ln1932_fu_632_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln1932_1_fu_638_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln1942_1_fu_665_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln1942_2_fu_659_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln1947_fu_677_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal pixOut_11_fu_701_p3 : STD_LOGIC_VECTOR (9 downto 0);
    signal pixOut_10_fu_694_p3 : STD_LOGIC_VECTOR (9 downto 0);
    signal pixOut_9_fu_687_p3 : STD_LOGIC_VECTOR (9 downto 0);
    signal pixOut_12_fu_708_p3 : STD_LOGIC_VECTOR (9 downto 0);
    signal pixOut_13_fu_715_p3 : STD_LOGIC_VECTOR (9 downto 0);
    signal pixOut_14_fu_722_p3 : STD_LOGIC_VECTOR (9 downto 0);
    signal ap_done_reg : STD_LOGIC := '0';
    signal ap_continue_int : STD_LOGIC;
    signal ap_done_int : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter1_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter2_reg : STD_LOGIC;
    signal ap_NS_fsm : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_enable_pp0 : STD_LOGIC;
    signal ap_start_int : STD_LOGIC;
    signal ap_ready_sig : STD_LOGIC;
    signal ap_done_sig : STD_LOGIC;
    signal ap_condition_276 : BOOLEAN;
    signal ap_condition_269 : BOOLEAN;
    signal ap_condition_300 : BOOLEAN;
    signal ap_condition_393 : BOOLEAN;
    signal ap_condition_400 : BOOLEAN;
    signal ap_condition_329 : BOOLEAN;
    signal ap_condition_691 : BOOLEAN;
    signal ap_ce_reg : STD_LOGIC;

    component system_v_tpg_0_0_tpgForeground_Pipeline_VITIS_LOOP_774_2_whiYuv_2_ROM_AUTO_1R IS
    generic (
        DataWidth : INTEGER;
        AddressRange : INTEGER;
        AddressWidth : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        address0 : IN STD_LOGIC_VECTOR (1 downto 0);
        ce0 : IN STD_LOGIC;
        q0 : OUT STD_LOGIC_VECTOR (9 downto 0) );
    end component;


    component system_v_tpg_0_0_flow_control_loop_pipe_sequential_init IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_start_int : OUT STD_LOGIC;
        ap_loop_init : OUT STD_LOGIC;
        ap_ready_int : IN STD_LOGIC;
        ap_loop_exit_ready : IN STD_LOGIC;
        ap_loop_exit_done : IN STD_LOGIC;
        ap_continue_int : OUT STD_LOGIC;
        ap_done_int : IN STD_LOGIC );
    end component;



begin
    whiYuv_2_U : component system_v_tpg_0_0_tpgForeground_Pipeline_VITIS_LOOP_774_2_whiYuv_2_ROM_AUTO_1R
    generic map (
        DataWidth => 10,
        AddressRange => 3,
        AddressWidth => 2)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        address0 => whiYuv_2_address0,
        ce0 => whiYuv_2_ce0_local,
        q0 => whiYuv_2_q0);

    flow_control_loop_pipe_sequential_init_U : component system_v_tpg_0_0_flow_control_loop_pipe_sequential_init
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => ap_start,
        ap_ready => ap_ready_sig,
        ap_done => ap_done_sig,
        ap_start_int => ap_start_int,
        ap_loop_init => ap_loop_init,
        ap_ready_int => ap_ready_int,
        ap_loop_exit_ready => ap_condition_exit_pp0_iter0_stage0,
        ap_loop_exit_done => ap_done_int,
        ap_continue_int => ap_continue_int,
        ap_done_int => ap_done_int);





    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    ap_block_pp0_stage0_subdone_grp0_done_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_block_pp0_stage0_subdone_grp0_done_reg <= ap_const_boolean_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_block_pp0_stage0_subdone_grp0_done_reg <= ap_const_boolean_0;
                elsif ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone_grp0)) then 
                    ap_block_pp0_stage0_subdone_grp0_done_reg <= ap_const_boolean_1;
                end if; 
            end if;
        end if;
    end process;


    ap_done_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_done_reg <= ap_const_logic_0;
            else
                if ((ap_continue_int = ap_const_logic_1)) then 
                    ap_done_reg <= ap_const_logic_0;
                elsif (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_loop_exit_ready_pp0_iter2_reg = ap_const_logic_1))) then 
                    ap_done_reg <= ap_const_logic_1;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter1_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter1 <= ap_const_logic_0;
            else
                if ((ap_const_logic_1 = ap_condition_exit_pp0_iter0_stage0)) then 
                    ap_enable_reg_pp0_iter1 <= ap_const_logic_0;
                elsif (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                    ap_enable_reg_pp0_iter1 <= ap_start_int;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter2_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter2 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter3_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter3 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter3 <= ap_enable_reg_pp0_iter2;
                end if; 
            end if;
        end if;
    end process;


    ap_phi_reg_pp0_iter1_phi_ln1975_reg_290_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_boolean_1 = ap_condition_269)) then
                if ((ap_const_boolean_1 = ap_condition_276)) then 
                    ap_phi_reg_pp0_iter1_phi_ln1975_reg_290 <= ap_const_lv2_1;
                elsif ((ap_const_boolean_1 = ap_const_boolean_1)) then 
                    ap_phi_reg_pp0_iter1_phi_ln1975_reg_290 <= ap_phi_reg_pp0_iter0_phi_ln1975_reg_290;
                end if;
            end if; 
        end if;
    end process;

    ap_phi_reg_pp0_iter1_pix_3_reg_318_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_boolean_1 = ap_condition_269)) then
                if ((ap_const_boolean_1 = ap_condition_300)) then 
                    ap_phi_reg_pp0_iter1_pix_3_reg_318 <= ap_const_lv10_3C0;
                elsif ((ap_const_boolean_1 = ap_const_boolean_1)) then 
                    ap_phi_reg_pp0_iter1_pix_3_reg_318 <= ap_phi_reg_pp0_iter0_pix_3_reg_318;
                end if;
            end if; 
        end if;
    end process;

    ap_phi_reg_pp0_iter1_pix_4_reg_301_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_boolean_1 = ap_condition_269)) then
                if ((ap_const_boolean_1 = ap_condition_300)) then 
                    ap_phi_reg_pp0_iter1_pix_4_reg_301 <= conv2_i_i_i129;
                elsif ((ap_const_boolean_1 = ap_const_boolean_1)) then 
                    ap_phi_reg_pp0_iter1_pix_4_reg_301 <= ap_phi_reg_pp0_iter0_pix_4_reg_301;
                end if;
            end if; 
        end if;
    end process;

    ap_phi_reg_pp0_iter1_pix_reg_337_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_boolean_1 = ap_condition_269)) then
                if ((ap_const_boolean_1 = ap_condition_300)) then 
                    ap_phi_reg_pp0_iter1_pix_reg_337 <= ap_const_lv10_3C0;
                elsif ((ap_const_boolean_1 = ap_const_boolean_1)) then 
                    ap_phi_reg_pp0_iter1_pix_reg_337 <= ap_phi_reg_pp0_iter0_pix_reg_337;
                end if;
            end if; 
        end if;
    end process;

    ap_phi_reg_pp0_iter3_pix_3_reg_318_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_predicate_pred260_state3 = ap_const_boolean_1) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1))) then 
                ap_phi_reg_pp0_iter3_pix_3_reg_318 <= whiYuv_2_q0;
            elsif ((((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_predicate_pred294_state3 = ap_const_boolean_1) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1)) or ((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_predicate_pred288_state3 = ap_const_boolean_1) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1)))) then 
                ap_phi_reg_pp0_iter3_pix_3_reg_318 <= bckgndYUV_dout(19 downto 10);
            elsif (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1))) then 
                ap_phi_reg_pp0_iter3_pix_3_reg_318 <= ap_phi_reg_pp0_iter2_pix_3_reg_318;
            end if; 
        end if;
    end process;

    ap_phi_reg_pp0_iter3_pix_4_reg_301_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_predicate_pred260_state3 = ap_const_boolean_1) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1))) then 
                ap_phi_reg_pp0_iter3_pix_4_reg_301 <= conv2_i_i_i129;
            elsif ((((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_predicate_pred294_state3 = ap_const_boolean_1) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1)) or ((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_predicate_pred288_state3 = ap_const_boolean_1) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1)))) then 
                ap_phi_reg_pp0_iter3_pix_4_reg_301 <= bckgndYUV_dout(29 downto 20);
            elsif (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1))) then 
                ap_phi_reg_pp0_iter3_pix_4_reg_301 <= ap_phi_reg_pp0_iter2_pix_4_reg_301;
            end if; 
        end if;
    end process;

    ap_phi_reg_pp0_iter3_pix_reg_337_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_predicate_pred260_state3 = ap_const_boolean_1) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1))) then 
                ap_phi_reg_pp0_iter3_pix_reg_337 <= ap_const_lv10_3C0;
            elsif ((((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_predicate_pred294_state3 = ap_const_boolean_1) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1)) or ((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_predicate_pred288_state3 = ap_const_boolean_1) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1)))) then 
                ap_phi_reg_pp0_iter3_pix_reg_337 <= pixIn_fu_565_p1;
            elsif (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1))) then 
                ap_phi_reg_pp0_iter3_pix_reg_337 <= ap_phi_reg_pp0_iter2_pix_reg_337;
            end if; 
        end if;
    end process;

    hDir_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_boolean_1 = ap_condition_691)) then
                if (((icmp_ln1894_fu_489_p2 = ap_const_lv1_1) and (hDir_load_load_fu_454_p1 = ap_const_lv1_1))) then 
                    hDir <= ap_const_lv1_0;
                elsif (((icmp_ln1889_fu_472_p2 = ap_const_lv1_1) and (hDir_load_load_fu_454_p1 = ap_const_lv1_0))) then 
                    hDir <= ap_const_lv1_1;
                end if;
            end if; 
        end if;
    end process;

    vDir_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_boolean_1 = ap_condition_691)) then
                if (((icmp_ln1906_fu_537_p2 = ap_const_lv1_1) and (vDir_load_load_fu_458_p1 = ap_const_lv1_1))) then 
                    vDir <= ap_const_lv1_0;
                elsif (((icmp_ln1901_fu_526_p2 = ap_const_lv1_1) and (vDir_load_load_fu_458_p1 = ap_const_lv1_0))) then 
                    vDir <= ap_const_lv1_1;
                end if;
            end if; 
        end if;
    end process;

    x_fu_134_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                if (((icmp_ln774_fu_397_p2 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1))) then 
                    x_fu_134 <= x_2_fu_403_p2;
                elsif ((ap_loop_init = ap_const_logic_1)) then 
                    x_fu_134 <= ap_const_lv16_0;
                end if;
            end if; 
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                and10_i_reg_830 <= and10_i_fu_377_p2;
                and26_i_reg_825 <= and26_i_fu_371_p2;
                and4_i_reg_835 <= and4_i_fu_383_p2;
                ap_loop_exit_ready_pp0_iter1_reg <= ap_loop_exit_ready;
                ap_loop_exit_ready_pp0_iter2_reg <= ap_loop_exit_ready_pp0_iter1_reg;
                    ap_predicate_pred260_state3 <= (not((color_read_reg_747 = ap_const_lv8_0)) and (icmp_ln774_reg_846 = ap_const_lv1_0) and (or_ln1963_reg_859 = ap_const_lv1_1) and (patternId_val_load_read_reg_783 = ap_const_lv8_2));
                    ap_predicate_pred288_state3 <= (not((patternId_val_load_read_reg_783 = ap_const_lv8_1)) and not((patternId_val_load_read_reg_783 = ap_const_lv8_2)) and (icmp_ln774_reg_846 = ap_const_lv1_0));
                    ap_predicate_pred294_state3 <= ((icmp_ln774_reg_846 = ap_const_lv1_0) and (or_ln1963_reg_859 = ap_const_lv1_0) and (patternId_val_load_read_reg_783 = ap_const_lv8_2));
                    ap_predicate_pred335_state3 <= ((icmp_ln1884_reg_855 = ap_const_lv1_1) and (patternId_val_load_read_reg_783 = ap_const_lv8_1));
                    ap_predicate_pred375_state3 <= ((icmp_ln774_reg_846 = ap_const_lv1_0) and (patternId_val_load_read_reg_783 = ap_const_lv8_1));
                icmp_ln1884_reg_855 <= icmp_ln1884_fu_419_p2;
                icmp_ln774_reg_846 <= icmp_ln774_fu_397_p2;
                icmp_ln774_reg_846_pp0_iter1_reg <= icmp_ln774_reg_846;
                    motionSpeed_cast_reg_810(7 downto 0) <= motionSpeed_cast_fu_361_p1(7 downto 0);
                or_ln1963_reg_859 <= or_ln1963_fu_431_p2;
                select_ln1975_reg_863 <= select_ln1975_fu_437_p3;
                tobool_reg_818 <= tobool_fu_365_p2;
                trunc_ln774_reg_850 <= trunc_ln774_fu_409_p1;
                trunc_ln774_reg_850_pp0_iter1_reg <= trunc_ln774_reg_850;
                x_1_reg_840 <= ap_sig_allocacmp_x_1;
                x_1_reg_840_pp0_iter1_reg <= x_1_reg_840;
                    zext_ln1889_cast_reg_804(8 downto 0) <= zext_ln1889_cast_fu_357_p1(8 downto 0);
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_boolean_0 = ap_block_pp0_stage0_11001)) then
                and_ln1942_reg_912 <= and_ln1942_fu_671_p2;
                icmp_ln774_reg_846_pp0_iter2_reg <= icmp_ln774_reg_846_pp0_iter1_reg;
                pixIn_5_reg_898 <= bckgndYUV_dout(19 downto 10);
                pixIn_6_reg_905 <= bckgndYUV_dout(29 downto 20);
                pixIn_reg_891 <= pixIn_fu_565_p1;
                pixOut_5_reg_916 <= pixOut_5_fu_681_p3;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                ap_phi_reg_pp0_iter2_pix_3_reg_318 <= ap_phi_reg_pp0_iter1_pix_3_reg_318;
                ap_phi_reg_pp0_iter2_pix_4_reg_301 <= ap_phi_reg_pp0_iter1_pix_4_reg_301;
                ap_phi_reg_pp0_iter2_pix_reg_337 <= ap_phi_reg_pp0_iter1_pix_reg_337;
            end if;
        end if;
    end process;
    zext_ln1889_cast_reg_804(15 downto 9) <= "0000000";
    motionSpeed_cast_reg_810(15 downto 8) <= "00000000";

    ap_NS_fsm_assign_proc : process (ap_CS_fsm)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_pp0_stage0 => 
                ap_NS_fsm <= ap_ST_fsm_pp0_stage0;
            when others =>  
                ap_NS_fsm <= "X";
        end case;
    end process;
    add_ln1912_fu_467_p2 <= std_logic_vector(unsigned(boxHCoord_loc_1_out_i) + unsigned(motionSpeed_cast_reg_810));
    add_ln1916_fu_521_p2 <= std_logic_vector(unsigned(boxVCoord_loc_1_out_i) + unsigned(motionSpeed_cast_reg_810));
    and10_i_fu_377_p2 <= (empty_47 and cmp31_i);
    and26_i_fu_371_p2 <= (empty_46 and cmp31_i);
    and4_i_fu_383_p2 <= (empty and cmp31_i);
    and_ln1942_1_fu_665_p2 <= (xor_ln1932_fu_632_p2 and icmp_ln1932_1_fu_638_p2);
    and_ln1942_2_fu_659_p2 <= (xor_ln1937_fu_648_p2 and icmp_ln1937_1_fu_654_p2);
    and_ln1942_fu_671_p2 <= (and_ln1942_2_fu_659_p2 and and_ln1942_1_fu_665_p2);
    and_ln1947_fu_677_p2 <= (trunc_ln774_reg_850_pp0_iter1_reg and icmp);
    ap_CS_fsm_pp0_stage0 <= ap_CS_fsm(0);
        ap_block_pp0_stage0 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_block_pp0_stage0_01001_assign_proc : process(ap_enable_reg_pp0_iter2, ap_enable_reg_pp0_iter3, ap_block_state3_pp0_stage0_iter2, ap_block_state4_pp0_stage0_iter3)
    begin
                ap_block_pp0_stage0_01001 <= (((ap_enable_reg_pp0_iter3 = ap_const_logic_1) and (ap_const_boolean_1 = ap_block_state4_pp0_stage0_iter3)) or ((ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (ap_const_boolean_1 = ap_block_state3_pp0_stage0_iter2)));
    end process;


    ap_block_pp0_stage0_11001_assign_proc : process(ap_enable_reg_pp0_iter2, ap_enable_reg_pp0_iter3, ap_block_state3_pp0_stage0_iter2, ap_block_state4_pp0_stage0_iter3)
    begin
                ap_block_pp0_stage0_11001 <= (((ap_enable_reg_pp0_iter3 = ap_const_logic_1) and (ap_const_boolean_1 = ap_block_state4_pp0_stage0_iter3)) or ((ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (ap_const_boolean_1 = ap_block_state3_pp0_stage0_iter2)));
    end process;

        ap_block_pp0_stage0_11001_grp0 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage0_grp0 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_block_pp0_stage0_subdone_assign_proc : process(ap_enable_reg_pp0_iter2, ap_enable_reg_pp0_iter3, ap_block_state3_pp0_stage0_iter2, ap_block_state4_pp0_stage0_iter3)
    begin
                ap_block_pp0_stage0_subdone <= (((ap_enable_reg_pp0_iter3 = ap_const_logic_1) and (ap_const_boolean_1 = ap_block_state4_pp0_stage0_iter3)) or ((ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (ap_const_boolean_1 = ap_block_state3_pp0_stage0_iter2)));
    end process;

        ap_block_pp0_stage0_subdone_grp0 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_block_state3_pp0_stage0_iter2_assign_proc : process(bckgndYUV_empty_n, icmp_ln774_reg_846_pp0_iter1_reg)
    begin
                ap_block_state3_pp0_stage0_iter2 <= ((icmp_ln774_reg_846_pp0_iter1_reg = ap_const_lv1_0) and (bckgndYUV_empty_n = ap_const_logic_0));
    end process;


    ap_block_state4_pp0_stage0_iter3_assign_proc : process(ovrlayYUV_full_n)
    begin
                ap_block_state4_pp0_stage0_iter3 <= (ovrlayYUV_full_n = ap_const_logic_0);
    end process;


    ap_condition_269_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_11001)
    begin
                ap_condition_269 <= ((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0));
    end process;


    ap_condition_276_assign_proc : process(icmp_ln774_fu_397_p2, color_read_read_fu_168_p2, patternId_val_load_read_read_fu_234_p2, or_ln1963_fu_431_p2)
    begin
                ap_condition_276 <= ((icmp_ln774_fu_397_p2 = ap_const_lv1_0) and (or_ln1963_fu_431_p2 = ap_const_lv1_1) and (patternId_val_load_read_read_fu_234_p2 = ap_const_lv8_2) and (color_read_read_fu_168_p2 = ap_const_lv8_1));
    end process;


    ap_condition_300_assign_proc : process(icmp_ln774_fu_397_p2, color_read_read_fu_168_p2, patternId_val_load_read_read_fu_234_p2, or_ln1963_fu_431_p2)
    begin
                ap_condition_300 <= ((icmp_ln774_fu_397_p2 = ap_const_lv1_0) and (or_ln1963_fu_431_p2 = ap_const_lv1_1) and (patternId_val_load_read_read_fu_234_p2 = ap_const_lv8_2) and (color_read_read_fu_168_p2 = ap_const_lv8_0));
    end process;


    ap_condition_329_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_block_pp0_stage0)
    begin
                ap_condition_329 <= ((ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0));
    end process;


    ap_condition_393_assign_proc : process(patternId_val_load_read_reg_783, icmp_ln1884_reg_855, vDir_load_load_fu_458_p1, icmp_ln1906_fu_537_p2, icmp_ln1901_fu_526_p2)
    begin
                ap_condition_393 <= (((icmp_ln1901_fu_526_p2 = ap_const_lv1_1) and (vDir_load_load_fu_458_p1 = ap_const_lv1_0) and (icmp_ln1884_reg_855 = ap_const_lv1_1) and (patternId_val_load_read_reg_783 = ap_const_lv8_1)) or ((icmp_ln1906_fu_537_p2 = ap_const_lv1_0) and (vDir_load_load_fu_458_p1 = ap_const_lv1_1) and (icmp_ln1884_reg_855 = ap_const_lv1_1) and (patternId_val_load_read_reg_783 = ap_const_lv8_1)));
    end process;


    ap_condition_400_assign_proc : process(patternId_val_load_read_reg_783, icmp_ln1884_reg_855, vDir_load_load_fu_458_p1, icmp_ln1906_fu_537_p2, icmp_ln1901_fu_526_p2)
    begin
                ap_condition_400 <= (((icmp_ln1901_fu_526_p2 = ap_const_lv1_0) and (vDir_load_load_fu_458_p1 = ap_const_lv1_0) and (icmp_ln1884_reg_855 = ap_const_lv1_1) and (patternId_val_load_read_reg_783 = ap_const_lv8_1)) or ((icmp_ln1906_fu_537_p2 = ap_const_lv1_1) and (vDir_load_load_fu_458_p1 = ap_const_lv1_1) and (icmp_ln1884_reg_855 = ap_const_lv1_1) and (patternId_val_load_read_reg_783 = ap_const_lv8_1)));
    end process;


    ap_condition_691_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_block_pp0_stage0_11001, patternId_val_load_read_reg_783, icmp_ln1884_reg_855)
    begin
                ap_condition_691 <= ((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (icmp_ln1884_reg_855 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (patternId_val_load_read_reg_783 = ap_const_lv8_1));
    end process;


    ap_condition_exit_pp0_iter0_stage0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_subdone, icmp_ln774_fu_397_p2)
    begin
        if (((icmp_ln774_fu_397_p2 = ap_const_lv1_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_condition_exit_pp0_iter0_stage0 <= ap_const_logic_1;
        else 
            ap_condition_exit_pp0_iter0_stage0 <= ap_const_logic_0;
        end if; 
    end process;

    ap_done <= ap_done_sig;

    ap_done_int_assign_proc : process(ap_block_pp0_stage0_subdone, ap_done_reg, ap_loop_exit_ready_pp0_iter2_reg)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_loop_exit_ready_pp0_iter2_reg = ap_const_logic_1))) then 
            ap_done_int <= ap_const_logic_1;
        else 
            ap_done_int <= ap_done_reg;
        end if; 
    end process;

    ap_enable_pp0 <= (ap_idle_pp0 xor ap_const_logic_1);
    ap_enable_reg_pp0_iter0 <= ap_start_int;

    ap_idle_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_idle_pp0, ap_start_int)
    begin
        if (((ap_start_int = ap_const_logic_0) and (ap_idle_pp0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;


    ap_idle_pp0_assign_proc : process(ap_enable_reg_pp0_iter0, ap_enable_reg_pp0_iter1, ap_enable_reg_pp0_iter2, ap_enable_reg_pp0_iter3)
    begin
        if (((ap_enable_reg_pp0_iter3 = ap_const_logic_0) and (ap_enable_reg_pp0_iter2 = ap_const_logic_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_0))) then 
            ap_idle_pp0 <= ap_const_logic_1;
        else 
            ap_idle_pp0 <= ap_const_logic_0;
        end if; 
    end process;

    ap_loop_exit_ready <= ap_condition_exit_pp0_iter0_stage0;

    ap_phi_mux_phi_ln1975_phi_fu_294_p4_assign_proc : process(icmp_ln774_reg_846, color_read_reg_747, patternId_val_load_read_reg_783, or_ln1963_reg_859, select_ln1975_reg_863, ap_phi_reg_pp0_iter1_phi_ln1975_reg_290)
    begin
        if ((not((color_read_reg_747 = ap_const_lv8_1)) and not((color_read_reg_747 = ap_const_lv8_0)) and (icmp_ln774_reg_846 = ap_const_lv1_0) and (or_ln1963_reg_859 = ap_const_lv1_1) and (patternId_val_load_read_reg_783 = ap_const_lv8_2))) then 
            ap_phi_mux_phi_ln1975_phi_fu_294_p4 <= select_ln1975_reg_863;
        else 
            ap_phi_mux_phi_ln1975_phi_fu_294_p4 <= ap_phi_reg_pp0_iter1_phi_ln1975_reg_290;
        end if; 
    end process;


    ap_phi_mux_pix_3_phi_fu_322_p12_assign_proc : process(patternId_val_load_read_reg_783, icmp_ln774_reg_846_pp0_iter2_reg, pixIn_5_reg_898, and_ln1942_reg_912, pixOut_5_reg_916, ap_phi_reg_pp0_iter3_pix_3_reg_318)
    begin
        if (((icmp_ln774_reg_846_pp0_iter2_reg = ap_const_lv1_0) and (patternId_val_load_read_reg_783 = ap_const_lv8_1))) then
            if ((ap_const_lv1_0 = and_ln1942_reg_912)) then 
                ap_phi_mux_pix_3_phi_fu_322_p12 <= pixIn_5_reg_898;
            elsif ((ap_const_lv1_1 = and_ln1942_reg_912)) then 
                ap_phi_mux_pix_3_phi_fu_322_p12 <= pixOut_5_reg_916;
            else 
                ap_phi_mux_pix_3_phi_fu_322_p12 <= ap_phi_reg_pp0_iter3_pix_3_reg_318;
            end if;
        else 
            ap_phi_mux_pix_3_phi_fu_322_p12 <= ap_phi_reg_pp0_iter3_pix_3_reg_318;
        end if; 
    end process;


    ap_phi_mux_pix_4_phi_fu_304_p12_assign_proc : process(boxColorB, patternId_val_load_read_reg_783, icmp_ln774_reg_846_pp0_iter2_reg, pixIn_6_reg_905, and_ln1942_reg_912, ap_phi_reg_pp0_iter3_pix_4_reg_301)
    begin
        if (((icmp_ln774_reg_846_pp0_iter2_reg = ap_const_lv1_0) and (patternId_val_load_read_reg_783 = ap_const_lv8_1))) then
            if ((ap_const_lv1_0 = and_ln1942_reg_912)) then 
                ap_phi_mux_pix_4_phi_fu_304_p12 <= pixIn_6_reg_905;
            elsif ((ap_const_lv1_1 = and_ln1942_reg_912)) then 
                ap_phi_mux_pix_4_phi_fu_304_p12 <= boxColorB;
            else 
                ap_phi_mux_pix_4_phi_fu_304_p12 <= ap_phi_reg_pp0_iter3_pix_4_reg_301;
            end if;
        else 
            ap_phi_mux_pix_4_phi_fu_304_p12 <= ap_phi_reg_pp0_iter3_pix_4_reg_301;
        end if; 
    end process;


    ap_phi_mux_pix_phi_fu_341_p12_assign_proc : process(boxColorR, patternId_val_load_read_reg_783, icmp_ln774_reg_846_pp0_iter2_reg, pixIn_reg_891, and_ln1942_reg_912, ap_phi_reg_pp0_iter3_pix_reg_337)
    begin
        if (((icmp_ln774_reg_846_pp0_iter2_reg = ap_const_lv1_0) and (patternId_val_load_read_reg_783 = ap_const_lv8_1))) then
            if ((ap_const_lv1_0 = and_ln1942_reg_912)) then 
                ap_phi_mux_pix_phi_fu_341_p12 <= pixIn_reg_891;
            elsif ((ap_const_lv1_1 = and_ln1942_reg_912)) then 
                ap_phi_mux_pix_phi_fu_341_p12 <= boxColorR;
            else 
                ap_phi_mux_pix_phi_fu_341_p12 <= ap_phi_reg_pp0_iter3_pix_reg_337;
            end if;
        else 
            ap_phi_mux_pix_phi_fu_341_p12 <= ap_phi_reg_pp0_iter3_pix_reg_337;
        end if; 
    end process;

    ap_phi_reg_pp0_iter0_phi_ln1975_reg_290 <= "XX";
    ap_phi_reg_pp0_iter0_pix_3_reg_318 <= "XXXXXXXXXX";
    ap_phi_reg_pp0_iter0_pix_4_reg_301 <= "XXXXXXXXXX";
    ap_phi_reg_pp0_iter0_pix_reg_337 <= "XXXXXXXXXX";
    ap_ready <= ap_ready_sig;

    ap_ready_int_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_subdone)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_ready_int <= ap_const_logic_1;
        else 
            ap_ready_int <= ap_const_logic_0;
        end if; 
    end process;


    ap_sig_allocacmp_x_1_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0, x_fu_134, ap_loop_init)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_loop_init = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_sig_allocacmp_x_1 <= ap_const_lv16_0;
        else 
            ap_sig_allocacmp_x_1 <= x_fu_134;
        end if; 
    end process;


    bckgndYUV_blk_n_assign_proc : process(ap_enable_reg_pp0_iter2, bckgndYUV_empty_n, icmp_ln774_reg_846_pp0_iter1_reg, ap_block_pp0_stage0)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0) and (icmp_ln774_reg_846_pp0_iter1_reg = ap_const_lv1_0) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1))) then 
            bckgndYUV_blk_n <= bckgndYUV_empty_n;
        else 
            bckgndYUV_blk_n <= ap_const_logic_1;
        end if; 
    end process;


    bckgndYUV_read_assign_proc : process(ap_enable_reg_pp0_iter2, icmp_ln774_reg_846_pp0_iter1_reg, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (icmp_ln774_reg_846_pp0_iter1_reg = ap_const_lv1_0) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1))) then 
            bckgndYUV_read <= ap_const_logic_1;
        else 
            bckgndYUV_read <= ap_const_logic_0;
        end if; 
    end process;

    boxBottom_fu_622_p2 <= std_logic_vector(unsigned(boxSize) + unsigned(boxVCoord_loc_1_out_i));
    boxHCoord <= boxHCoord_loc_1_out_i;

    boxHCoord_ap_vld_assign_proc : process(ap_enable_reg_pp0_iter2, ap_predicate_pred335_state3, ap_block_pp0_stage0_11001_grp0, ap_block_pp0_stage0_subdone_grp0_done_reg)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone_grp0_done_reg) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp0) and (ap_predicate_pred335_state3 = ap_const_boolean_1) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1))) then 
            boxHCoord_ap_vld <= ap_const_logic_1;
        else 
            boxHCoord_ap_vld <= ap_const_logic_0;
        end if; 
    end process;


    boxHCoord_loc_1_out_o_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, boxHCoord_loc_1_out_i, ap_block_pp0_stage0, patternId_val_load_read_reg_783, icmp_ln1884_reg_855, sub_ln1914_fu_462_p2, add_ln1912_fu_467_p2, hDir_load_load_fu_454_p1, icmp_ln1889_fu_472_p2, icmp_ln1894_fu_489_p2)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (((icmp_ln1889_fu_472_p2 = ap_const_lv1_0) and (hDir_load_load_fu_454_p1 = ap_const_lv1_0) and (icmp_ln1884_reg_855 = ap_const_lv1_1) and (patternId_val_load_read_reg_783 = ap_const_lv8_1)) or ((icmp_ln1894_fu_489_p2 = ap_const_lv1_1) and (hDir_load_load_fu_454_p1 = ap_const_lv1_1) and (icmp_ln1884_reg_855 = ap_const_lv1_1) and (patternId_val_load_read_reg_783 = ap_const_lv8_1))))) then 
            boxHCoord_loc_1_out_o <= add_ln1912_fu_467_p2;
        elsif ((((ap_const_boolean_0 = ap_block_pp0_stage0) and (icmp_ln1894_fu_489_p2 = ap_const_lv1_0) and (hDir_load_load_fu_454_p1 = ap_const_lv1_1) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (icmp_ln1884_reg_855 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (patternId_val_load_read_reg_783 = ap_const_lv8_1)) or ((ap_const_boolean_0 = ap_block_pp0_stage0) and (icmp_ln1889_fu_472_p2 = ap_const_lv1_1) and (hDir_load_load_fu_454_p1 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (icmp_ln1884_reg_855 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (patternId_val_load_read_reg_783 = ap_const_lv8_1)))) then 
            boxHCoord_loc_1_out_o <= sub_ln1914_fu_462_p2;
        else 
            boxHCoord_loc_1_out_o <= boxHCoord_loc_1_out_i;
        end if; 
    end process;


    boxHCoord_loc_1_out_o_ap_vld_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_block_pp0_stage0_11001, patternId_val_load_read_reg_783, icmp_ln1884_reg_855, hDir_load_load_fu_454_p1, icmp_ln1889_fu_472_p2, icmp_ln1894_fu_489_p2)
    begin
        if ((((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (icmp_ln1894_fu_489_p2 = ap_const_lv1_0) and (hDir_load_load_fu_454_p1 = ap_const_lv1_1) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (icmp_ln1884_reg_855 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (patternId_val_load_read_reg_783 = ap_const_lv8_1)) or ((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (icmp_ln1889_fu_472_p2 = ap_const_lv1_1) and (hDir_load_load_fu_454_p1 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (icmp_ln1884_reg_855 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (patternId_val_load_read_reg_783 = ap_const_lv8_1)) or ((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (((icmp_ln1889_fu_472_p2 = ap_const_lv1_0) and (hDir_load_load_fu_454_p1 = ap_const_lv1_0) and (icmp_ln1884_reg_855 = ap_const_lv1_1) and (patternId_val_load_read_reg_783 = ap_const_lv8_1)) or ((icmp_ln1894_fu_489_p2 
    = ap_const_lv1_1) and (hDir_load_load_fu_454_p1 = ap_const_lv1_1) and (icmp_ln1884_reg_855 = ap_const_lv1_1) and (patternId_val_load_read_reg_783 = ap_const_lv8_1)))))) then 
            boxHCoord_loc_1_out_o_ap_vld <= ap_const_logic_1;
        else 
            boxHCoord_loc_1_out_o_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    boxRight_fu_617_p2 <= std_logic_vector(unsigned(boxSize) + unsigned(boxHCoord_loc_1_out_i));
    boxVCoord <= boxVCoord_loc_1_out_i;

    boxVCoord_ap_vld_assign_proc : process(ap_enable_reg_pp0_iter2, ap_predicate_pred335_state3, ap_block_pp0_stage0_11001_grp0, ap_block_pp0_stage0_subdone_grp0_done_reg)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone_grp0_done_reg) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp0) and (ap_predicate_pred335_state3 = ap_const_boolean_1) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1))) then 
            boxVCoord_ap_vld <= ap_const_logic_1;
        else 
            boxVCoord_ap_vld <= ap_const_logic_0;
        end if; 
    end process;


    boxVCoord_loc_1_out_o_assign_proc : process(boxVCoord_loc_1_out_i, sub_ln1918_fu_516_p2, add_ln1916_fu_521_p2, ap_condition_393, ap_condition_400, ap_condition_329)
    begin
        if ((ap_const_boolean_1 = ap_condition_329)) then
            if ((ap_const_boolean_1 = ap_condition_400)) then 
                boxVCoord_loc_1_out_o <= add_ln1916_fu_521_p2;
            elsif ((ap_const_boolean_1 = ap_condition_393)) then 
                boxVCoord_loc_1_out_o <= sub_ln1918_fu_516_p2;
            else 
                boxVCoord_loc_1_out_o <= boxVCoord_loc_1_out_i;
            end if;
        else 
            boxVCoord_loc_1_out_o <= boxVCoord_loc_1_out_i;
        end if; 
    end process;


    boxVCoord_loc_1_out_o_ap_vld_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_block_pp0_stage0_11001, patternId_val_load_read_reg_783, icmp_ln1884_reg_855, vDir_load_load_fu_458_p1, icmp_ln1906_fu_537_p2, icmp_ln1901_fu_526_p2)
    begin
        if ((((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (((icmp_ln1901_fu_526_p2 = ap_const_lv1_0) and (vDir_load_load_fu_458_p1 = ap_const_lv1_0) and (icmp_ln1884_reg_855 = ap_const_lv1_1) and (patternId_val_load_read_reg_783 = ap_const_lv8_1)) or ((icmp_ln1906_fu_537_p2 = ap_const_lv1_1) and (vDir_load_load_fu_458_p1 = ap_const_lv1_1) and (icmp_ln1884_reg_855 = ap_const_lv1_1) and (patternId_val_load_read_reg_783 = ap_const_lv8_1)))) or ((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (((icmp_ln1901_fu_526_p2 = ap_const_lv1_1) and (vDir_load_load_fu_458_p1 = ap_const_lv1_0) and (icmp_ln1884_reg_855 = ap_const_lv1_1) and (patternId_val_load_read_reg_783 = ap_const_lv8_1)) or ((icmp_ln1906_fu_537_p2 = ap_const_lv1_0) and (vDir_load_load_fu_458_p1 = ap_const_lv1_1) and (icmp_ln1884_reg_855 = ap_const_lv1_1) and (patternId_val_load_read_reg_783 
    = ap_const_lv8_1)))))) then 
            boxVCoord_loc_1_out_o_ap_vld <= ap_const_logic_1;
        else 
            boxVCoord_loc_1_out_o_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    color_read_read_fu_168_p2 <= color;
    color_read_reg_747 <= color;
    hDir_load_load_fu_454_p1 <= hDir;
    icmp_ln1884_fu_419_p2 <= "1" when (or_ln1884_fu_413_p2 = ap_const_lv16_0) else "0";
    icmp_ln1889_fu_472_p2 <= "1" when (unsigned(boxHCoord_loc_1_out_i) > unsigned(hMax)) else "0";
    icmp_ln1894_fu_489_p2 <= "1" when (unsigned(zext_ln1889_cast_reg_804) > unsigned(boxHCoord_loc_1_out_i)) else "0";
    icmp_ln1901_fu_526_p2 <= "1" when (unsigned(boxVCoord_loc_1_out_i) > unsigned(vMax)) else "0";
    icmp_ln1906_fu_537_p2 <= "1" when (unsigned(zext_ln1889_cast_reg_804) > unsigned(boxVCoord_loc_1_out_i)) else "0";
    icmp_ln1932_1_fu_638_p2 <= "1" when (unsigned(y) < unsigned(boxBottom_fu_622_p2)) else "0";
    icmp_ln1932_fu_627_p2 <= "1" when (unsigned(y) < unsigned(boxVCoord_loc_1_out_i)) else "0";
    icmp_ln1937_1_fu_654_p2 <= "1" when (unsigned(x_1_reg_840_pp0_iter1_reg) < unsigned(boxRight_fu_617_p2)) else "0";
    icmp_ln1937_fu_643_p2 <= "1" when (unsigned(x_1_reg_840_pp0_iter1_reg) < unsigned(boxHCoord_loc_1_out_i)) else "0";
    icmp_ln1963_fu_425_p2 <= "1" when (ap_sig_allocacmp_x_1 = crossHairX) else "0";
    icmp_ln774_fu_397_p2 <= "1" when (ap_sig_allocacmp_x_1 = loopWidth) else "0";
    motionSpeed_cast_fu_361_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(motionSpeed),16));
    or_ln1884_fu_413_p2 <= (y or ap_sig_allocacmp_x_1);
    or_ln1963_fu_431_p2 <= (icmp_ln1963_fu_425_p2 or cmp2_i);

    ovrlayYUV_blk_n_assign_proc : process(ap_enable_reg_pp0_iter3, ovrlayYUV_full_n, ap_block_pp0_stage0)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_enable_reg_pp0_iter3 = ap_const_logic_1))) then 
            ovrlayYUV_blk_n <= ovrlayYUV_full_n;
        else 
            ovrlayYUV_blk_n <= ap_const_logic_1;
        end if; 
    end process;

    ovrlayYUV_din <= ((pixOut_12_fu_708_p3 & pixOut_13_fu_715_p3) & pixOut_14_fu_722_p3);

    ovrlayYUV_write_assign_proc : process(ap_enable_reg_pp0_iter3, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter3 = ap_const_logic_1))) then 
            ovrlayYUV_write <= ap_const_logic_1;
        else 
            ovrlayYUV_write <= ap_const_logic_0;
        end if; 
    end process;

    patternId_val_load_read_read_fu_234_p2 <= patternId_val_load;
    patternId_val_load_read_reg_783 <= patternId_val_load;
    pixIn_fu_565_p1 <= bckgndYUV_dout(10 - 1 downto 0);
    pixOut_10_fu_694_p3 <= 
        ap_const_lv10_0 when (and10_i_reg_830(0) = '1') else 
        ap_phi_mux_pix_3_phi_fu_322_p12;
    pixOut_11_fu_701_p3 <= 
        ap_const_lv10_0 when (and26_i_reg_825(0) = '1') else 
        ap_phi_mux_pix_4_phi_fu_304_p12;
    pixOut_12_fu_708_p3 <= 
        ap_phi_mux_pix_4_phi_fu_304_p12 when (tobool_reg_818(0) = '1') else 
        pixOut_11_fu_701_p3;
    pixOut_13_fu_715_p3 <= 
        ap_phi_mux_pix_3_phi_fu_322_p12 when (tobool_reg_818(0) = '1') else 
        pixOut_10_fu_694_p3;
    pixOut_14_fu_722_p3 <= 
        ap_phi_mux_pix_phi_fu_341_p12 when (tobool_reg_818(0) = '1') else 
        pixOut_9_fu_687_p3;
    pixOut_5_fu_681_p3 <= 
        boxColorB when (and_ln1947_fu_677_p2(0) = '1') else 
        boxColorG;
    pixOut_9_fu_687_p3 <= 
        ap_const_lv10_0 when (and4_i_reg_835(0) = '1') else 
        ap_phi_mux_pix_phi_fu_341_p12;
    select_ln1975_fu_437_p3 <= 
        ap_const_lv2_2 when (trunc_ln774_fu_409_p1(0) = '1') else 
        ap_const_lv2_1;
    sub_ln1914_fu_462_p2 <= std_logic_vector(unsigned(boxHCoord_loc_1_out_i) - unsigned(motionSpeed_cast_reg_810));
    sub_ln1918_fu_516_p2 <= std_logic_vector(unsigned(boxVCoord_loc_1_out_i) - unsigned(motionSpeed_cast_reg_810));
    tobool_fu_365_p2 <= "1" when (maskId = ap_const_lv8_0) else "0";
    trunc_ln774_fu_409_p1 <= ap_sig_allocacmp_x_1(1 - 1 downto 0);
    vDir_load_load_fu_458_p1 <= vDir;
    whiYuv_2_address0 <= zext_ln1975_fu_560_p1(2 - 1 downto 0);

    whiYuv_2_ce0_local_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            whiYuv_2_ce0_local <= ap_const_logic_1;
        else 
            whiYuv_2_ce0_local <= ap_const_logic_0;
        end if; 
    end process;

    x_2_fu_403_p2 <= std_logic_vector(unsigned(ap_sig_allocacmp_x_1) + unsigned(ap_const_lv16_1));
    xor_ln1932_fu_632_p2 <= (icmp_ln1932_fu_627_p2 xor ap_const_lv1_1);
    xor_ln1937_fu_648_p2 <= (icmp_ln1937_fu_643_p2 xor ap_const_lv1_1);
    zext_ln1889_cast_fu_357_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(zext_ln1889),16));
    zext_ln1975_fu_560_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(ap_phi_mux_phi_ln1975_phi_fu_294_p4),64));
end behav;
