// ==============================================================
// Generated by Vitis HLS v2024.2
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2024 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

module system_v_tpg_0_0_AXIvideo2MultiPixStream_Pipeline_loop_width (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        s_axis_video_TVALID,
        srcYUV_din,
        srcYUV_full_n,
        srcYUV_write,
        srcYUV_num_data_valid,
        srcYUV_fifo_cap,
        sof_5,
        axi_last_2,
        axi_data_6,
        empty,
        s_axis_video_TDATA,
        s_axis_video_TREADY,
        s_axis_video_TKEEP,
        s_axis_video_TSTRB,
        s_axis_video_TUSER,
        s_axis_video_TLAST,
        s_axis_video_TID,
        s_axis_video_TDEST,
        colorFormat_val,
        eol_out,
        eol_out_ap_vld,
        axi_data_7_out,
        axi_data_7_out_ap_vld
);

parameter    ap_ST_fsm_pp0_stage0 = 1'd1;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
input   s_axis_video_TVALID;
output  [29:0] srcYUV_din;
input   srcYUV_full_n;
output   srcYUV_write;
input  [4:0] srcYUV_num_data_valid;
input  [4:0] srcYUV_fifo_cap;
input  [0:0] sof_5;
input  [0:0] axi_last_2;
input  [29:0] axi_data_6;
input  [12:0] empty;
input  [31:0] s_axis_video_TDATA;
output   s_axis_video_TREADY;
input  [3:0] s_axis_video_TKEEP;
input  [3:0] s_axis_video_TSTRB;
input  [0:0] s_axis_video_TUSER;
input  [0:0] s_axis_video_TLAST;
input  [0:0] s_axis_video_TID;
input  [0:0] s_axis_video_TDEST;
input  [7:0] colorFormat_val;
output  [0:0] eol_out;
output   eol_out_ap_vld;
output  [29:0] axi_data_7_out;
output   axi_data_7_out_ap_vld;

reg ap_idle;
reg srcYUV_write;
reg s_axis_video_TREADY;
reg eol_out_ap_vld;
reg axi_data_7_out_ap_vld;

(* fsm_encoding = "none" *) reg   [0:0] ap_CS_fsm;
wire    ap_CS_fsm_pp0_stage0;
wire    ap_enable_reg_pp0_iter0;
reg    ap_enable_reg_pp0_iter1;
reg    ap_enable_reg_pp0_iter2;
reg    ap_idle_pp0;
reg   [0:0] icmp_ln850_reg_363;
wire   [0:0] or_ln854_fu_239_p2;
reg    ap_predicate_op41_read_state2;
reg    ap_block_state2_pp0_stage0_iter1;
reg   [0:0] icmp_ln850_reg_363_pp0_iter1_reg;
reg    ap_block_state3_pp0_stage0_iter2;
reg    ap_block_pp0_stage0_subdone;
wire   [0:0] icmp_ln850_fu_222_p2;
reg    ap_condition_exit_pp0_iter0_stage0;
wire    ap_loop_exit_ready;
reg    ap_ready_int;
reg    srcYUV_blk_n;
wire    ap_block_pp0_stage0;
reg    s_axis_video_TDATA_blk_n;
reg   [0:0] eol_reg_175;
reg   [0:0] sof_reg_187;
wire    ap_block_pp0_stage0_11001_grp0;
wire    ap_block_pp0_stage0_subdone_grp0;
reg    ap_block_pp0_stage0_11001;
wire   [0:0] cond_fu_198_p2;
reg   [0:0] cond_reg_356;
reg    ap_condition_exit_pp0_iter1_stage0;
reg   [0:0] ap_phi_mux_eol_phi_fu_179_p4;
wire    ap_loop_init;
reg   [0:0] ap_phi_mux_sof_phi_fu_191_p4;
reg   [12:0] j_fu_94;
wire   [12:0] j_4_fu_228_p2;
reg   [12:0] ap_sig_allocacmp_j_3;
reg   [29:0] axi_data_fu_98;
wire   [29:0] axi_data_4_fu_253_p1;
reg    ap_loop_exit_ready_pp0_iter1_reg;
reg   [0:0] axi_last_fu_102;
reg    ap_block_pp0_stage0_01001;
wire   [9:0] tmp_3_fu_273_p3;
wire   [9:0] trunc_ln63_fu_281_p1;
wire   [9:0] tmp_5_fu_292_p3;
wire   [9:0] select_ln880_2_fu_307_p3;
wire   [9:0] select_ln880_1_fu_300_p3;
wire   [9:0] select_ln880_fu_285_p3;
reg    ap_done_reg;
wire    ap_continue_int;
reg    ap_done_int;
reg   [0:0] ap_NS_fsm;
wire    ap_enable_pp0;
wire    ap_start_int;
wire    ap_ready_sig;
wire    ap_done_sig;
reg    ap_condition_308;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 1'd1;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 ap_enable_reg_pp0_iter2 = 1'b0;
#0 j_fu_94 = 13'd0;
#0 axi_data_fu_98 = 30'd0;
#0 axi_last_fu_102 = 1'd0;
#0 ap_done_reg = 1'b0;
end

system_v_tpg_0_0_flow_control_loop_pipe_sequential_init flow_control_loop_pipe_sequential_init_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(ap_start),
    .ap_ready(ap_ready_sig),
    .ap_done(ap_done_sig),
    .ap_start_int(ap_start_int),
    .ap_loop_init(ap_loop_init),
    .ap_ready_int(ap_ready_int),
    .ap_loop_exit_ready(ap_condition_exit_pp0_iter0_stage0),
    .ap_loop_exit_done(ap_done_int),
    .ap_continue_int(ap_continue_int),
    .ap_done_int(ap_done_int)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue_int == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_loop_exit_ready_pp0_iter1_reg == 1'b1))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_enable_reg_pp0_iter1 <= ap_start_int;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter2 <= 1'b0;
    end else begin
        if ((1'b1 == ap_condition_exit_pp0_iter1_stage0)) begin
            ap_enable_reg_pp0_iter2 <= 1'b0;
        end else if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if ((ap_loop_init == 1'b1)) begin
            axi_data_fu_98 <= axi_data_6;
        end else if ((1'b1 == ap_condition_308)) begin
            axi_data_fu_98 <= axi_data_4_fu_253_p1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if ((ap_loop_init == 1'b1)) begin
            axi_last_fu_102 <= axi_last_2;
        end else if ((1'b1 == ap_condition_308)) begin
            axi_last_fu_102 <= s_axis_video_TLAST;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln850_reg_363_pp0_iter1_reg == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        eol_reg_175 <= axi_last_fu_102;
    end else if (((1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_loop_init == 1'b1))) begin
        eol_reg_175 <= 1'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if (((icmp_ln850_fu_222_p2 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
            j_fu_94 <= j_4_fu_228_p2;
        end else if ((ap_loop_init == 1'b1)) begin
            j_fu_94 <= 13'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln850_reg_363_pp0_iter1_reg == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        sof_reg_187 <= 1'd0;
    end else if (((1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_loop_init == 1'b1))) begin
        sof_reg_187 <= sof_5;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_loop_exit_ready_pp0_iter1_reg <= ap_loop_exit_ready;
        cond_reg_356 <= cond_fu_198_p2;
        icmp_ln850_reg_363 <= icmp_ln850_fu_222_p2;
        icmp_ln850_reg_363_pp0_iter1_reg <= icmp_ln850_reg_363;
    end
end

always @ (*) begin
    if (((icmp_ln850_fu_222_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (icmp_ln850_reg_363 == 1'd1) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_condition_exit_pp0_iter1_stage0 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter1_stage0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_loop_exit_ready_pp0_iter1_reg == 1'b1))) begin
        ap_done_int = 1'b1;
    end else begin
        ap_done_int = ap_done_reg;
    end
end

always @ (*) begin
    if (((ap_start_int == 1'b0) & (ap_idle_pp0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter2 == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln850_reg_363_pp0_iter1_reg == 1'd0) & (1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        ap_phi_mux_eol_phi_fu_179_p4 = axi_last_fu_102;
    end else begin
        ap_phi_mux_eol_phi_fu_179_p4 = eol_reg_175;
    end
end

always @ (*) begin
    if (((icmp_ln850_reg_363_pp0_iter1_reg == 1'd0) & (1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        ap_phi_mux_sof_phi_fu_191_p4 = 1'd0;
    end else begin
        ap_phi_mux_sof_phi_fu_191_p4 = sof_reg_187;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_ready_int = 1'b1;
    end else begin
        ap_ready_int = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_loop_init == 1'b1))) begin
        ap_sig_allocacmp_j_3 = 13'd0;
    end else begin
        ap_sig_allocacmp_j_3 = j_fu_94;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln850_reg_363 == 1'd1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_loop_exit_ready_pp0_iter1_reg == 1'b1))) begin
        axi_data_7_out_ap_vld = 1'b1;
    end else begin
        axi_data_7_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln850_reg_363 == 1'd1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_loop_exit_ready_pp0_iter1_reg == 1'b1))) begin
        eol_out_ap_vld = 1'b1;
    end else begin
        eol_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_predicate_op41_read_state2 == 1'b1) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        s_axis_video_TDATA_blk_n = s_axis_video_TVALID;
    end else begin
        s_axis_video_TDATA_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_predicate_op41_read_state2 == 1'b1) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        s_axis_video_TREADY = 1'b1;
    end else begin
        s_axis_video_TREADY = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln850_reg_363_pp0_iter1_reg == 1'd0) & (1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        srcYUV_blk_n = srcYUV_full_n;
    end else begin
        srcYUV_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((icmp_ln850_reg_363_pp0_iter1_reg == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        srcYUV_write = 1'b1;
    end else begin
        srcYUV_write = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_pp0_stage0 : begin
            ap_NS_fsm = ap_ST_fsm_pp0_stage0;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd0];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage0_01001 = (((ap_enable_reg_pp0_iter2 == 1'b1) & (1'b1 == ap_block_state3_pp0_stage0_iter2)) | ((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_block_state2_pp0_stage0_iter1)));
end

always @ (*) begin
    ap_block_pp0_stage0_11001 = (((ap_enable_reg_pp0_iter2 == 1'b1) & (1'b1 == ap_block_state3_pp0_stage0_iter2)) | ((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_block_state2_pp0_stage0_iter1)));
end

assign ap_block_pp0_stage0_11001_grp0 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage0_subdone = (((ap_enable_reg_pp0_iter2 == 1'b1) & (1'b1 == ap_block_state3_pp0_stage0_iter2)) | ((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_block_state2_pp0_stage0_iter1)));
end

assign ap_block_pp0_stage0_subdone_grp0 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_state2_pp0_stage0_iter1 = ((ap_predicate_op41_read_state2 == 1'b1) & (s_axis_video_TVALID == 1'b0));
end

always @ (*) begin
    ap_block_state3_pp0_stage0_iter2 = ((icmp_ln850_reg_363_pp0_iter1_reg == 1'd0) & (srcYUV_full_n == 1'b0));
end

always @ (*) begin
    ap_condition_308 = ((or_ln854_fu_239_p2 == 1'd0) & (icmp_ln850_reg_363 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1));
end

assign ap_done = ap_done_sig;

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign ap_enable_reg_pp0_iter0 = ap_start_int;

assign ap_loop_exit_ready = ap_condition_exit_pp0_iter0_stage0;

always @ (*) begin
    ap_predicate_op41_read_state2 = ((or_ln854_fu_239_p2 == 1'd0) & (icmp_ln850_reg_363 == 1'd0));
end

assign ap_ready = ap_ready_sig;

assign axi_data_4_fu_253_p1 = s_axis_video_TDATA[29:0];

assign axi_data_7_out = axi_data_fu_98;

assign cond_fu_198_p2 = ((colorFormat_val == 8'd0) ? 1'b1 : 1'b0);

assign eol_out = eol_reg_175;

assign icmp_ln850_fu_222_p2 = ((ap_sig_allocacmp_j_3 == empty) ? 1'b1 : 1'b0);

assign j_4_fu_228_p2 = (ap_sig_allocacmp_j_3 + 13'd1);

assign or_ln854_fu_239_p2 = (ap_phi_mux_sof_phi_fu_191_p4 | ap_phi_mux_eol_phi_fu_179_p4);

assign select_ln880_1_fu_300_p3 = ((cond_reg_356[0:0] == 1'b1) ? trunc_ln63_fu_281_p1 : tmp_5_fu_292_p3);

assign select_ln880_2_fu_307_p3 = ((cond_reg_356[0:0] == 1'b1) ? tmp_5_fu_292_p3 : tmp_3_fu_273_p3);

assign select_ln880_fu_285_p3 = ((cond_reg_356[0:0] == 1'b1) ? tmp_3_fu_273_p3 : trunc_ln63_fu_281_p1);

assign srcYUV_din = {{{select_ln880_2_fu_307_p3}, {select_ln880_1_fu_300_p3}}, {select_ln880_fu_285_p3}};

assign tmp_3_fu_273_p3 = {{axi_data_fu_98[29:20]}};

assign tmp_5_fu_292_p3 = {{axi_data_fu_98[19:10]}};

assign trunc_ln63_fu_281_p1 = axi_data_fu_98[9:0];

endmodule //system_v_tpg_0_0_AXIvideo2MultiPixStream_Pipeline_loop_width
