// ==============================================================
// Generated by Vitis HLS v2024.2
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2024 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

module system_v_tpg_0_0_tpgForeground_Pipeline_VITIS_LOOP_774_2 (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        bckgndYUV_dout,
        bckgndYUV_empty_n,
        bckgndYUV_read,
        bckgndYUV_num_data_valid,
        bckgndYUV_fifo_cap,
        ovrlayYUV_din,
        ovrlayYUV_full_n,
        ovrlayYUV_write,
        ovrlayYUV_num_data_valid,
        ovrlayYUV_fifo_cap,
        loopWidth,
        boxColorB,
        conv2_i_i_i129,
        boxColorR,
        patternId_val_load,
        boxSize,
        y,
        vMax,
        motionSpeed,
        hMax,
        zext_ln1889,
        icmp,
        boxColorG,
        crossHairX,
        cmp2_i,
        color,
        maskId,
        cmp31_i,
        empty_46,
        empty_47,
        empty,
        boxHCoord_loc_1_out_i,
        boxHCoord_loc_1_out_o,
        boxHCoord_loc_1_out_o_ap_vld,
        boxVCoord_loc_1_out_i,
        boxVCoord_loc_1_out_o,
        boxVCoord_loc_1_out_o_ap_vld,
        boxVCoord,
        boxVCoord_ap_vld,
        boxHCoord,
        boxHCoord_ap_vld
);

parameter    ap_ST_fsm_pp0_stage0 = 1'd1;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
input  [29:0] bckgndYUV_dout;
input   bckgndYUV_empty_n;
output   bckgndYUV_read;
input  [4:0] bckgndYUV_num_data_valid;
input  [4:0] bckgndYUV_fifo_cap;
output  [29:0] ovrlayYUV_din;
input   ovrlayYUV_full_n;
output   ovrlayYUV_write;
input  [31:0] ovrlayYUV_num_data_valid;
input  [31:0] ovrlayYUV_fifo_cap;
input  [15:0] loopWidth;
input  [9:0] boxColorB;
input  [9:0] conv2_i_i_i129;
input  [9:0] boxColorR;
input  [7:0] patternId_val_load;
input  [15:0] boxSize;
input  [15:0] y;
input  [15:0] vMax;
input  [7:0] motionSpeed;
input  [15:0] hMax;
input  [8:0] zext_ln1889;
input  [0:0] icmp;
input  [9:0] boxColorG;
input  [15:0] crossHairX;
input  [0:0] cmp2_i;
input  [7:0] color;
input  [7:0] maskId;
input  [0:0] cmp31_i;
input  [0:0] empty_46;
input  [0:0] empty_47;
input  [0:0] empty;
input  [15:0] boxHCoord_loc_1_out_i;
output  [15:0] boxHCoord_loc_1_out_o;
output   boxHCoord_loc_1_out_o_ap_vld;
input  [15:0] boxVCoord_loc_1_out_i;
output  [15:0] boxVCoord_loc_1_out_o;
output   boxVCoord_loc_1_out_o_ap_vld;
output  [15:0] boxVCoord;
output   boxVCoord_ap_vld;
output  [15:0] boxHCoord;
output   boxHCoord_ap_vld;

reg ap_idle;
reg bckgndYUV_read;
reg ovrlayYUV_write;
reg[15:0] boxHCoord_loc_1_out_o;
reg boxHCoord_loc_1_out_o_ap_vld;
reg[15:0] boxVCoord_loc_1_out_o;
reg boxVCoord_loc_1_out_o_ap_vld;
reg boxVCoord_ap_vld;
reg boxHCoord_ap_vld;

(* fsm_encoding = "none" *) reg   [0:0] ap_CS_fsm;
wire    ap_CS_fsm_pp0_stage0;
wire    ap_enable_reg_pp0_iter0;
reg    ap_enable_reg_pp0_iter1;
reg    ap_enable_reg_pp0_iter2;
reg    ap_enable_reg_pp0_iter3;
reg    ap_idle_pp0;
reg   [0:0] icmp_ln774_reg_846;
reg   [0:0] icmp_ln774_reg_846_pp0_iter1_reg;
reg    ap_block_state3_pp0_stage0_iter2;
reg    ap_block_state4_pp0_stage0_iter3;
reg    ap_block_pp0_stage0_subdone;
wire   [0:0] icmp_ln774_fu_397_p2;
reg    ap_condition_exit_pp0_iter0_stage0;
wire    ap_loop_exit_ready;
reg    ap_ready_int;
reg   [0:0] vDir;
reg   [0:0] hDir;
wire   [1:0] whiYuv_2_address0;
wire   [9:0] whiYuv_2_q0;
reg    ovrlayYUV_blk_n;
wire    ap_block_pp0_stage0;
reg    bckgndYUV_blk_n;
wire   [7:0] color_read_read_fu_168_p2;
wire   [7:0] color_read_reg_747;
reg    ap_block_pp0_stage0_11001;
wire   [7:0] patternId_val_load_read_read_fu_234_p2;
wire   [7:0] patternId_val_load_read_reg_783;
wire   [15:0] zext_ln1889_cast_fu_357_p1;
reg   [15:0] zext_ln1889_cast_reg_804;
wire   [15:0] motionSpeed_cast_fu_361_p1;
reg   [15:0] motionSpeed_cast_reg_810;
wire   [0:0] tobool_fu_365_p2;
reg   [0:0] tobool_reg_818;
wire   [0:0] and26_i_fu_371_p2;
reg   [0:0] and26_i_reg_825;
wire   [0:0] and10_i_fu_377_p2;
reg   [0:0] and10_i_reg_830;
wire   [0:0] and4_i_fu_383_p2;
reg   [0:0] and4_i_reg_835;
reg   [15:0] x_1_reg_840;
reg   [15:0] x_1_reg_840_pp0_iter1_reg;
reg   [0:0] icmp_ln774_reg_846_pp0_iter2_reg;
wire   [0:0] trunc_ln774_fu_409_p1;
reg   [0:0] trunc_ln774_reg_850;
reg   [0:0] trunc_ln774_reg_850_pp0_iter1_reg;
wire   [0:0] icmp_ln1884_fu_419_p2;
reg   [0:0] icmp_ln1884_reg_855;
wire   [0:0] or_ln1963_fu_431_p2;
reg   [0:0] or_ln1963_reg_859;
wire   [1:0] select_ln1975_fu_437_p3;
reg   [1:0] select_ln1975_reg_863;
wire   [9:0] pixIn_fu_565_p1;
reg   [9:0] pixIn_reg_891;
reg   [9:0] pixIn_5_reg_898;
reg   [9:0] pixIn_6_reg_905;
wire   [0:0] and_ln1942_fu_671_p2;
reg   [0:0] and_ln1942_reg_912;
wire   [9:0] pixOut_5_fu_681_p3;
reg   [9:0] pixOut_5_reg_916;
reg   [1:0] ap_phi_mux_phi_ln1975_phi_fu_294_p4;
reg   [1:0] ap_phi_reg_pp0_iter1_phi_ln1975_reg_290;
wire   [1:0] ap_phi_reg_pp0_iter0_phi_ln1975_reg_290;
reg   [9:0] ap_phi_mux_pix_4_phi_fu_304_p12;
wire   [9:0] ap_phi_reg_pp0_iter0_pix_4_reg_301;
reg   [9:0] ap_phi_reg_pp0_iter1_pix_4_reg_301;
reg   [9:0] ap_phi_reg_pp0_iter2_pix_4_reg_301;
reg   [9:0] ap_phi_reg_pp0_iter3_pix_4_reg_301;
reg    ap_predicate_pred288_state3;
reg    ap_predicate_pred294_state3;
reg    ap_predicate_pred260_state3;
reg   [9:0] ap_phi_mux_pix_3_phi_fu_322_p12;
wire   [9:0] ap_phi_reg_pp0_iter0_pix_3_reg_318;
reg   [9:0] ap_phi_reg_pp0_iter1_pix_3_reg_318;
reg   [9:0] ap_phi_reg_pp0_iter2_pix_3_reg_318;
reg   [9:0] ap_phi_reg_pp0_iter3_pix_3_reg_318;
reg   [9:0] ap_phi_mux_pix_phi_fu_341_p12;
wire   [9:0] ap_phi_reg_pp0_iter0_pix_reg_337;
reg   [9:0] ap_phi_reg_pp0_iter1_pix_reg_337;
reg   [9:0] ap_phi_reg_pp0_iter2_pix_reg_337;
reg   [9:0] ap_phi_reg_pp0_iter3_pix_reg_337;
wire   [63:0] zext_ln1975_fu_560_p1;
wire   [15:0] sub_ln1914_fu_462_p2;
wire   [15:0] add_ln1912_fu_467_p2;
wire   [0:0] hDir_load_load_fu_454_p1;
wire   [0:0] icmp_ln1889_fu_472_p2;
wire   [0:0] icmp_ln1894_fu_489_p2;
wire    ap_block_pp0_stage0_grp0;
reg    ap_predicate_pred335_state3;
reg    ap_predicate_pred375_state3;
wire   [15:0] sub_ln1918_fu_516_p2;
wire   [15:0] add_ln1916_fu_521_p2;
wire   [0:0] vDir_load_load_fu_458_p1;
wire   [0:0] icmp_ln1906_fu_537_p2;
wire   [0:0] icmp_ln1901_fu_526_p2;
wire    ap_block_pp0_stage0_11001_grp0;
reg    ap_block_pp0_stage0_subdone_grp0_done_reg;
wire    ap_block_pp0_stage0_subdone_grp0;
reg   [15:0] x_fu_134;
wire   [15:0] x_2_fu_403_p2;
wire    ap_loop_init;
reg   [15:0] ap_sig_allocacmp_x_1;
reg    ap_block_pp0_stage0_01001;
reg    whiYuv_2_ce0_local;
wire   [15:0] or_ln1884_fu_413_p2;
wire   [0:0] icmp_ln1963_fu_425_p2;
wire   [0:0] icmp_ln1932_fu_627_p2;
wire   [15:0] boxBottom_fu_622_p2;
wire   [0:0] icmp_ln1937_fu_643_p2;
wire   [15:0] boxRight_fu_617_p2;
wire   [0:0] icmp_ln1937_1_fu_654_p2;
wire   [0:0] xor_ln1937_fu_648_p2;
wire   [0:0] xor_ln1932_fu_632_p2;
wire   [0:0] icmp_ln1932_1_fu_638_p2;
wire   [0:0] and_ln1942_1_fu_665_p2;
wire   [0:0] and_ln1942_2_fu_659_p2;
wire   [0:0] and_ln1947_fu_677_p2;
wire   [9:0] pixOut_11_fu_701_p3;
wire   [9:0] pixOut_10_fu_694_p3;
wire   [9:0] pixOut_9_fu_687_p3;
wire   [9:0] pixOut_12_fu_708_p3;
wire   [9:0] pixOut_13_fu_715_p3;
wire   [9:0] pixOut_14_fu_722_p3;
reg    ap_done_reg;
wire    ap_continue_int;
reg    ap_done_int;
reg    ap_loop_exit_ready_pp0_iter1_reg;
reg    ap_loop_exit_ready_pp0_iter2_reg;
reg   [0:0] ap_NS_fsm;
wire    ap_enable_pp0;
wire    ap_start_int;
wire    ap_ready_sig;
wire    ap_done_sig;
reg    ap_condition_276;
reg    ap_condition_269;
reg    ap_condition_300;
reg    ap_condition_393;
reg    ap_condition_400;
reg    ap_condition_329;
reg    ap_condition_691;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 1'd1;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 ap_enable_reg_pp0_iter2 = 1'b0;
#0 ap_enable_reg_pp0_iter3 = 1'b0;
#0 vDir = 1'd0;
#0 hDir = 1'd0;
#0 ap_block_pp0_stage0_subdone_grp0_done_reg = 1'b0;
#0 x_fu_134 = 16'd0;
#0 ap_done_reg = 1'b0;
end

system_v_tpg_0_0_tpgForeground_Pipeline_VITIS_LOOP_774_2_whiYuv_2_ROM_AUTO_1R #(
    .DataWidth( 10 ),
    .AddressRange( 3 ),
    .AddressWidth( 2 ))
whiYuv_2_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(whiYuv_2_address0),
    .ce0(whiYuv_2_ce0_local),
    .q0(whiYuv_2_q0)
);

system_v_tpg_0_0_flow_control_loop_pipe_sequential_init flow_control_loop_pipe_sequential_init_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(ap_start),
    .ap_ready(ap_ready_sig),
    .ap_done(ap_done_sig),
    .ap_start_int(ap_start_int),
    .ap_loop_init(ap_loop_init),
    .ap_ready_int(ap_ready_int),
    .ap_loop_exit_ready(ap_condition_exit_pp0_iter0_stage0),
    .ap_loop_exit_done(ap_done_int),
    .ap_continue_int(ap_continue_int),
    .ap_done_int(ap_done_int)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_block_pp0_stage0_subdone_grp0_done_reg <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_block_pp0_stage0_subdone_grp0_done_reg <= 1'b0;
        end else if ((1'b0 == ap_block_pp0_stage0_subdone_grp0)) begin
            ap_block_pp0_stage0_subdone_grp0_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue_int == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_loop_exit_ready_pp0_iter2_reg == 1'b1))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if ((1'b1 == ap_condition_exit_pp0_iter0_stage0)) begin
            ap_enable_reg_pp0_iter1 <= 1'b0;
        end else if (((1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_enable_reg_pp0_iter1 <= ap_start_int;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter2 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter3 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter3 <= ap_enable_reg_pp0_iter2;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_269)) begin
        if ((1'b1 == ap_condition_276)) begin
            ap_phi_reg_pp0_iter1_phi_ln1975_reg_290 <= 2'd1;
        end else if ((1'b1 == 1'b1)) begin
            ap_phi_reg_pp0_iter1_phi_ln1975_reg_290 <= ap_phi_reg_pp0_iter0_phi_ln1975_reg_290;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_269)) begin
        if ((1'b1 == ap_condition_300)) begin
            ap_phi_reg_pp0_iter1_pix_3_reg_318 <= 10'd960;
        end else if ((1'b1 == 1'b1)) begin
            ap_phi_reg_pp0_iter1_pix_3_reg_318 <= ap_phi_reg_pp0_iter0_pix_3_reg_318;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_269)) begin
        if ((1'b1 == ap_condition_300)) begin
            ap_phi_reg_pp0_iter1_pix_4_reg_301 <= conv2_i_i_i129;
        end else if ((1'b1 == 1'b1)) begin
            ap_phi_reg_pp0_iter1_pix_4_reg_301 <= ap_phi_reg_pp0_iter0_pix_4_reg_301;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_269)) begin
        if ((1'b1 == ap_condition_300)) begin
            ap_phi_reg_pp0_iter1_pix_reg_337 <= 10'd960;
        end else if ((1'b1 == 1'b1)) begin
            ap_phi_reg_pp0_iter1_pix_reg_337 <= ap_phi_reg_pp0_iter0_pix_reg_337;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_predicate_pred260_state3 == 1'b1) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        ap_phi_reg_pp0_iter3_pix_3_reg_318 <= whiYuv_2_q0;
    end else if ((((1'b0 == ap_block_pp0_stage0_11001) & (ap_predicate_pred294_state3 == 1'b1) & (ap_enable_reg_pp0_iter2 == 1'b1)) | ((1'b0 == ap_block_pp0_stage0_11001) & (ap_predicate_pred288_state3 == 1'b1) & (ap_enable_reg_pp0_iter2 == 1'b1)))) begin
        ap_phi_reg_pp0_iter3_pix_3_reg_318 <= {{bckgndYUV_dout[19:10]}};
    end else if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        ap_phi_reg_pp0_iter3_pix_3_reg_318 <= ap_phi_reg_pp0_iter2_pix_3_reg_318;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_predicate_pred260_state3 == 1'b1) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        ap_phi_reg_pp0_iter3_pix_4_reg_301 <= conv2_i_i_i129;
    end else if ((((1'b0 == ap_block_pp0_stage0_11001) & (ap_predicate_pred294_state3 == 1'b1) & (ap_enable_reg_pp0_iter2 == 1'b1)) | ((1'b0 == ap_block_pp0_stage0_11001) & (ap_predicate_pred288_state3 == 1'b1) & (ap_enable_reg_pp0_iter2 == 1'b1)))) begin
        ap_phi_reg_pp0_iter3_pix_4_reg_301 <= {{bckgndYUV_dout[29:20]}};
    end else if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        ap_phi_reg_pp0_iter3_pix_4_reg_301 <= ap_phi_reg_pp0_iter2_pix_4_reg_301;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_predicate_pred260_state3 == 1'b1) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        ap_phi_reg_pp0_iter3_pix_reg_337 <= 10'd960;
    end else if ((((1'b0 == ap_block_pp0_stage0_11001) & (ap_predicate_pred294_state3 == 1'b1) & (ap_enable_reg_pp0_iter2 == 1'b1)) | ((1'b0 == ap_block_pp0_stage0_11001) & (ap_predicate_pred288_state3 == 1'b1) & (ap_enable_reg_pp0_iter2 == 1'b1)))) begin
        ap_phi_reg_pp0_iter3_pix_reg_337 <= pixIn_fu_565_p1;
    end else if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        ap_phi_reg_pp0_iter3_pix_reg_337 <= ap_phi_reg_pp0_iter2_pix_reg_337;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_691)) begin
        if (((icmp_ln1894_fu_489_p2 == 1'd1) & (hDir_load_load_fu_454_p1 == 1'd1))) begin
            hDir <= 1'd0;
        end else if (((icmp_ln1889_fu_472_p2 == 1'd1) & (hDir_load_load_fu_454_p1 == 1'd0))) begin
            hDir <= 1'd1;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_691)) begin
        if (((icmp_ln1906_fu_537_p2 == 1'd1) & (vDir_load_load_fu_458_p1 == 1'd1))) begin
            vDir <= 1'd0;
        end else if (((icmp_ln1901_fu_526_p2 == 1'd1) & (vDir_load_load_fu_458_p1 == 1'd0))) begin
            vDir <= 1'd1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if (((icmp_ln774_fu_397_p2 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
            x_fu_134 <= x_2_fu_403_p2;
        end else if ((ap_loop_init == 1'b1)) begin
            x_fu_134 <= 16'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        and10_i_reg_830 <= and10_i_fu_377_p2;
        and26_i_reg_825 <= and26_i_fu_371_p2;
        and4_i_reg_835 <= and4_i_fu_383_p2;
        ap_loop_exit_ready_pp0_iter1_reg <= ap_loop_exit_ready;
        ap_loop_exit_ready_pp0_iter2_reg <= ap_loop_exit_ready_pp0_iter1_reg;
        ap_predicate_pred260_state3 <= (~(color_read_reg_747 == 8'd0) & (icmp_ln774_reg_846 == 1'd0) & (or_ln1963_reg_859 == 1'd1) & (patternId_val_load_read_reg_783 == 8'd2));
        ap_predicate_pred288_state3 <= (~(patternId_val_load_read_reg_783 == 8'd1) & ~(patternId_val_load_read_reg_783 == 8'd2) & (icmp_ln774_reg_846 == 1'd0));
        ap_predicate_pred294_state3 <= ((icmp_ln774_reg_846 == 1'd0) & (or_ln1963_reg_859 == 1'd0) & (patternId_val_load_read_reg_783 == 8'd2));
        ap_predicate_pred335_state3 <= ((icmp_ln1884_reg_855 == 1'd1) & (patternId_val_load_read_reg_783 == 8'd1));
        ap_predicate_pred375_state3 <= ((icmp_ln774_reg_846 == 1'd0) & (patternId_val_load_read_reg_783 == 8'd1));
        icmp_ln1884_reg_855 <= icmp_ln1884_fu_419_p2;
        icmp_ln774_reg_846 <= icmp_ln774_fu_397_p2;
        icmp_ln774_reg_846_pp0_iter1_reg <= icmp_ln774_reg_846;
        motionSpeed_cast_reg_810[7 : 0] <= motionSpeed_cast_fu_361_p1[7 : 0];
        or_ln1963_reg_859 <= or_ln1963_fu_431_p2;
        select_ln1975_reg_863 <= select_ln1975_fu_437_p3;
        tobool_reg_818 <= tobool_fu_365_p2;
        trunc_ln774_reg_850 <= trunc_ln774_fu_409_p1;
        trunc_ln774_reg_850_pp0_iter1_reg <= trunc_ln774_reg_850;
        x_1_reg_840 <= ap_sig_allocacmp_x_1;
        x_1_reg_840_pp0_iter1_reg <= x_1_reg_840;
        zext_ln1889_cast_reg_804[8 : 0] <= zext_ln1889_cast_fu_357_p1[8 : 0];
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        and_ln1942_reg_912 <= and_ln1942_fu_671_p2;
        icmp_ln774_reg_846_pp0_iter2_reg <= icmp_ln774_reg_846_pp0_iter1_reg;
        pixIn_5_reg_898 <= {{bckgndYUV_dout[19:10]}};
        pixIn_6_reg_905 <= {{bckgndYUV_dout[29:20]}};
        pixIn_reg_891 <= pixIn_fu_565_p1;
        pixOut_5_reg_916 <= pixOut_5_fu_681_p3;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_phi_reg_pp0_iter2_pix_3_reg_318 <= ap_phi_reg_pp0_iter1_pix_3_reg_318;
        ap_phi_reg_pp0_iter2_pix_4_reg_301 <= ap_phi_reg_pp0_iter1_pix_4_reg_301;
        ap_phi_reg_pp0_iter2_pix_reg_337 <= ap_phi_reg_pp0_iter1_pix_reg_337;
    end
end

always @ (*) begin
    if (((icmp_ln774_fu_397_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_loop_exit_ready_pp0_iter2_reg == 1'b1))) begin
        ap_done_int = 1'b1;
    end else begin
        ap_done_int = ap_done_reg;
    end
end

always @ (*) begin
    if (((ap_start_int == 1'b0) & (ap_idle_pp0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter3 == 1'b0) & (ap_enable_reg_pp0_iter2 == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if ((~(color_read_reg_747 == 8'd1) & ~(color_read_reg_747 == 8'd0) & (icmp_ln774_reg_846 == 1'd0) & (or_ln1963_reg_859 == 1'd1) & (patternId_val_load_read_reg_783 == 8'd2))) begin
        ap_phi_mux_phi_ln1975_phi_fu_294_p4 = select_ln1975_reg_863;
    end else begin
        ap_phi_mux_phi_ln1975_phi_fu_294_p4 = ap_phi_reg_pp0_iter1_phi_ln1975_reg_290;
    end
end

always @ (*) begin
    if (((icmp_ln774_reg_846_pp0_iter2_reg == 1'd0) & (patternId_val_load_read_reg_783 == 8'd1))) begin
        if ((1'd0 == and_ln1942_reg_912)) begin
            ap_phi_mux_pix_3_phi_fu_322_p12 = pixIn_5_reg_898;
        end else if ((1'd1 == and_ln1942_reg_912)) begin
            ap_phi_mux_pix_3_phi_fu_322_p12 = pixOut_5_reg_916;
        end else begin
            ap_phi_mux_pix_3_phi_fu_322_p12 = ap_phi_reg_pp0_iter3_pix_3_reg_318;
        end
    end else begin
        ap_phi_mux_pix_3_phi_fu_322_p12 = ap_phi_reg_pp0_iter3_pix_3_reg_318;
    end
end

always @ (*) begin
    if (((icmp_ln774_reg_846_pp0_iter2_reg == 1'd0) & (patternId_val_load_read_reg_783 == 8'd1))) begin
        if ((1'd0 == and_ln1942_reg_912)) begin
            ap_phi_mux_pix_4_phi_fu_304_p12 = pixIn_6_reg_905;
        end else if ((1'd1 == and_ln1942_reg_912)) begin
            ap_phi_mux_pix_4_phi_fu_304_p12 = boxColorB;
        end else begin
            ap_phi_mux_pix_4_phi_fu_304_p12 = ap_phi_reg_pp0_iter3_pix_4_reg_301;
        end
    end else begin
        ap_phi_mux_pix_4_phi_fu_304_p12 = ap_phi_reg_pp0_iter3_pix_4_reg_301;
    end
end

always @ (*) begin
    if (((icmp_ln774_reg_846_pp0_iter2_reg == 1'd0) & (patternId_val_load_read_reg_783 == 8'd1))) begin
        if ((1'd0 == and_ln1942_reg_912)) begin
            ap_phi_mux_pix_phi_fu_341_p12 = pixIn_reg_891;
        end else if ((1'd1 == and_ln1942_reg_912)) begin
            ap_phi_mux_pix_phi_fu_341_p12 = boxColorR;
        end else begin
            ap_phi_mux_pix_phi_fu_341_p12 = ap_phi_reg_pp0_iter3_pix_reg_337;
        end
    end else begin
        ap_phi_mux_pix_phi_fu_341_p12 = ap_phi_reg_pp0_iter3_pix_reg_337;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_ready_int = 1'b1;
    end else begin
        ap_ready_int = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_sig_allocacmp_x_1 = 16'd0;
    end else begin
        ap_sig_allocacmp_x_1 = x_fu_134;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (icmp_ln774_reg_846_pp0_iter1_reg == 1'd0) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        bckgndYUV_blk_n = bckgndYUV_empty_n;
    end else begin
        bckgndYUV_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln774_reg_846_pp0_iter1_reg == 1'd0) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        bckgndYUV_read = 1'b1;
    end else begin
        bckgndYUV_read = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone_grp0_done_reg) & (1'b0 == ap_block_pp0_stage0_11001_grp0) & (ap_predicate_pred335_state3 == 1'b1) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        boxHCoord_ap_vld = 1'b1;
    end else begin
        boxHCoord_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (((icmp_ln1889_fu_472_p2 == 1'd0) & (hDir_load_load_fu_454_p1 == 1'd0) & (icmp_ln1884_reg_855 == 1'd1) & (patternId_val_load_read_reg_783 == 8'd1)) | ((icmp_ln1894_fu_489_p2 == 1'd1) & (hDir_load_load_fu_454_p1 == 1'd1) & (icmp_ln1884_reg_855 == 1'd1) & (patternId_val_load_read_reg_783 == 8'd1))))) begin
        boxHCoord_loc_1_out_o = add_ln1912_fu_467_p2;
    end else if ((((1'b0 == ap_block_pp0_stage0) & (icmp_ln1894_fu_489_p2 == 1'd0) & (hDir_load_load_fu_454_p1 == 1'd1) & (ap_enable_reg_pp0_iter1 == 1'b1) & (icmp_ln1884_reg_855 == 1'd1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (patternId_val_load_read_reg_783 == 8'd1)) | ((1'b0 == ap_block_pp0_stage0) & (icmp_ln1889_fu_472_p2 == 1'd1) & (hDir_load_load_fu_454_p1 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (icmp_ln1884_reg_855 == 1'd1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (patternId_val_load_read_reg_783 == 8'd1)))) begin
        boxHCoord_loc_1_out_o = sub_ln1914_fu_462_p2;
    end else begin
        boxHCoord_loc_1_out_o = boxHCoord_loc_1_out_i;
    end
end

always @ (*) begin
    if ((((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln1894_fu_489_p2 == 1'd0) & (hDir_load_load_fu_454_p1 == 1'd1) & (ap_enable_reg_pp0_iter1 == 1'b1) & (icmp_ln1884_reg_855 == 1'd1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (patternId_val_load_read_reg_783 == 8'd1)) | ((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln1889_fu_472_p2 == 1'd1) & (hDir_load_load_fu_454_p1 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (icmp_ln1884_reg_855 == 1'd1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (patternId_val_load_read_reg_783 == 8'd1)) | ((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (((icmp_ln1889_fu_472_p2 == 1'd0) & (hDir_load_load_fu_454_p1 == 1'd0) & (icmp_ln1884_reg_855 == 1'd1) & (patternId_val_load_read_reg_783 == 8'd1)) | ((icmp_ln1894_fu_489_p2 == 1'd1) & (hDir_load_load_fu_454_p1 == 1'd1) & (icmp_ln1884_reg_855 == 1'd1) & (patternId_val_load_read_reg_783 == 8'd1)))))) begin
        boxHCoord_loc_1_out_o_ap_vld = 1'b1;
    end else begin
        boxHCoord_loc_1_out_o_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone_grp0_done_reg) & (1'b0 == ap_block_pp0_stage0_11001_grp0) & (ap_predicate_pred335_state3 == 1'b1) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        boxVCoord_ap_vld = 1'b1;
    end else begin
        boxVCoord_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_condition_329)) begin
        if ((1'b1 == ap_condition_400)) begin
            boxVCoord_loc_1_out_o = add_ln1916_fu_521_p2;
        end else if ((1'b1 == ap_condition_393)) begin
            boxVCoord_loc_1_out_o = sub_ln1918_fu_516_p2;
        end else begin
            boxVCoord_loc_1_out_o = boxVCoord_loc_1_out_i;
        end
    end else begin
        boxVCoord_loc_1_out_o = boxVCoord_loc_1_out_i;
    end
end

always @ (*) begin
    if ((((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (((icmp_ln1901_fu_526_p2 == 1'd0) & (vDir_load_load_fu_458_p1 == 1'd0) & (icmp_ln1884_reg_855 == 1'd1) & (patternId_val_load_read_reg_783 == 8'd1)) | ((icmp_ln1906_fu_537_p2 == 1'd1) & (vDir_load_load_fu_458_p1 == 1'd1) & (icmp_ln1884_reg_855 == 1'd1) & (patternId_val_load_read_reg_783 == 8'd1)))) | ((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (((icmp_ln1901_fu_526_p2 == 1'd1) & (vDir_load_load_fu_458_p1 == 1'd0) & (icmp_ln1884_reg_855 == 1'd1) & (patternId_val_load_read_reg_783 == 8'd1)) | ((icmp_ln1906_fu_537_p2 == 1'd0) & (vDir_load_load_fu_458_p1 == 1'd1) & (icmp_ln1884_reg_855 == 1'd1) & (patternId_val_load_read_reg_783 == 8'd1)))))) begin
        boxVCoord_loc_1_out_o_ap_vld = 1'b1;
    end else begin
        boxVCoord_loc_1_out_o_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter3 == 1'b1))) begin
        ovrlayYUV_blk_n = ovrlayYUV_full_n;
    end else begin
        ovrlayYUV_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter3 == 1'b1))) begin
        ovrlayYUV_write = 1'b1;
    end else begin
        ovrlayYUV_write = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        whiYuv_2_ce0_local = 1'b1;
    end else begin
        whiYuv_2_ce0_local = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_pp0_stage0 : begin
            ap_NS_fsm = ap_ST_fsm_pp0_stage0;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign add_ln1912_fu_467_p2 = (boxHCoord_loc_1_out_i + motionSpeed_cast_reg_810);

assign add_ln1916_fu_521_p2 = (boxVCoord_loc_1_out_i + motionSpeed_cast_reg_810);

assign and10_i_fu_377_p2 = (empty_47 & cmp31_i);

assign and26_i_fu_371_p2 = (empty_46 & cmp31_i);

assign and4_i_fu_383_p2 = (empty & cmp31_i);

assign and_ln1942_1_fu_665_p2 = (xor_ln1932_fu_632_p2 & icmp_ln1932_1_fu_638_p2);

assign and_ln1942_2_fu_659_p2 = (xor_ln1937_fu_648_p2 & icmp_ln1937_1_fu_654_p2);

assign and_ln1942_fu_671_p2 = (and_ln1942_2_fu_659_p2 & and_ln1942_1_fu_665_p2);

assign and_ln1947_fu_677_p2 = (trunc_ln774_reg_850_pp0_iter1_reg & icmp);

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd0];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage0_01001 = (((ap_enable_reg_pp0_iter3 == 1'b1) & (1'b1 == ap_block_state4_pp0_stage0_iter3)) | ((ap_enable_reg_pp0_iter2 == 1'b1) & (1'b1 == ap_block_state3_pp0_stage0_iter2)));
end

always @ (*) begin
    ap_block_pp0_stage0_11001 = (((ap_enable_reg_pp0_iter3 == 1'b1) & (1'b1 == ap_block_state4_pp0_stage0_iter3)) | ((ap_enable_reg_pp0_iter2 == 1'b1) & (1'b1 == ap_block_state3_pp0_stage0_iter2)));
end

assign ap_block_pp0_stage0_11001_grp0 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_grp0 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage0_subdone = (((ap_enable_reg_pp0_iter3 == 1'b1) & (1'b1 == ap_block_state4_pp0_stage0_iter3)) | ((ap_enable_reg_pp0_iter2 == 1'b1) & (1'b1 == ap_block_state3_pp0_stage0_iter2)));
end

assign ap_block_pp0_stage0_subdone_grp0 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_state3_pp0_stage0_iter2 = ((icmp_ln774_reg_846_pp0_iter1_reg == 1'd0) & (bckgndYUV_empty_n == 1'b0));
end

always @ (*) begin
    ap_block_state4_pp0_stage0_iter3 = (ovrlayYUV_full_n == 1'b0);
end

always @ (*) begin
    ap_condition_269 = ((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0));
end

always @ (*) begin
    ap_condition_276 = ((icmp_ln774_fu_397_p2 == 1'd0) & (or_ln1963_fu_431_p2 == 1'd1) & (patternId_val_load_read_read_fu_234_p2 == 8'd2) & (color_read_read_fu_168_p2 == 8'd1));
end

always @ (*) begin
    ap_condition_300 = ((icmp_ln774_fu_397_p2 == 1'd0) & (or_ln1963_fu_431_p2 == 1'd1) & (patternId_val_load_read_read_fu_234_p2 == 8'd2) & (color_read_read_fu_168_p2 == 8'd0));
end

always @ (*) begin
    ap_condition_329 = ((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0));
end

always @ (*) begin
    ap_condition_393 = (((icmp_ln1901_fu_526_p2 == 1'd1) & (vDir_load_load_fu_458_p1 == 1'd0) & (icmp_ln1884_reg_855 == 1'd1) & (patternId_val_load_read_reg_783 == 8'd1)) | ((icmp_ln1906_fu_537_p2 == 1'd0) & (vDir_load_load_fu_458_p1 == 1'd1) & (icmp_ln1884_reg_855 == 1'd1) & (patternId_val_load_read_reg_783 == 8'd1)));
end

always @ (*) begin
    ap_condition_400 = (((icmp_ln1901_fu_526_p2 == 1'd0) & (vDir_load_load_fu_458_p1 == 1'd0) & (icmp_ln1884_reg_855 == 1'd1) & (patternId_val_load_read_reg_783 == 8'd1)) | ((icmp_ln1906_fu_537_p2 == 1'd1) & (vDir_load_load_fu_458_p1 == 1'd1) & (icmp_ln1884_reg_855 == 1'd1) & (patternId_val_load_read_reg_783 == 8'd1)));
end

always @ (*) begin
    ap_condition_691 = ((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (icmp_ln1884_reg_855 == 1'd1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (patternId_val_load_read_reg_783 == 8'd1));
end

assign ap_done = ap_done_sig;

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign ap_enable_reg_pp0_iter0 = ap_start_int;

assign ap_loop_exit_ready = ap_condition_exit_pp0_iter0_stage0;

assign ap_phi_reg_pp0_iter0_phi_ln1975_reg_290 = 'bx;

assign ap_phi_reg_pp0_iter0_pix_3_reg_318 = 'bx;

assign ap_phi_reg_pp0_iter0_pix_4_reg_301 = 'bx;

assign ap_phi_reg_pp0_iter0_pix_reg_337 = 'bx;

assign ap_ready = ap_ready_sig;

assign boxBottom_fu_622_p2 = (boxSize + boxVCoord_loc_1_out_i);

assign boxHCoord = boxHCoord_loc_1_out_i;

assign boxRight_fu_617_p2 = (boxSize + boxHCoord_loc_1_out_i);

assign boxVCoord = boxVCoord_loc_1_out_i;

assign color_read_read_fu_168_p2 = color;

assign color_read_reg_747 = color;

assign hDir_load_load_fu_454_p1 = hDir;

assign icmp_ln1884_fu_419_p2 = ((or_ln1884_fu_413_p2 == 16'd0) ? 1'b1 : 1'b0);

assign icmp_ln1889_fu_472_p2 = ((boxHCoord_loc_1_out_i > hMax) ? 1'b1 : 1'b0);

assign icmp_ln1894_fu_489_p2 = ((zext_ln1889_cast_reg_804 > boxHCoord_loc_1_out_i) ? 1'b1 : 1'b0);

assign icmp_ln1901_fu_526_p2 = ((boxVCoord_loc_1_out_i > vMax) ? 1'b1 : 1'b0);

assign icmp_ln1906_fu_537_p2 = ((zext_ln1889_cast_reg_804 > boxVCoord_loc_1_out_i) ? 1'b1 : 1'b0);

assign icmp_ln1932_1_fu_638_p2 = ((y < boxBottom_fu_622_p2) ? 1'b1 : 1'b0);

assign icmp_ln1932_fu_627_p2 = ((y < boxVCoord_loc_1_out_i) ? 1'b1 : 1'b0);

assign icmp_ln1937_1_fu_654_p2 = ((x_1_reg_840_pp0_iter1_reg < boxRight_fu_617_p2) ? 1'b1 : 1'b0);

assign icmp_ln1937_fu_643_p2 = ((x_1_reg_840_pp0_iter1_reg < boxHCoord_loc_1_out_i) ? 1'b1 : 1'b0);

assign icmp_ln1963_fu_425_p2 = ((ap_sig_allocacmp_x_1 == crossHairX) ? 1'b1 : 1'b0);

assign icmp_ln774_fu_397_p2 = ((ap_sig_allocacmp_x_1 == loopWidth) ? 1'b1 : 1'b0);

assign motionSpeed_cast_fu_361_p1 = motionSpeed;

assign or_ln1884_fu_413_p2 = (y | ap_sig_allocacmp_x_1);

assign or_ln1963_fu_431_p2 = (icmp_ln1963_fu_425_p2 | cmp2_i);

assign ovrlayYUV_din = {{{pixOut_12_fu_708_p3}, {pixOut_13_fu_715_p3}}, {pixOut_14_fu_722_p3}};

assign patternId_val_load_read_read_fu_234_p2 = patternId_val_load;

assign patternId_val_load_read_reg_783 = patternId_val_load;

assign pixIn_fu_565_p1 = bckgndYUV_dout[9:0];

assign pixOut_10_fu_694_p3 = ((and10_i_reg_830[0:0] == 1'b1) ? 10'd0 : ap_phi_mux_pix_3_phi_fu_322_p12);

assign pixOut_11_fu_701_p3 = ((and26_i_reg_825[0:0] == 1'b1) ? 10'd0 : ap_phi_mux_pix_4_phi_fu_304_p12);

assign pixOut_12_fu_708_p3 = ((tobool_reg_818[0:0] == 1'b1) ? ap_phi_mux_pix_4_phi_fu_304_p12 : pixOut_11_fu_701_p3);

assign pixOut_13_fu_715_p3 = ((tobool_reg_818[0:0] == 1'b1) ? ap_phi_mux_pix_3_phi_fu_322_p12 : pixOut_10_fu_694_p3);

assign pixOut_14_fu_722_p3 = ((tobool_reg_818[0:0] == 1'b1) ? ap_phi_mux_pix_phi_fu_341_p12 : pixOut_9_fu_687_p3);

assign pixOut_5_fu_681_p3 = ((and_ln1947_fu_677_p2[0:0] == 1'b1) ? boxColorB : boxColorG);

assign pixOut_9_fu_687_p3 = ((and4_i_reg_835[0:0] == 1'b1) ? 10'd0 : ap_phi_mux_pix_phi_fu_341_p12);

assign select_ln1975_fu_437_p3 = ((trunc_ln774_fu_409_p1[0:0] == 1'b1) ? 2'd2 : 2'd1);

assign sub_ln1914_fu_462_p2 = (boxHCoord_loc_1_out_i - motionSpeed_cast_reg_810);

assign sub_ln1918_fu_516_p2 = (boxVCoord_loc_1_out_i - motionSpeed_cast_reg_810);

assign tobool_fu_365_p2 = ((maskId == 8'd0) ? 1'b1 : 1'b0);

assign trunc_ln774_fu_409_p1 = ap_sig_allocacmp_x_1[0:0];

assign vDir_load_load_fu_458_p1 = vDir;

assign whiYuv_2_address0 = zext_ln1975_fu_560_p1;

assign x_2_fu_403_p2 = (ap_sig_allocacmp_x_1 + 16'd1);

assign xor_ln1932_fu_632_p2 = (icmp_ln1932_fu_627_p2 ^ 1'd1);

assign xor_ln1937_fu_648_p2 = (icmp_ln1937_fu_643_p2 ^ 1'd1);

assign zext_ln1889_cast_fu_357_p1 = zext_ln1889;

assign zext_ln1975_fu_560_p1 = ap_phi_mux_phi_ln1975_phi_fu_294_p4;

always @ (posedge ap_clk) begin
    zext_ln1889_cast_reg_804[15:9] <= 7'b0000000;
    motionSpeed_cast_reg_810[15:8] <= 8'b00000000;
end

endmodule //system_v_tpg_0_0_tpgForeground_Pipeline_VITIS_LOOP_774_2
