// ==============================================================
// Generated by Vitis HLS v2024.2
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2024 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

module system_v_tpg_0_0_tpgBackground (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_continue,
        ap_idle,
        ap_ready,
        srcYUV_dout,
        srcYUV_empty_n,
        srcYUV_read,
        srcYUV_num_data_valid,
        srcYUV_fifo_cap,
        height_val_dout,
        height_val_empty_n,
        height_val_read,
        height_val_num_data_valid,
        height_val_fifo_cap,
        width_val_dout,
        width_val_empty_n,
        width_val_read,
        width_val_num_data_valid,
        width_val_fifo_cap,
        passthruStartX_val_dout,
        passthruStartX_val_empty_n,
        passthruStartX_val_read,
        passthruStartX_val_num_data_valid,
        passthruStartX_val_fifo_cap,
        passthruStartY_val_dout,
        passthruStartY_val_empty_n,
        passthruStartY_val_read,
        passthruStartY_val_num_data_valid,
        passthruStartY_val_fifo_cap,
        passthruEndX_val_dout,
        passthruEndX_val_empty_n,
        passthruEndX_val_read,
        passthruEndX_val_num_data_valid,
        passthruEndX_val_fifo_cap,
        passthruEndY_val_dout,
        passthruEndY_val_empty_n,
        passthruEndY_val_read,
        passthruEndY_val_num_data_valid,
        passthruEndY_val_fifo_cap,
        enableInput_val_dout,
        enableInput_val_empty_n,
        enableInput_val_read,
        enableInput_val_num_data_valid,
        enableInput_val_fifo_cap,
        patternId_val_dout,
        patternId_val_empty_n,
        patternId_val_read,
        patternId_val_num_data_valid,
        patternId_val_fifo_cap,
        ZplateHorContStart_val_dout,
        ZplateHorContStart_val_empty_n,
        ZplateHorContStart_val_read,
        ZplateHorContStart_val_num_data_valid,
        ZplateHorContStart_val_fifo_cap,
        ZplateHorContDelta_val_dout,
        ZplateHorContDelta_val_empty_n,
        ZplateHorContDelta_val_read,
        ZplateHorContDelta_val_num_data_valid,
        ZplateHorContDelta_val_fifo_cap,
        ZplateVerContStart_val_dout,
        ZplateVerContStart_val_empty_n,
        ZplateVerContStart_val_read,
        ZplateVerContStart_val_num_data_valid,
        ZplateVerContStart_val_fifo_cap,
        ZplateVerContDelta_val_dout,
        ZplateVerContDelta_val_empty_n,
        ZplateVerContDelta_val_read,
        ZplateVerContDelta_val_num_data_valid,
        ZplateVerContDelta_val_fifo_cap,
        dpDynamicRange_val_dout,
        dpDynamicRange_val_empty_n,
        dpDynamicRange_val_read,
        dpDynamicRange_val_num_data_valid,
        dpDynamicRange_val_fifo_cap,
        dpYUVCoef_val_dout,
        dpYUVCoef_val_empty_n,
        dpYUVCoef_val_read,
        dpYUVCoef_val_num_data_valid,
        dpYUVCoef_val_fifo_cap,
        motionSpeed_val_dout,
        motionSpeed_val_empty_n,
        motionSpeed_val_read,
        motionSpeed_val_num_data_valid,
        motionSpeed_val_fifo_cap,
        colorFormat_val_dout,
        colorFormat_val_empty_n,
        colorFormat_val_read,
        colorFormat_val_num_data_valid,
        colorFormat_val_fifo_cap,
        bckgndYUV_din,
        bckgndYUV_full_n,
        bckgndYUV_write,
        bckgndYUV_num_data_valid,
        bckgndYUV_fifo_cap,
        height_val5_c3_din,
        height_val5_c3_full_n,
        height_val5_c3_write,
        height_val5_c3_num_data_valid,
        height_val5_c3_fifo_cap,
        width_val10_c5_din,
        width_val10_c5_full_n,
        width_val10_c5_write,
        width_val10_c5_num_data_valid,
        width_val10_c5_fifo_cap,
        motionSpeed_val23_c_din,
        motionSpeed_val23_c_full_n,
        motionSpeed_val23_c_write,
        motionSpeed_val23_c_num_data_valid,
        motionSpeed_val23_c_fifo_cap,
        colorFormat_val27_c8_din,
        colorFormat_val27_c8_full_n,
        colorFormat_val27_c8_write,
        colorFormat_val27_c8_num_data_valid,
        colorFormat_val27_c8_fifo_cap,
        s
);

parameter    ap_ST_fsm_state1 = 6'd1;
parameter    ap_ST_fsm_state2 = 6'd2;
parameter    ap_ST_fsm_state3 = 6'd4;
parameter    ap_ST_fsm_state4 = 6'd8;
parameter    ap_ST_fsm_state5 = 6'd16;
parameter    ap_ST_fsm_state6 = 6'd32;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
input   ap_continue;
output   ap_idle;
output   ap_ready;
input  [29:0] srcYUV_dout;
input   srcYUV_empty_n;
output   srcYUV_read;
input  [4:0] srcYUV_num_data_valid;
input  [4:0] srcYUV_fifo_cap;
input  [15:0] height_val_dout;
input   height_val_empty_n;
output   height_val_read;
input  [2:0] height_val_num_data_valid;
input  [2:0] height_val_fifo_cap;
input  [15:0] width_val_dout;
input   width_val_empty_n;
output   width_val_read;
input  [2:0] width_val_num_data_valid;
input  [2:0] width_val_fifo_cap;
input  [15:0] passthruStartX_val_dout;
input   passthruStartX_val_empty_n;
output   passthruStartX_val_read;
input  [2:0] passthruStartX_val_num_data_valid;
input  [2:0] passthruStartX_val_fifo_cap;
input  [15:0] passthruStartY_val_dout;
input   passthruStartY_val_empty_n;
output   passthruStartY_val_read;
input  [2:0] passthruStartY_val_num_data_valid;
input  [2:0] passthruStartY_val_fifo_cap;
input  [15:0] passthruEndX_val_dout;
input   passthruEndX_val_empty_n;
output   passthruEndX_val_read;
input  [2:0] passthruEndX_val_num_data_valid;
input  [2:0] passthruEndX_val_fifo_cap;
input  [15:0] passthruEndY_val_dout;
input   passthruEndY_val_empty_n;
output   passthruEndY_val_read;
input  [2:0] passthruEndY_val_num_data_valid;
input  [2:0] passthruEndY_val_fifo_cap;
input  [7:0] enableInput_val_dout;
input   enableInput_val_empty_n;
output   enableInput_val_read;
input  [2:0] enableInput_val_num_data_valid;
input  [2:0] enableInput_val_fifo_cap;
input  [7:0] patternId_val_dout;
input   patternId_val_empty_n;
output   patternId_val_read;
input  [2:0] patternId_val_num_data_valid;
input  [2:0] patternId_val_fifo_cap;
input  [15:0] ZplateHorContStart_val_dout;
input   ZplateHorContStart_val_empty_n;
output   ZplateHorContStart_val_read;
input  [2:0] ZplateHorContStart_val_num_data_valid;
input  [2:0] ZplateHorContStart_val_fifo_cap;
input  [15:0] ZplateHorContDelta_val_dout;
input   ZplateHorContDelta_val_empty_n;
output   ZplateHorContDelta_val_read;
input  [2:0] ZplateHorContDelta_val_num_data_valid;
input  [2:0] ZplateHorContDelta_val_fifo_cap;
input  [15:0] ZplateVerContStart_val_dout;
input   ZplateVerContStart_val_empty_n;
output   ZplateVerContStart_val_read;
input  [2:0] ZplateVerContStart_val_num_data_valid;
input  [2:0] ZplateVerContStart_val_fifo_cap;
input  [15:0] ZplateVerContDelta_val_dout;
input   ZplateVerContDelta_val_empty_n;
output   ZplateVerContDelta_val_read;
input  [2:0] ZplateVerContDelta_val_num_data_valid;
input  [2:0] ZplateVerContDelta_val_fifo_cap;
input  [7:0] dpDynamicRange_val_dout;
input   dpDynamicRange_val_empty_n;
output   dpDynamicRange_val_read;
input  [2:0] dpDynamicRange_val_num_data_valid;
input  [2:0] dpDynamicRange_val_fifo_cap;
input  [7:0] dpYUVCoef_val_dout;
input   dpYUVCoef_val_empty_n;
output   dpYUVCoef_val_read;
input  [2:0] dpYUVCoef_val_num_data_valid;
input  [2:0] dpYUVCoef_val_fifo_cap;
input  [7:0] motionSpeed_val_dout;
input   motionSpeed_val_empty_n;
output   motionSpeed_val_read;
input  [2:0] motionSpeed_val_num_data_valid;
input  [2:0] motionSpeed_val_fifo_cap;
input  [7:0] colorFormat_val_dout;
input   colorFormat_val_empty_n;
output   colorFormat_val_read;
input  [2:0] colorFormat_val_num_data_valid;
input  [2:0] colorFormat_val_fifo_cap;
output  [29:0] bckgndYUV_din;
input   bckgndYUV_full_n;
output   bckgndYUV_write;
input  [4:0] bckgndYUV_num_data_valid;
input  [4:0] bckgndYUV_fifo_cap;
output  [15:0] height_val5_c3_din;
input   height_val5_c3_full_n;
output   height_val5_c3_write;
input  [2:0] height_val5_c3_num_data_valid;
input  [2:0] height_val5_c3_fifo_cap;
output  [15:0] width_val10_c5_din;
input   width_val10_c5_full_n;
output   width_val10_c5_write;
input  [2:0] width_val10_c5_num_data_valid;
input  [2:0] width_val10_c5_fifo_cap;
output  [7:0] motionSpeed_val23_c_din;
input   motionSpeed_val23_c_full_n;
output   motionSpeed_val23_c_write;
input  [2:0] motionSpeed_val23_c_num_data_valid;
input  [2:0] motionSpeed_val23_c_fifo_cap;
output  [7:0] colorFormat_val27_c8_din;
input   colorFormat_val27_c8_full_n;
output   colorFormat_val27_c8_write;
input  [2:0] colorFormat_val27_c8_num_data_valid;
input  [2:0] colorFormat_val27_c8_fifo_cap;
input  [31:0] s;

reg ap_done;
reg ap_idle;
reg ap_ready;
reg height_val_read;
reg width_val_read;
reg passthruStartX_val_read;
reg passthruStartY_val_read;
reg passthruEndX_val_read;
reg passthruEndY_val_read;
reg enableInput_val_read;
reg patternId_val_read;
reg ZplateHorContStart_val_read;
reg ZplateHorContDelta_val_read;
reg ZplateVerContStart_val_read;
reg ZplateVerContDelta_val_read;
reg dpDynamicRange_val_read;
reg dpYUVCoef_val_read;
reg motionSpeed_val_read;
reg colorFormat_val_read;
reg height_val5_c3_write;
reg width_val10_c5_write;
reg motionSpeed_val23_c_write;
reg colorFormat_val27_c8_write;

reg    ap_done_reg;
(* fsm_encoding = "none" *) reg   [5:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
reg   [9:0] rampStart;
reg   [15:0] rampVal_1;
reg   [9:0] rampVal;
reg   [7:0] tpgPatternColorBars_unsigned_short_unsigned_short_unsigned_char_int_hBarSel;
reg   [15:0] zonePlateVAddr;
reg   [2:0] vBarSel;
reg   [2:0] tpgPatternTartanColorBars_unsigned_short_unsigned_short_unsigned_short_unsign_1;
reg   [15:0] hdata;
reg   [7:0] vBarSel_2;
reg   [2:0] tpgPatternCheckerBoard_unsigned_short_unsigned_short_unsigned_short_unsigned_1;
reg   [15:0] rampVal_2;
reg   [0:0] vBarSel_1;
reg   [2:0] tpgPatternDPColorSquare_unsigned_short_unsigned_short_unsigned_char_unsigned_1;
reg    height_val_blk_n;
reg    width_val_blk_n;
reg    passthruStartX_val_blk_n;
reg    passthruStartY_val_blk_n;
reg    passthruEndX_val_blk_n;
reg    passthruEndY_val_blk_n;
reg    enableInput_val_blk_n;
reg    patternId_val_blk_n;
reg    ZplateHorContStart_val_blk_n;
reg    ZplateHorContDelta_val_blk_n;
reg    ZplateVerContStart_val_blk_n;
reg    ZplateVerContDelta_val_blk_n;
reg    dpDynamicRange_val_blk_n;
reg    dpYUVCoef_val_blk_n;
reg    motionSpeed_val_blk_n;
reg    colorFormat_val_blk_n;
reg    height_val5_c3_blk_n;
reg    width_val10_c5_blk_n;
reg    motionSpeed_val23_c_blk_n;
reg    colorFormat_val27_c8_blk_n;
reg   [7:0] dpYUVCoef_val_read_reg_1369;
reg    ap_block_state1;
reg   [7:0] dpDynamicRange_val_read_reg_1374;
reg   [15:0] ZplateVerContDelta_val_read_reg_1379;
reg   [15:0] ZplateVerContStart_val_read_reg_1384;
reg   [15:0] ZplateHorContDelta_val_read_reg_1389;
reg   [15:0] ZplateHorContStart_val_read_reg_1394;
reg   [7:0] colorFormatLocal_reg_1399;
reg   [7:0] motionSpeed_val_read_reg_1406;
reg   [7:0] patternId_val_read_reg_1411;
reg   [7:0] enableInput_val_read_reg_1416;
reg   [15:0] passthruEndY_val_read_reg_1421;
reg   [15:0] passthruEndX_val_read_reg_1426;
reg   [15:0] passthruStartY_val_read_reg_1431;
reg   [15:0] passthruStartX_val_read_reg_1436;
reg   [15:0] loopWidth_reg_1441;
reg   [15:0] loopHeight_reg_1447;
wire   [13:0] empty_fu_733_p1;
reg   [13:0] empty_reg_1453;
wire   [0:0] icmp_fu_757_p2;
reg   [0:0] icmp_reg_1459;
reg   [9:0] tmp_1_reg_1464;
wire   [9:0] conv2_i_i10_i267_fu_915_p3;
reg   [9:0] conv2_i_i10_i267_reg_1469;
wire    ap_CS_fsm_state2;
wire   [2:0] conv2_i_i_i_cast_cast_fu_923_p3;
reg   [2:0] conv2_i_i_i_cast_cast_reg_1474;
wire   [9:0] conv2_i_i10_i270_fu_931_p3;
reg   [9:0] conv2_i_i10_i270_reg_1479;
wire   [6:0] conv2_i_i_i271_cast_cast_fu_939_p3;
reg   [6:0] conv2_i_i_i271_cast_cast_reg_1484;
wire   [4:0] conv2_i_i10_i285_cast_cast_cast_cast_fu_947_p3;
reg   [4:0] conv2_i_i10_i285_cast_cast_cast_cast_reg_1489;
wire   [9:0] conv2_i_i_i286_fu_955_p3;
reg   [9:0] conv2_i_i_i286_reg_1494;
wire   [9:0] conv2_i_i_i299_fu_963_p3;
reg   [9:0] conv2_i_i_i299_reg_1499;
wire   [9:0] conv2_i_i_i313_fu_971_p3;
reg   [9:0] conv2_i_i_i313_reg_1504;
reg   [10:0] barWidth_reg_1509;
wire   [9:0] barWidthMinSamples_fu_1012_p2;
reg   [9:0] barWidthMinSamples_reg_1515;
wire   [10:0] sub_i_i_i_fu_1024_p2;
reg   [10:0] sub_i_i_i_reg_1520;
wire   [16:0] sub35_i_fu_1030_p2;
reg   [16:0] sub35_i_reg_1525;
wire   [16:0] sub10_i_fu_1036_p2;
reg   [16:0] sub10_i_reg_1530;
reg   [9:0] rampStart_load_reg_1535;
wire   [9:0] outpix_10_fu_1046_p3;
reg   [9:0] outpix_10_reg_1541;
wire   [7:0] empty_125_fu_1058_p1;
reg   [7:0] empty_125_reg_1546;
wire   [15:0] shl_i_fu_1066_p3;
reg   [15:0] shl_i_reg_1551;
wire   [0:0] cmp136_i_fu_1074_p2;
reg   [0:0] cmp136_i_reg_1556;
reg   [15:0] y_3_reg_1561;
wire    ap_CS_fsm_state3;
reg   [9:0] outpix_load_reg_1571;
reg   [9:0] outpix_1_load_reg_1576;
reg   [9:0] outpix_2_load_reg_1581;
wire   [0:0] ult_fu_1106_p2;
reg   [0:0] ult_reg_1586;
wire   [0:0] ult348_fu_1111_p2;
reg   [0:0] ult348_reg_1591;
wire   [0:0] cmp12_i_fu_1120_p2;
reg   [0:0] cmp12_i_reg_1596;
wire   [0:0] cmp11_i_fu_1126_p2;
reg   [0:0] cmp11_i_reg_1601;
wire   [9:0] add_i410_fu_1131_p2;
reg   [9:0] add_i410_reg_1606;
wire   [0:0] rev_fu_1182_p2;
reg   [0:0] rev_reg_1611;
wire    ap_CS_fsm_state4;
wire   [0:0] rev349_fu_1188_p2;
reg   [0:0] rev349_reg_1616;
reg   [1:0] colorSel_reg_1621;
reg   [0:0] tmp_35_reg_1626;
wire    grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_542_ap_start;
wire    grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_542_ap_done;
wire    grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_542_ap_idle;
wire    grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_542_ap_ready;
wire    grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_542_srcYUV_read;
wire   [29:0] grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_542_bckgndYUV_din;
wire    grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_542_bckgndYUV_write;
wire   [0:0] grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_542_rampVal_3_flag_1_out;
wire    grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_542_rampVal_3_flag_1_out_ap_vld;
wire   [15:0] grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_542_rampVal_3_new_1_out;
wire    grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_542_rampVal_3_new_1_out_ap_vld;
wire   [15:0] grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_542_rampVal_3_loc_1_out_o;
wire    grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_542_rampVal_3_loc_1_out_o_ap_vld;
wire   [15:0] grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_542_rampVal_loc_1_out_o;
wire    grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_542_rampVal_loc_1_out_o_ap_vld;
wire   [7:0] grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_542_tpgPatternColorBars_unsigned_short_unsigned_short_unsigned_char_int_hBarSel_l_2_out_o;
wire    grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_542_tpgPatternColorBars_unsigned_short_unsigned_short_unsigned_char_int_hBarSel_l_2_out_o_ap_vld;
wire   [15:0] grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_542_zonePlateVAddr_loc_1_out_o;
wire    grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_542_zonePlateVAddr_loc_1_out_o_ap_vld;
wire   [7:0] grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_542_vBarSel_loc_1_out_o;
wire    grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_542_vBarSel_loc_1_out_o_ap_vld;
wire   [7:0] grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_542_tpgPatternTartanColorBars_unsigned_short_unsigned_short_unsigned_short_unsign_4_out_o;
wire    grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_542_tpgPatternTartanColorBars_unsigned_short_unsigned_short_unsigned_short_unsign_4_out_o_ap_vld;
wire   [0:0] grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_542_hdata_flag_1_out;
wire    grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_542_hdata_flag_1_out_ap_vld;
wire   [15:0] grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_542_hdata_new_1_out;
wire    grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_542_hdata_new_1_out_ap_vld;
wire   [15:0] grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_542_hdata_loc_1_out_o;
wire    grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_542_hdata_loc_1_out_o_ap_vld;
wire   [7:0] grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_542_vBarSel_2_loc_1_out_o;
wire    grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_542_vBarSel_2_loc_1_out_o_ap_vld;
wire   [7:0] grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_542_tpgPatternCheckerBoard_unsigned_short_unsigned_short_unsigned_short_unsigned_4_out_o;
wire    grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_542_tpgPatternCheckerBoard_unsigned_short_unsigned_short_unsigned_short_unsigned_4_out_o_ap_vld;
wire   [0:0] grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_542_rampVal_2_flag_1_out;
wire    grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_542_rampVal_2_flag_1_out_ap_vld;
wire   [15:0] grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_542_rampVal_2_new_1_out;
wire    grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_542_rampVal_2_new_1_out_ap_vld;
wire   [15:0] grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_542_rampVal_2_loc_1_out_o;
wire    grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_542_rampVal_2_loc_1_out_o_ap_vld;
wire   [7:0] grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_542_vBarSel_3_loc_1_out_o;
wire    grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_542_vBarSel_3_loc_1_out_o_ap_vld;
wire   [7:0] grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_542_tpgPatternDPColorSquare_unsigned_short_unsigned_short_unsigned_char_unsigned_4_out_o;
wire    grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_542_tpgPatternDPColorSquare_unsigned_short_unsigned_short_unsigned_char_unsigned_4_out_o_ap_vld;
wire   [9:0] grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_542_outpix_5_out;
wire    grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_542_outpix_5_out_ap_vld;
wire   [9:0] grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_542_outpix_4_out;
wire    grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_542_outpix_4_out_ap_vld;
wire   [9:0] grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_542_outpix_3_out;
wire    grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_542_outpix_3_out_ap_vld;
wire   [9:0] grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_542_p_0_0_0247_out_o;
wire    grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_542_p_0_0_0247_out_o_ap_vld;
wire   [9:0] grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_542_p_0_0_09245_out_o;
wire    grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_542_p_0_0_09245_out_o_ap_vld;
wire   [9:0] grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_542_p_0_0_010243_out_o;
wire    grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_542_p_0_0_010243_out_o_ap_vld;
wire   [9:0] grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_542_rampVal;
wire    grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_542_rampVal_ap_vld;
wire   [7:0] grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_542_tpgPatternColorBars_unsigned_short_unsigned_short_unsigned_char_int_hBarSel;
wire    grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_542_tpgPatternColorBars_unsigned_short_unsigned_short_unsigned_char_int_hBarSel_ap_vld;
wire   [15:0] grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_542_zonePlateVAddr;
wire    grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_542_zonePlateVAddr_ap_vld;
wire   [2:0] grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_542_tpgPatternTartanColorBars_unsigned_short_unsigned_short_unsigned_short_unsign_1;
wire    grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_542_tpgPatternTartanColorBars_unsigned_short_unsigned_short_unsigned_short_unsign_1_ap_vld;
wire   [2:0] grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_542_vBarSel;
wire    grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_542_vBarSel_ap_vld;
wire   [2:0] grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_542_tpgPatternCheckerBoard_unsigned_short_unsigned_short_unsigned_short_unsigned_1;
wire    grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_542_tpgPatternCheckerBoard_unsigned_short_unsigned_short_unsigned_short_unsigned_1_ap_vld;
wire   [7:0] grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_542_vBarSel_2;
wire    grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_542_vBarSel_2_ap_vld;
wire   [2:0] grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_542_tpgPatternDPColorSquare_unsigned_short_unsigned_short_unsigned_char_unsigned_1;
wire    grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_542_tpgPatternDPColorSquare_unsigned_short_unsigned_short_unsigned_char_unsigned_1_ap_vld;
wire   [0:0] grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_542_vBarSel_1;
wire    grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_542_vBarSel_1_ap_vld;
wire   [0:0] ap_phi_mux_rampVal_3_flag_0_phi_fu_510_p4;
reg   [0:0] rampVal_3_flag_0_reg_506;
wire    ap_CS_fsm_state6;
wire   [0:0] ap_phi_mux_hdata_flag_0_phi_fu_522_p4;
reg   [0:0] hdata_flag_0_reg_518;
wire   [0:0] ap_phi_mux_rampVal_2_flag_0_phi_fu_534_p4;
reg   [0:0] rampVal_2_flag_0_reg_530;
reg    grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_542_ap_start_reg;
wire    ap_CS_fsm_state5;
reg   [15:0] rampVal_3_new_0_fu_362;
reg   [15:0] rampVal_3_loc_0_fu_358;
reg   [15:0] rampVal_loc_0_fu_354;
reg   [7:0] tpgPatternColorBars_unsigned_short_unsigned_short_unsigned_char_int_hBarSel_l_1_fu_350;
reg   [15:0] zonePlateVAddr_loc_0_fu_346;
reg   [7:0] vBarSel_loc_0_fu_342;
reg   [7:0] tpgPatternTartanColorBars_unsigned_short_unsigned_short_unsigned_short_unsign_3_fu_338;
reg   [15:0] hdata_new_0_fu_334;
reg   [15:0] hdata_loc_0_fu_330;
reg   [7:0] vBarSel_2_loc_0_fu_326;
reg   [7:0] tpgPatternCheckerBoard_unsigned_short_unsigned_short_unsigned_short_unsigned_3_fu_322;
reg   [15:0] rampVal_2_new_0_fu_318;
reg   [15:0] rampVal_2_loc_0_fu_314;
reg   [7:0] vBarSel_3_loc_0_fu_310;
reg   [7:0] tpgPatternDPColorSquare_unsigned_short_unsigned_short_unsigned_char_unsigned_3_fu_306;
reg   [9:0] outpix_2_fu_302;
reg   [9:0] outpix_1_fu_298;
reg   [9:0] outpix_fu_294;
reg   [9:0] p_0_0_0248_lcssa257_fu_286;
reg   [9:0] p_0_0_09246_lcssa254_fu_282;
reg   [9:0] p_0_0_010244_lcssa251_fu_278;
wire   [9:0] add_ln750_fu_1144_p2;
wire   [0:0] icmp_ln563_fu_1082_p2;
reg   [15:0] y_fu_290;
wire   [15:0] add_ln563_fu_1087_p2;
wire   [7:0] zext_ln563_1_fu_841_p1;
wire   [7:0] zext_ln1775_fu_833_p1;
wire   [7:0] zext_ln563_fu_821_p1;
wire   [7:0] zext_ln1545_fu_805_p1;
wire   [7:0] zext_ln1412_fu_797_p1;
wire   [15:0] zext_ln1257_fu_781_p1;
wire   [13:0] empty_124_fu_737_p1;
wire   [6:0] tmp_fu_747_p4;
wire   [13:0] add5_i_fu_741_p2;
wire   [0:0] cmp2_i_fu_910_p2;
wire   [13:0] add_i_fu_982_p2;
wire   [13:0] add2_i_fu_997_p2;
wire   [9:0] p_cast_fu_1002_p4;
wire   [10:0] barHeight_cast_fu_1021_p1;
wire   [16:0] width_val_cast14_fu_979_p1;
wire   [16:0] height_val_cast15_fu_1018_p1;
wire   [7:0] empty_126_fu_1062_p1;
wire   [16:0] zext_ln563_2_fu_1102_p1;
wire   [9:0] empty_127_fu_1116_p1;
wire   [9:0] zext_ln750_fu_1141_p1;
reg   [5:0] ap_NS_fsm;
reg    ap_ST_fsm_state1_blk;
wire    ap_ST_fsm_state2_blk;
wire    ap_ST_fsm_state3_blk;
wire    ap_ST_fsm_state4_blk;
reg    ap_ST_fsm_state5_blk;
wire    ap_ST_fsm_state6_blk;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_done_reg = 1'b0;
#0 ap_CS_fsm = 6'd1;
#0 rampStart = 10'd0;
#0 rampVal_1 = 16'd0;
#0 rampVal = 10'd0;
#0 tpgPatternColorBars_unsigned_short_unsigned_short_unsigned_char_int_hBarSel = 8'd0;
#0 zonePlateVAddr = 16'd0;
#0 vBarSel = 3'd0;
#0 tpgPatternTartanColorBars_unsigned_short_unsigned_short_unsigned_short_unsign_1 = 3'd0;
#0 hdata = 16'd0;
#0 vBarSel_2 = 8'd0;
#0 tpgPatternCheckerBoard_unsigned_short_unsigned_short_unsigned_short_unsigned_1 = 3'd0;
#0 rampVal_2 = 16'd0;
#0 vBarSel_1 = 1'd0;
#0 tpgPatternDPColorSquare_unsigned_short_unsigned_short_unsigned_char_unsigned_1 = 3'd0;
#0 grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_542_ap_start_reg = 1'b0;
#0 rampVal_3_loc_0_fu_358 = 16'd0;
#0 rampVal_loc_0_fu_354 = 16'd0;
#0 tpgPatternColorBars_unsigned_short_unsigned_short_unsigned_char_int_hBarSel_l_1_fu_350 = 8'd0;
#0 zonePlateVAddr_loc_0_fu_346 = 16'd0;
#0 vBarSel_loc_0_fu_342 = 8'd0;
#0 tpgPatternTartanColorBars_unsigned_short_unsigned_short_unsigned_short_unsign_3_fu_338 = 8'd0;
#0 hdata_loc_0_fu_330 = 16'd0;
#0 vBarSel_2_loc_0_fu_326 = 8'd0;
#0 tpgPatternCheckerBoard_unsigned_short_unsigned_short_unsigned_short_unsigned_3_fu_322 = 8'd0;
#0 rampVal_2_loc_0_fu_314 = 16'd0;
#0 vBarSel_3_loc_0_fu_310 = 8'd0;
#0 tpgPatternDPColorSquare_unsigned_short_unsigned_short_unsigned_char_unsigned_3_fu_306 = 8'd0;
#0 y_fu_290 = 16'd0;
end

system_v_tpg_0_0_tpgBackground_Pipeline_VITIS_LOOP_565_2 grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_542(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_542_ap_start),
    .ap_done(grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_542_ap_done),
    .ap_idle(grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_542_ap_idle),
    .ap_ready(grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_542_ap_ready),
    .srcYUV_dout(srcYUV_dout),
    .srcYUV_empty_n(srcYUV_empty_n),
    .srcYUV_read(grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_542_srcYUV_read),
    .srcYUV_num_data_valid(5'd0),
    .srcYUV_fifo_cap(5'd0),
    .bckgndYUV_din(grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_542_bckgndYUV_din),
    .bckgndYUV_full_n(bckgndYUV_full_n),
    .bckgndYUV_write(grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_542_bckgndYUV_write),
    .bckgndYUV_num_data_valid(5'd0),
    .bckgndYUV_fifo_cap(5'd0),
    .rampVal_3_flag_0(rampVal_3_flag_0_reg_506),
    .hdata_flag_0(hdata_flag_0_reg_518),
    .rampVal_2_flag_0(rampVal_2_flag_0_reg_530),
    .outpix_2(outpix_2_load_reg_1581),
    .outpix_1(outpix_1_load_reg_1576),
    .outpix(outpix_load_reg_1571),
    .loopWidth(loopWidth_reg_1441),
    .conv2_i_i_i313(conv2_i_i_i313_reg_1504),
    .conv2_i_i_i299(conv2_i_i_i299_reg_1499),
    .conv2_i_i_i286(conv2_i_i_i286_reg_1494),
    .conv2_i_i_i271_cast_cast(conv2_i_i_i271_cast_cast_reg_1484),
    .conv2_i_i_i_cast_cast(conv2_i_i_i_cast_cast_reg_1474),
    .outpix_10(outpix_10_reg_1541),
    .conv2_i_i10_i285_cast_cast_cast_cast(conv2_i_i10_i285_cast_cast_cast_cast_reg_1489),
    .conv2_i_i10_i270(conv2_i_i10_i270_reg_1479),
    .conv2_i_i10_i267(conv2_i_i10_i267_reg_1469),
    .rampStart_1(rampStart_load_reg_1535),
    .patternId_val_load(patternId_val_read_reg_1411),
    .Zplate_Hor_Control_Start(ZplateHorContStart_val_read_reg_1394),
    .outpix_9_cast(rampStart_load_reg_1535),
    .y(y_3_reg_1561),
    .colorFormatLocal(colorFormatLocal_reg_1399),
    .empty_48(empty_125_reg_1546),
    .barWidth_cast(barWidth_reg_1509),
    .barWidth(barWidth_reg_1509),
    .shl_i(shl_i_reg_1551),
    .Zplate_Hor_Control_Delta(ZplateHorContDelta_val_read_reg_1389),
    .Zplate_Ver_Control_Start(ZplateVerContStart_val_read_reg_1384),
    .cmp12_i(cmp12_i_reg_1596),
    .Zplate_Ver_Control_Delta(ZplateVerContDelta_val_read_reg_1379),
    .sub_i_i_i(sub_i_i_i_reg_1520),
    .barWidthMinSamples(barWidthMinSamples_reg_1515),
    .cmp11_i(cmp11_i_reg_1601),
    .sub35_i(sub35_i_reg_1525),
    .add_i410(add_i410_reg_1606),
    .icmp(icmp_reg_1459),
    .empty(tmp_35_reg_1626),
    .cmp136_i(cmp136_i_reg_1556),
    .passthruStartX_val_load(passthruStartX_val_read_reg_1436),
    .passthruEndX_val_load(passthruEndX_val_read_reg_1426),
    .rev(rev_reg_1611),
    .rev304(rev349_reg_1616),
    .dpYUVCoef(dpYUVCoef_val_read_reg_1369),
    .dpDynamicRange(dpDynamicRange_val_read_reg_1374),
    .colorSel(colorSel_reg_1621),
    .enableInput_val_load(enableInput_val_read_reg_1416),
    .rampVal_3_flag_1_out(grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_542_rampVal_3_flag_1_out),
    .rampVal_3_flag_1_out_ap_vld(grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_542_rampVal_3_flag_1_out_ap_vld),
    .rampVal_3_new_1_out(grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_542_rampVal_3_new_1_out),
    .rampVal_3_new_1_out_ap_vld(grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_542_rampVal_3_new_1_out_ap_vld),
    .rampVal_3_loc_1_out_i(rampVal_3_loc_0_fu_358),
    .rampVal_3_loc_1_out_o(grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_542_rampVal_3_loc_1_out_o),
    .rampVal_3_loc_1_out_o_ap_vld(grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_542_rampVal_3_loc_1_out_o_ap_vld),
    .rampVal_loc_1_out_i(rampVal_loc_0_fu_354),
    .rampVal_loc_1_out_o(grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_542_rampVal_loc_1_out_o),
    .rampVal_loc_1_out_o_ap_vld(grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_542_rampVal_loc_1_out_o_ap_vld),
    .tpgPatternColorBars_unsigned_short_unsigned_short_unsigned_char_int_hBarSel_l_2_out_i(tpgPatternColorBars_unsigned_short_unsigned_short_unsigned_char_int_hBarSel_l_1_fu_350),
    .tpgPatternColorBars_unsigned_short_unsigned_short_unsigned_char_int_hBarSel_l_2_out_o(grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_542_tpgPatternColorBars_unsigned_short_unsigned_short_unsigned_char_int_hBarSel_l_2_out_o),
    .tpgPatternColorBars_unsigned_short_unsigned_short_unsigned_char_int_hBarSel_l_2_out_o_ap_vld(grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_542_tpgPatternColorBars_unsigned_short_unsigned_short_unsigned_char_int_hBarSel_l_2_out_o_ap_vld),
    .zonePlateVAddr_loc_1_out_i(zonePlateVAddr_loc_0_fu_346),
    .zonePlateVAddr_loc_1_out_o(grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_542_zonePlateVAddr_loc_1_out_o),
    .zonePlateVAddr_loc_1_out_o_ap_vld(grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_542_zonePlateVAddr_loc_1_out_o_ap_vld),
    .vBarSel_loc_1_out_i(vBarSel_loc_0_fu_342),
    .vBarSel_loc_1_out_o(grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_542_vBarSel_loc_1_out_o),
    .vBarSel_loc_1_out_o_ap_vld(grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_542_vBarSel_loc_1_out_o_ap_vld),
    .tpgPatternTartanColorBars_unsigned_short_unsigned_short_unsigned_short_unsign_4_out_i(tpgPatternTartanColorBars_unsigned_short_unsigned_short_unsigned_short_unsign_3_fu_338),
    .tpgPatternTartanColorBars_unsigned_short_unsigned_short_unsigned_short_unsign_4_out_o(grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_542_tpgPatternTartanColorBars_unsigned_short_unsigned_short_unsigned_short_unsign_4_out_o),
    .tpgPatternTartanColorBars_unsigned_short_unsigned_short_unsigned_short_unsign_4_out_o_ap_vld(grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_542_tpgPatternTartanColorBars_unsigned_short_unsigned_short_unsigned_short_unsign_4_out_o_ap_vld),
    .hdata_flag_1_out(grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_542_hdata_flag_1_out),
    .hdata_flag_1_out_ap_vld(grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_542_hdata_flag_1_out_ap_vld),
    .hdata_new_1_out(grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_542_hdata_new_1_out),
    .hdata_new_1_out_ap_vld(grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_542_hdata_new_1_out_ap_vld),
    .hdata_loc_1_out_i(hdata_loc_0_fu_330),
    .hdata_loc_1_out_o(grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_542_hdata_loc_1_out_o),
    .hdata_loc_1_out_o_ap_vld(grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_542_hdata_loc_1_out_o_ap_vld),
    .vBarSel_2_loc_1_out_i(vBarSel_2_loc_0_fu_326),
    .vBarSel_2_loc_1_out_o(grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_542_vBarSel_2_loc_1_out_o),
    .vBarSel_2_loc_1_out_o_ap_vld(grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_542_vBarSel_2_loc_1_out_o_ap_vld),
    .tpgPatternCheckerBoard_unsigned_short_unsigned_short_unsigned_short_unsigned_4_out_i(tpgPatternCheckerBoard_unsigned_short_unsigned_short_unsigned_short_unsigned_3_fu_322),
    .tpgPatternCheckerBoard_unsigned_short_unsigned_short_unsigned_short_unsigned_4_out_o(grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_542_tpgPatternCheckerBoard_unsigned_short_unsigned_short_unsigned_short_unsigned_4_out_o),
    .tpgPatternCheckerBoard_unsigned_short_unsigned_short_unsigned_short_unsigned_4_out_o_ap_vld(grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_542_tpgPatternCheckerBoard_unsigned_short_unsigned_short_unsigned_short_unsigned_4_out_o_ap_vld),
    .rampVal_2_flag_1_out(grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_542_rampVal_2_flag_1_out),
    .rampVal_2_flag_1_out_ap_vld(grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_542_rampVal_2_flag_1_out_ap_vld),
    .rampVal_2_new_1_out(grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_542_rampVal_2_new_1_out),
    .rampVal_2_new_1_out_ap_vld(grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_542_rampVal_2_new_1_out_ap_vld),
    .rampVal_2_loc_1_out_i(rampVal_2_loc_0_fu_314),
    .rampVal_2_loc_1_out_o(grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_542_rampVal_2_loc_1_out_o),
    .rampVal_2_loc_1_out_o_ap_vld(grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_542_rampVal_2_loc_1_out_o_ap_vld),
    .vBarSel_3_loc_1_out_i(vBarSel_3_loc_0_fu_310),
    .vBarSel_3_loc_1_out_o(grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_542_vBarSel_3_loc_1_out_o),
    .vBarSel_3_loc_1_out_o_ap_vld(grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_542_vBarSel_3_loc_1_out_o_ap_vld),
    .tpgPatternDPColorSquare_unsigned_short_unsigned_short_unsigned_char_unsigned_4_out_i(tpgPatternDPColorSquare_unsigned_short_unsigned_short_unsigned_char_unsigned_3_fu_306),
    .tpgPatternDPColorSquare_unsigned_short_unsigned_short_unsigned_char_unsigned_4_out_o(grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_542_tpgPatternDPColorSquare_unsigned_short_unsigned_short_unsigned_char_unsigned_4_out_o),
    .tpgPatternDPColorSquare_unsigned_short_unsigned_short_unsigned_char_unsigned_4_out_o_ap_vld(grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_542_tpgPatternDPColorSquare_unsigned_short_unsigned_short_unsigned_char_unsigned_4_out_o_ap_vld),
    .outpix_5_out(grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_542_outpix_5_out),
    .outpix_5_out_ap_vld(grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_542_outpix_5_out_ap_vld),
    .outpix_4_out(grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_542_outpix_4_out),
    .outpix_4_out_ap_vld(grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_542_outpix_4_out_ap_vld),
    .outpix_3_out(grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_542_outpix_3_out),
    .outpix_3_out_ap_vld(grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_542_outpix_3_out_ap_vld),
    .p_0_0_0247_out_i(p_0_0_0248_lcssa257_fu_286),
    .p_0_0_0247_out_o(grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_542_p_0_0_0247_out_o),
    .p_0_0_0247_out_o_ap_vld(grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_542_p_0_0_0247_out_o_ap_vld),
    .p_0_0_09245_out_i(p_0_0_09246_lcssa254_fu_282),
    .p_0_0_09245_out_o(grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_542_p_0_0_09245_out_o),
    .p_0_0_09245_out_o_ap_vld(grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_542_p_0_0_09245_out_o_ap_vld),
    .p_0_0_010243_out_i(p_0_0_010244_lcssa251_fu_278),
    .p_0_0_010243_out_o(grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_542_p_0_0_010243_out_o),
    .p_0_0_010243_out_o_ap_vld(grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_542_p_0_0_010243_out_o_ap_vld),
    .rampVal(grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_542_rampVal),
    .rampVal_ap_vld(grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_542_rampVal_ap_vld),
    .tpgPatternColorBars_unsigned_short_unsigned_short_unsigned_char_int_hBarSel(grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_542_tpgPatternColorBars_unsigned_short_unsigned_short_unsigned_char_int_hBarSel),
    .tpgPatternColorBars_unsigned_short_unsigned_short_unsigned_char_int_hBarSel_ap_vld(grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_542_tpgPatternColorBars_unsigned_short_unsigned_short_unsigned_char_int_hBarSel_ap_vld),
    .zonePlateVAddr(grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_542_zonePlateVAddr),
    .zonePlateVAddr_ap_vld(grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_542_zonePlateVAddr_ap_vld),
    .tpgPatternTartanColorBars_unsigned_short_unsigned_short_unsigned_short_unsign_1(grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_542_tpgPatternTartanColorBars_unsigned_short_unsigned_short_unsigned_short_unsign_1),
    .tpgPatternTartanColorBars_unsigned_short_unsigned_short_unsigned_short_unsign_1_ap_vld(grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_542_tpgPatternTartanColorBars_unsigned_short_unsigned_short_unsigned_short_unsign_1_ap_vld),
    .vBarSel(grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_542_vBarSel),
    .vBarSel_ap_vld(grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_542_vBarSel_ap_vld),
    .tpgPatternCheckerBoard_unsigned_short_unsigned_short_unsigned_short_unsigned_1(grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_542_tpgPatternCheckerBoard_unsigned_short_unsigned_short_unsigned_short_unsigned_1),
    .tpgPatternCheckerBoard_unsigned_short_unsigned_short_unsigned_short_unsigned_1_ap_vld(grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_542_tpgPatternCheckerBoard_unsigned_short_unsigned_short_unsigned_short_unsigned_1_ap_vld),
    .vBarSel_2(grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_542_vBarSel_2),
    .vBarSel_2_ap_vld(grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_542_vBarSel_2_ap_vld),
    .tpgPatternDPColorSquare_unsigned_short_unsigned_short_unsigned_char_unsigned_1(grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_542_tpgPatternDPColorSquare_unsigned_short_unsigned_short_unsigned_char_unsigned_1),
    .tpgPatternDPColorSquare_unsigned_short_unsigned_short_unsigned_char_unsigned_1_ap_vld(grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_542_tpgPatternDPColorSquare_unsigned_short_unsigned_short_unsigned_char_unsigned_1_ap_vld),
    .vBarSel_1(grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_542_vBarSel_1),
    .vBarSel_1_ap_vld(grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_542_vBarSel_1_ap_vld)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((icmp_ln563_fu_1082_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state3))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_542_ap_start_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_state4)) begin
            grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_542_ap_start_reg <= 1'b1;
        end else if ((grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_542_ap_ready == 1'b1)) begin
            grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_542_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state6)) begin
        hdata_flag_0_reg_518 <= grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_542_hdata_flag_1_out;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        hdata_flag_0_reg_518 <= 1'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_state1) & (1'b1 == ap_CS_fsm_state1))) begin
        hdata_loc_0_fu_330 <= hdata;
    end else if (((grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_542_hdata_loc_1_out_o_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state5))) begin
        hdata_loc_0_fu_330 <= grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_542_hdata_loc_1_out_o;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state6)) begin
        rampVal_2_flag_0_reg_530 <= grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_542_rampVal_2_flag_1_out;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        rampVal_2_flag_0_reg_530 <= 1'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_state1) & (1'b1 == ap_CS_fsm_state1))) begin
        rampVal_2_loc_0_fu_314 <= rampVal_2;
    end else if (((grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_542_rampVal_2_loc_1_out_o_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state5))) begin
        rampVal_2_loc_0_fu_314 <= grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_542_rampVal_2_loc_1_out_o;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state6)) begin
        rampVal_3_flag_0_reg_506 <= grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_542_rampVal_3_flag_1_out;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        rampVal_3_flag_0_reg_506 <= 1'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_state1) & (1'b1 == ap_CS_fsm_state1))) begin
        rampVal_3_loc_0_fu_358 <= rampVal_1;
    end else if (((grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_542_rampVal_3_loc_1_out_o_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state5))) begin
        rampVal_3_loc_0_fu_358 <= grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_542_rampVal_3_loc_1_out_o;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_state1) & (1'b1 == ap_CS_fsm_state1))) begin
        rampVal_loc_0_fu_354 <= zext_ln1257_fu_781_p1;
    end else if (((grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_542_rampVal_loc_1_out_o_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state5))) begin
        rampVal_loc_0_fu_354 <= grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_542_rampVal_loc_1_out_o;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_state1) & (1'b1 == ap_CS_fsm_state1))) begin
        tpgPatternCheckerBoard_unsigned_short_unsigned_short_unsigned_short_unsigned_3_fu_322 <= zext_ln563_fu_821_p1;
    end else if (((grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_542_tpgPatternCheckerBoard_unsigned_short_unsigned_short_unsigned_short_unsigned_4_out_o_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state5))) begin
        tpgPatternCheckerBoard_unsigned_short_unsigned_short_unsigned_short_unsigned_3_fu_322 <= grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_542_tpgPatternCheckerBoard_unsigned_short_unsigned_short_unsigned_short_unsigned_4_out_o;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_state1) & (1'b1 == ap_CS_fsm_state1))) begin
        tpgPatternColorBars_unsigned_short_unsigned_short_unsigned_char_int_hBarSel_l_1_fu_350 <= tpgPatternColorBars_unsigned_short_unsigned_short_unsigned_char_int_hBarSel;
    end else if (((grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_542_tpgPatternColorBars_unsigned_short_unsigned_short_unsigned_char_int_hBarSel_l_2_out_o_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state5))) begin
        tpgPatternColorBars_unsigned_short_unsigned_short_unsigned_char_int_hBarSel_l_1_fu_350 <= grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_542_tpgPatternColorBars_unsigned_short_unsigned_short_unsigned_char_int_hBarSel_l_2_out_o;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_state1) & (1'b1 == ap_CS_fsm_state1))) begin
        tpgPatternDPColorSquare_unsigned_short_unsigned_short_unsigned_char_unsigned_3_fu_306 <= zext_ln563_1_fu_841_p1;
    end else if (((grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_542_tpgPatternDPColorSquare_unsigned_short_unsigned_short_unsigned_char_unsigned_4_out_o_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state5))) begin
        tpgPatternDPColorSquare_unsigned_short_unsigned_short_unsigned_char_unsigned_3_fu_306 <= grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_542_tpgPatternDPColorSquare_unsigned_short_unsigned_short_unsigned_char_unsigned_4_out_o;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_state1) & (1'b1 == ap_CS_fsm_state1))) begin
        tpgPatternTartanColorBars_unsigned_short_unsigned_short_unsigned_short_unsign_3_fu_338 <= zext_ln1545_fu_805_p1;
    end else if (((grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_542_tpgPatternTartanColorBars_unsigned_short_unsigned_short_unsigned_short_unsign_4_out_o_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state5))) begin
        tpgPatternTartanColorBars_unsigned_short_unsigned_short_unsigned_short_unsign_3_fu_338 <= grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_542_tpgPatternTartanColorBars_unsigned_short_unsigned_short_unsigned_short_unsign_4_out_o;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_state1) & (1'b1 == ap_CS_fsm_state1))) begin
        vBarSel_2_loc_0_fu_326 <= vBarSel_2;
    end else if (((grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_542_vBarSel_2_loc_1_out_o_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state5))) begin
        vBarSel_2_loc_0_fu_326 <= grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_542_vBarSel_2_loc_1_out_o;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_state1) & (1'b1 == ap_CS_fsm_state1))) begin
        vBarSel_3_loc_0_fu_310 <= zext_ln1775_fu_833_p1;
    end else if (((grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_542_vBarSel_3_loc_1_out_o_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state5))) begin
        vBarSel_3_loc_0_fu_310 <= grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_542_vBarSel_3_loc_1_out_o;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_state1) & (1'b1 == ap_CS_fsm_state1))) begin
        vBarSel_loc_0_fu_342 <= zext_ln1412_fu_797_p1;
    end else if (((grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_542_vBarSel_loc_1_out_o_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state5))) begin
        vBarSel_loc_0_fu_342 <= grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_542_vBarSel_loc_1_out_o;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_state1) & (1'b1 == ap_CS_fsm_state1))) begin
        y_fu_290 <= 16'd0;
    end else if (((icmp_ln563_fu_1082_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state3))) begin
        y_fu_290 <= add_ln563_fu_1087_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_state1) & (1'b1 == ap_CS_fsm_state1))) begin
        zonePlateVAddr_loc_0_fu_346 <= zonePlateVAddr;
    end else if (((grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_542_zonePlateVAddr_loc_1_out_o_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state5))) begin
        zonePlateVAddr_loc_0_fu_346 <= grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_542_zonePlateVAddr_loc_1_out_o;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_state1) & (1'b1 == ap_CS_fsm_state1))) begin
        ZplateHorContDelta_val_read_reg_1389 <= ZplateHorContDelta_val_dout;
        ZplateHorContStart_val_read_reg_1394 <= ZplateHorContStart_val_dout;
        ZplateVerContDelta_val_read_reg_1379 <= ZplateVerContDelta_val_dout;
        ZplateVerContStart_val_read_reg_1384 <= ZplateVerContStart_val_dout;
        colorFormatLocal_reg_1399 <= colorFormat_val_dout;
        dpDynamicRange_val_read_reg_1374 <= dpDynamicRange_val_dout;
        dpYUVCoef_val_read_reg_1369 <= dpYUVCoef_val_dout;
        empty_reg_1453 <= empty_fu_733_p1;
        enableInput_val_read_reg_1416 <= enableInput_val_dout;
        icmp_reg_1459 <= icmp_fu_757_p2;
        loopHeight_reg_1447 <= height_val_dout;
        loopWidth_reg_1441 <= width_val_dout;
        motionSpeed_val_read_reg_1406 <= motionSpeed_val_dout;
        passthruEndX_val_read_reg_1426 <= passthruEndX_val_dout;
        passthruEndY_val_read_reg_1421 <= passthruEndY_val_dout;
        passthruStartX_val_read_reg_1436 <= passthruStartX_val_dout;
        passthruStartY_val_read_reg_1431 <= passthruStartY_val_dout;
        patternId_val_read_reg_1411 <= patternId_val_dout;
        tmp_1_reg_1464 <= {{add5_i_fu_741_p2[13:4]}};
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        add_i410_reg_1606 <= add_i410_fu_1131_p2;
        cmp11_i_reg_1601 <= cmp11_i_fu_1126_p2;
        cmp12_i_reg_1596 <= cmp12_i_fu_1120_p2;
        outpix_1_load_reg_1576 <= outpix_1_fu_298;
        outpix_2_load_reg_1581 <= outpix_2_fu_302;
        outpix_load_reg_1571 <= outpix_fu_294;
        ult348_reg_1591 <= ult348_fu_1111_p2;
        ult_reg_1586 <= ult_fu_1106_p2;
        y_3_reg_1561 <= y_fu_290;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        barWidthMinSamples_reg_1515 <= barWidthMinSamples_fu_1012_p2;
        barWidth_reg_1509 <= {{add_i_fu_982_p2[13:3]}};
        cmp136_i_reg_1556 <= cmp136_i_fu_1074_p2;
        conv2_i_i10_i267_reg_1469[3 : 0] <= conv2_i_i10_i267_fu_915_p3[3 : 0];
conv2_i_i10_i267_reg_1469[7 : 6] <= conv2_i_i10_i267_fu_915_p3[7 : 6];
conv2_i_i10_i267_reg_1469[9] <= conv2_i_i10_i267_fu_915_p3[9];
        conv2_i_i10_i270_reg_1479[2] <= conv2_i_i10_i270_fu_931_p3[2];
conv2_i_i10_i270_reg_1479[4] <= conv2_i_i10_i270_fu_931_p3[4];
conv2_i_i10_i270_reg_1479[6] <= conv2_i_i10_i270_fu_931_p3[6];
conv2_i_i10_i270_reg_1479[9] <= conv2_i_i10_i270_fu_931_p3[9];
        conv2_i_i10_i285_cast_cast_cast_cast_reg_1489[2] <= conv2_i_i10_i285_cast_cast_cast_cast_fu_947_p3[2];
conv2_i_i10_i285_cast_cast_cast_cast_reg_1489[4] <= conv2_i_i10_i285_cast_cast_cast_cast_fu_947_p3[4];
        conv2_i_i_i271_cast_cast_reg_1484[2] <= conv2_i_i_i271_cast_cast_fu_939_p3[2];
conv2_i_i_i271_cast_cast_reg_1484[4] <= conv2_i_i_i271_cast_cast_fu_939_p3[4];
conv2_i_i_i271_cast_cast_reg_1484[6] <= conv2_i_i_i271_cast_cast_fu_939_p3[6];
        conv2_i_i_i286_reg_1494[1 : 0] <= conv2_i_i_i286_fu_955_p3[1 : 0];
conv2_i_i_i286_reg_1494[4] <= conv2_i_i_i286_fu_955_p3[4];
conv2_i_i_i286_reg_1494[6] <= conv2_i_i_i286_fu_955_p3[6];
conv2_i_i_i286_reg_1494[9] <= conv2_i_i_i286_fu_955_p3[9];
        conv2_i_i_i299_reg_1499[9] <= conv2_i_i_i299_fu_963_p3[9];
        conv2_i_i_i313_reg_1504[8 : 0] <= conv2_i_i_i313_fu_971_p3[8 : 0];
        conv2_i_i_i_cast_cast_reg_1474[2] <= conv2_i_i_i_cast_cast_fu_923_p3[2];
        empty_125_reg_1546 <= empty_125_fu_1058_p1;
        outpix_10_reg_1541 <= outpix_10_fu_1046_p3;
        rampStart_load_reg_1535 <= rampStart;
        shl_i_reg_1551[15 : 8] <= shl_i_fu_1066_p3[15 : 8];
        sub10_i_reg_1530 <= sub10_i_fu_1036_p2;
        sub35_i_reg_1525 <= sub35_i_fu_1030_p2;
        sub_i_i_i_reg_1520 <= sub_i_i_i_fu_1024_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        colorSel_reg_1621 <= {{y_3_reg_1561[7:6]}};
        rev349_reg_1616 <= rev349_fu_1188_p2;
        rev_reg_1611 <= rev_fu_1182_p2;
        tmp_35_reg_1626 <= y_3_reg_1561[32'd5];
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln563_fu_1082_p2 == 1'd1) & (ap_phi_mux_hdata_flag_0_phi_fu_522_p4 == 1'd1) & (1'b1 == ap_CS_fsm_state3))) begin
        hdata <= hdata_new_0_fu_334;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_542_hdata_new_1_out_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state5))) begin
        hdata_new_0_fu_334 <= grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_542_hdata_new_1_out;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_542_outpix_4_out_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state5))) begin
        outpix_1_fu_298 <= grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_542_outpix_4_out;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_542_outpix_5_out_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state5))) begin
        outpix_2_fu_302 <= grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_542_outpix_5_out;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_542_outpix_3_out_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state5))) begin
        outpix_fu_294 <= grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_542_outpix_3_out;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_542_p_0_0_010243_out_o_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state5))) begin
        p_0_0_010244_lcssa251_fu_278 <= grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_542_p_0_0_010243_out_o;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_542_p_0_0_0247_out_o_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state5))) begin
        p_0_0_0248_lcssa257_fu_286 <= grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_542_p_0_0_0247_out_o;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_542_p_0_0_09245_out_o_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state5))) begin
        p_0_0_09246_lcssa254_fu_282 <= grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_542_p_0_0_09245_out_o;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln563_fu_1082_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state3))) begin
        rampStart <= add_ln750_fu_1144_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_542_rampVal_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state5))) begin
        rampVal <= grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_542_rampVal;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln563_fu_1082_p2 == 1'd1) & (ap_phi_mux_rampVal_3_flag_0_phi_fu_510_p4 == 1'd1) & (1'b1 == ap_CS_fsm_state3))) begin
        rampVal_1 <= rampVal_3_new_0_fu_362;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln563_fu_1082_p2 == 1'd1) & (ap_phi_mux_rampVal_2_flag_0_phi_fu_534_p4 == 1'd1) & (1'b1 == ap_CS_fsm_state3))) begin
        rampVal_2 <= rampVal_2_new_0_fu_318;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_542_rampVal_2_new_1_out_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state5))) begin
        rampVal_2_new_0_fu_318 <= grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_542_rampVal_2_new_1_out;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_542_rampVal_3_new_1_out_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state5))) begin
        rampVal_3_new_0_fu_362 <= grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_542_rampVal_3_new_1_out;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_542_tpgPatternCheckerBoard_unsigned_short_unsigned_short_unsigned_short_unsigned_1_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state5))) begin
        tpgPatternCheckerBoard_unsigned_short_unsigned_short_unsigned_short_unsigned_1 <= grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_542_tpgPatternCheckerBoard_unsigned_short_unsigned_short_unsigned_short_unsigned_1;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_542_tpgPatternColorBars_unsigned_short_unsigned_short_unsigned_char_int_hBarSel_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state5))) begin
        tpgPatternColorBars_unsigned_short_unsigned_short_unsigned_char_int_hBarSel <= grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_542_tpgPatternColorBars_unsigned_short_unsigned_short_unsigned_char_int_hBarSel;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_542_tpgPatternDPColorSquare_unsigned_short_unsigned_short_unsigned_char_unsigned_1_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state5))) begin
        tpgPatternDPColorSquare_unsigned_short_unsigned_short_unsigned_char_unsigned_1 <= grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_542_tpgPatternDPColorSquare_unsigned_short_unsigned_short_unsigned_char_unsigned_1;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_542_tpgPatternTartanColorBars_unsigned_short_unsigned_short_unsigned_short_unsign_1_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state5))) begin
        tpgPatternTartanColorBars_unsigned_short_unsigned_short_unsigned_short_unsign_1 <= grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_542_tpgPatternTartanColorBars_unsigned_short_unsigned_short_unsigned_short_unsign_1;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_542_vBarSel_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state5))) begin
        vBarSel <= grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_542_vBarSel;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_542_vBarSel_1_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state5))) begin
        vBarSel_1 <= grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_542_vBarSel_1;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_542_vBarSel_2_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state5))) begin
        vBarSel_2 <= grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_542_vBarSel_2;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_542_zonePlateVAddr_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state5))) begin
        zonePlateVAddr <= grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_542_zonePlateVAddr;
    end
end

always @ (*) begin
    if ((~((ap_done_reg == 1'b1) | (ap_start == 1'b0)) & (1'b1 == ap_CS_fsm_state1))) begin
        ZplateHorContDelta_val_blk_n = ZplateHorContDelta_val_empty_n;
    end else begin
        ZplateHorContDelta_val_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_state1) & (1'b1 == ap_CS_fsm_state1))) begin
        ZplateHorContDelta_val_read = 1'b1;
    end else begin
        ZplateHorContDelta_val_read = 1'b0;
    end
end

always @ (*) begin
    if ((~((ap_done_reg == 1'b1) | (ap_start == 1'b0)) & (1'b1 == ap_CS_fsm_state1))) begin
        ZplateHorContStart_val_blk_n = ZplateHorContStart_val_empty_n;
    end else begin
        ZplateHorContStart_val_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_state1) & (1'b1 == ap_CS_fsm_state1))) begin
        ZplateHorContStart_val_read = 1'b1;
    end else begin
        ZplateHorContStart_val_read = 1'b0;
    end
end

always @ (*) begin
    if ((~((ap_done_reg == 1'b1) | (ap_start == 1'b0)) & (1'b1 == ap_CS_fsm_state1))) begin
        ZplateVerContDelta_val_blk_n = ZplateVerContDelta_val_empty_n;
    end else begin
        ZplateVerContDelta_val_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_state1) & (1'b1 == ap_CS_fsm_state1))) begin
        ZplateVerContDelta_val_read = 1'b1;
    end else begin
        ZplateVerContDelta_val_read = 1'b0;
    end
end

always @ (*) begin
    if ((~((ap_done_reg == 1'b1) | (ap_start == 1'b0)) & (1'b1 == ap_CS_fsm_state1))) begin
        ZplateVerContStart_val_blk_n = ZplateVerContStart_val_empty_n;
    end else begin
        ZplateVerContStart_val_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_state1) & (1'b1 == ap_CS_fsm_state1))) begin
        ZplateVerContStart_val_read = 1'b1;
    end else begin
        ZplateVerContStart_val_read = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_block_state1)) begin
        ap_ST_fsm_state1_blk = 1'b1;
    end else begin
        ap_ST_fsm_state1_blk = 1'b0;
    end
end

assign ap_ST_fsm_state2_blk = 1'b0;

assign ap_ST_fsm_state3_blk = 1'b0;

assign ap_ST_fsm_state4_blk = 1'b0;

always @ (*) begin
    if ((grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_542_ap_done == 1'b0)) begin
        ap_ST_fsm_state5_blk = 1'b1;
    end else begin
        ap_ST_fsm_state5_blk = 1'b0;
    end
end

assign ap_ST_fsm_state6_blk = 1'b0;

always @ (*) begin
    if (((icmp_ln563_fu_1082_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state3))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = ap_done_reg;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln563_fu_1082_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state3))) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    if ((~((ap_done_reg == 1'b1) | (ap_start == 1'b0)) & (1'b1 == ap_CS_fsm_state1))) begin
        colorFormat_val27_c8_blk_n = colorFormat_val27_c8_full_n;
    end else begin
        colorFormat_val27_c8_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_state1) & (1'b1 == ap_CS_fsm_state1))) begin
        colorFormat_val27_c8_write = 1'b1;
    end else begin
        colorFormat_val27_c8_write = 1'b0;
    end
end

always @ (*) begin
    if ((~((ap_done_reg == 1'b1) | (ap_start == 1'b0)) & (1'b1 == ap_CS_fsm_state1))) begin
        colorFormat_val_blk_n = colorFormat_val_empty_n;
    end else begin
        colorFormat_val_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_state1) & (1'b1 == ap_CS_fsm_state1))) begin
        colorFormat_val_read = 1'b1;
    end else begin
        colorFormat_val_read = 1'b0;
    end
end

always @ (*) begin
    if ((~((ap_done_reg == 1'b1) | (ap_start == 1'b0)) & (1'b1 == ap_CS_fsm_state1))) begin
        dpDynamicRange_val_blk_n = dpDynamicRange_val_empty_n;
    end else begin
        dpDynamicRange_val_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_state1) & (1'b1 == ap_CS_fsm_state1))) begin
        dpDynamicRange_val_read = 1'b1;
    end else begin
        dpDynamicRange_val_read = 1'b0;
    end
end

always @ (*) begin
    if ((~((ap_done_reg == 1'b1) | (ap_start == 1'b0)) & (1'b1 == ap_CS_fsm_state1))) begin
        dpYUVCoef_val_blk_n = dpYUVCoef_val_empty_n;
    end else begin
        dpYUVCoef_val_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_state1) & (1'b1 == ap_CS_fsm_state1))) begin
        dpYUVCoef_val_read = 1'b1;
    end else begin
        dpYUVCoef_val_read = 1'b0;
    end
end

always @ (*) begin
    if ((~((ap_done_reg == 1'b1) | (ap_start == 1'b0)) & (1'b1 == ap_CS_fsm_state1))) begin
        enableInput_val_blk_n = enableInput_val_empty_n;
    end else begin
        enableInput_val_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_state1) & (1'b1 == ap_CS_fsm_state1))) begin
        enableInput_val_read = 1'b1;
    end else begin
        enableInput_val_read = 1'b0;
    end
end

always @ (*) begin
    if ((~((ap_done_reg == 1'b1) | (ap_start == 1'b0)) & (1'b1 == ap_CS_fsm_state1))) begin
        height_val5_c3_blk_n = height_val5_c3_full_n;
    end else begin
        height_val5_c3_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_state1) & (1'b1 == ap_CS_fsm_state1))) begin
        height_val5_c3_write = 1'b1;
    end else begin
        height_val5_c3_write = 1'b0;
    end
end

always @ (*) begin
    if ((~((ap_done_reg == 1'b1) | (ap_start == 1'b0)) & (1'b1 == ap_CS_fsm_state1))) begin
        height_val_blk_n = height_val_empty_n;
    end else begin
        height_val_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_state1) & (1'b1 == ap_CS_fsm_state1))) begin
        height_val_read = 1'b1;
    end else begin
        height_val_read = 1'b0;
    end
end

always @ (*) begin
    if ((~((ap_done_reg == 1'b1) | (ap_start == 1'b0)) & (1'b1 == ap_CS_fsm_state1))) begin
        motionSpeed_val23_c_blk_n = motionSpeed_val23_c_full_n;
    end else begin
        motionSpeed_val23_c_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_state1) & (1'b1 == ap_CS_fsm_state1))) begin
        motionSpeed_val23_c_write = 1'b1;
    end else begin
        motionSpeed_val23_c_write = 1'b0;
    end
end

always @ (*) begin
    if ((~((ap_done_reg == 1'b1) | (ap_start == 1'b0)) & (1'b1 == ap_CS_fsm_state1))) begin
        motionSpeed_val_blk_n = motionSpeed_val_empty_n;
    end else begin
        motionSpeed_val_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_state1) & (1'b1 == ap_CS_fsm_state1))) begin
        motionSpeed_val_read = 1'b1;
    end else begin
        motionSpeed_val_read = 1'b0;
    end
end

always @ (*) begin
    if ((~((ap_done_reg == 1'b1) | (ap_start == 1'b0)) & (1'b1 == ap_CS_fsm_state1))) begin
        passthruEndX_val_blk_n = passthruEndX_val_empty_n;
    end else begin
        passthruEndX_val_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_state1) & (1'b1 == ap_CS_fsm_state1))) begin
        passthruEndX_val_read = 1'b1;
    end else begin
        passthruEndX_val_read = 1'b0;
    end
end

always @ (*) begin
    if ((~((ap_done_reg == 1'b1) | (ap_start == 1'b0)) & (1'b1 == ap_CS_fsm_state1))) begin
        passthruEndY_val_blk_n = passthruEndY_val_empty_n;
    end else begin
        passthruEndY_val_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_state1) & (1'b1 == ap_CS_fsm_state1))) begin
        passthruEndY_val_read = 1'b1;
    end else begin
        passthruEndY_val_read = 1'b0;
    end
end

always @ (*) begin
    if ((~((ap_done_reg == 1'b1) | (ap_start == 1'b0)) & (1'b1 == ap_CS_fsm_state1))) begin
        passthruStartX_val_blk_n = passthruStartX_val_empty_n;
    end else begin
        passthruStartX_val_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_state1) & (1'b1 == ap_CS_fsm_state1))) begin
        passthruStartX_val_read = 1'b1;
    end else begin
        passthruStartX_val_read = 1'b0;
    end
end

always @ (*) begin
    if ((~((ap_done_reg == 1'b1) | (ap_start == 1'b0)) & (1'b1 == ap_CS_fsm_state1))) begin
        passthruStartY_val_blk_n = passthruStartY_val_empty_n;
    end else begin
        passthruStartY_val_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_state1) & (1'b1 == ap_CS_fsm_state1))) begin
        passthruStartY_val_read = 1'b1;
    end else begin
        passthruStartY_val_read = 1'b0;
    end
end

always @ (*) begin
    if ((~((ap_done_reg == 1'b1) | (ap_start == 1'b0)) & (1'b1 == ap_CS_fsm_state1))) begin
        patternId_val_blk_n = patternId_val_empty_n;
    end else begin
        patternId_val_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_state1) & (1'b1 == ap_CS_fsm_state1))) begin
        patternId_val_read = 1'b1;
    end else begin
        patternId_val_read = 1'b0;
    end
end

always @ (*) begin
    if ((~((ap_done_reg == 1'b1) | (ap_start == 1'b0)) & (1'b1 == ap_CS_fsm_state1))) begin
        width_val10_c5_blk_n = width_val10_c5_full_n;
    end else begin
        width_val10_c5_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_state1) & (1'b1 == ap_CS_fsm_state1))) begin
        width_val10_c5_write = 1'b1;
    end else begin
        width_val10_c5_write = 1'b0;
    end
end

always @ (*) begin
    if ((~((ap_done_reg == 1'b1) | (ap_start == 1'b0)) & (1'b1 == ap_CS_fsm_state1))) begin
        width_val_blk_n = width_val_empty_n;
    end else begin
        width_val_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_state1) & (1'b1 == ap_CS_fsm_state1))) begin
        width_val_read = 1'b1;
    end else begin
        width_val_read = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if (((1'b0 == ap_block_state1) & (1'b1 == ap_CS_fsm_state1))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_state2 : begin
            ap_NS_fsm = ap_ST_fsm_state3;
        end
        ap_ST_fsm_state3 : begin
            if (((icmp_ln563_fu_1082_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state3))) begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state4;
            end
        end
        ap_ST_fsm_state4 : begin
            ap_NS_fsm = ap_ST_fsm_state5;
        end
        ap_ST_fsm_state5 : begin
            if (((grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_542_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state5))) begin
                ap_NS_fsm = ap_ST_fsm_state6;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state5;
            end
        end
        ap_ST_fsm_state6 : begin
            ap_NS_fsm = ap_ST_fsm_state3;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign add2_i_fu_997_p2 = (empty_reg_1453 + 14'd15);

assign add5_i_fu_741_p2 = (empty_124_fu_737_p1 + 14'd15);

assign add_i410_fu_1131_p2 = (rampStart + empty_127_fu_1116_p1);

assign add_i_fu_982_p2 = (empty_reg_1453 + 14'd7);

assign add_ln563_fu_1087_p2 = (y_fu_290 + 16'd1);

assign add_ln750_fu_1144_p2 = (rampStart + zext_ln750_fu_1141_p1);

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state2 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_state3 = ap_CS_fsm[32'd2];

assign ap_CS_fsm_state4 = ap_CS_fsm[32'd3];

assign ap_CS_fsm_state5 = ap_CS_fsm[32'd4];

assign ap_CS_fsm_state6 = ap_CS_fsm[32'd5];

always @ (*) begin
    ap_block_state1 = ((patternId_val_empty_n == 1'b0) | (enableInput_val_empty_n == 1'b0) | (passthruEndY_val_empty_n == 1'b0) | (passthruEndX_val_empty_n == 1'b0) | (passthruStartY_val_empty_n == 1'b0) | (passthruStartX_val_empty_n == 1'b0) | (width_val_empty_n == 1'b0) | (height_val_empty_n == 1'b0) | (1'b0 == ZplateVerContStart_val_empty_n) | (1'b0 == ZplateHorContDelta_val_empty_n) | (1'b0 == ZplateHorContStart_val_empty_n) | (1'b0 == ZplateVerContDelta_val_empty_n) | (ap_done_reg == 1'b1) | (colorFormat_val27_c8_full_n == 1'b0) | (motionSpeed_val23_c_full_n == 1'b0) | (width_val10_c5_full_n == 1'b0) | (height_val5_c3_full_n == 1'b0) | (colorFormat_val_empty_n == 1'b0) | (motionSpeed_val_empty_n == 1'b0) | (ap_start == 1'b0) | (dpYUVCoef_val_empty_n == 1'b0) | (dpDynamicRange_val_empty_n == 1'b0));
end

assign ap_phi_mux_hdata_flag_0_phi_fu_522_p4 = hdata_flag_0_reg_518;

assign ap_phi_mux_rampVal_2_flag_0_phi_fu_534_p4 = rampVal_2_flag_0_reg_530;

assign ap_phi_mux_rampVal_3_flag_0_phi_fu_510_p4 = rampVal_3_flag_0_reg_506;

assign barHeight_cast_fu_1021_p1 = tmp_1_reg_1464;

assign barWidthMinSamples_fu_1012_p2 = ($signed(p_cast_fu_1002_p4) + $signed(10'd1023));

assign bckgndYUV_din = grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_542_bckgndYUV_din;

assign bckgndYUV_write = grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_542_bckgndYUV_write;

assign cmp11_i_fu_1126_p2 = ((sub10_i_reg_1530 == zext_ln563_2_fu_1102_p1) ? 1'b1 : 1'b0);

assign cmp12_i_fu_1120_p2 = ((y_fu_290 != 16'd0) ? 1'b1 : 1'b0);

assign cmp136_i_fu_1074_p2 = ((colorFormatLocal_reg_1399 != 8'd1) ? 1'b1 : 1'b0);

assign cmp2_i_fu_910_p2 = ((colorFormatLocal_reg_1399 == 8'd0) ? 1'b1 : 1'b0);

assign colorFormat_val27_c8_din = colorFormat_val_dout;

assign conv2_i_i10_i267_fu_915_p3 = ((cmp2_i_fu_910_p2[0:0] == 1'b1) ? 10'd1023 : 10'd304);

assign conv2_i_i10_i270_fu_931_p3 = ((cmp2_i_fu_910_p2[0:0] == 1'b1) ? 10'd0 : 10'd596);

assign conv2_i_i10_i285_cast_cast_cast_cast_fu_947_p3 = ((cmp2_i_fu_910_p2[0:0] == 1'b1) ? 5'd0 : 5'd20);

assign conv2_i_i_i271_cast_cast_fu_939_p3 = ((cmp2_i_fu_910_p2[0:0] == 1'b1) ? 7'd0 : 7'd84);

assign conv2_i_i_i286_fu_955_p3 = ((cmp2_i_fu_910_p2[0:0] == 1'b1) ? 10'd1023 : 10'd428);

assign conv2_i_i_i299_fu_963_p3 = ((cmp2_i_fu_910_p2[0:0] == 1'b1) ? 10'd0 : 10'd512);

assign conv2_i_i_i313_fu_971_p3 = ((cmp2_i_fu_910_p2[0:0] == 1'b1) ? 10'd1023 : 10'd512);

assign conv2_i_i_i_cast_cast_fu_923_p3 = ((cmp2_i_fu_910_p2[0:0] == 1'b1) ? 3'd0 : 3'd4);

assign empty_124_fu_737_p1 = height_val_dout[13:0];

assign empty_125_fu_1058_p1 = s[7:0];

assign empty_126_fu_1062_p1 = rampStart[7:0];

assign empty_127_fu_1116_p1 = y_fu_290[9:0];

assign empty_fu_733_p1 = width_val_dout[13:0];

assign grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_542_ap_start = grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_542_ap_start_reg;

assign height_val5_c3_din = height_val_dout;

assign height_val_cast15_fu_1018_p1 = loopHeight_reg_1447;

assign icmp_fu_757_p2 = ((tmp_fu_747_p4 != 7'd0) ? 1'b1 : 1'b0);

assign icmp_ln563_fu_1082_p2 = ((y_fu_290 == loopHeight_reg_1447) ? 1'b1 : 1'b0);

assign motionSpeed_val23_c_din = motionSpeed_val_dout;

assign outpix_10_fu_1046_p3 = ((cmp2_i_fu_910_p2[0:0] == 1'b1) ? rampStart : 10'd512);

assign p_cast_fu_1002_p4 = {{add2_i_fu_997_p2[13:4]}};

assign rev349_fu_1188_p2 = (ult348_reg_1591 ^ 1'd1);

assign rev_fu_1182_p2 = (ult_reg_1586 ^ 1'd1);

assign shl_i_fu_1066_p3 = {{empty_126_fu_1062_p1}, {8'd0}};

assign srcYUV_read = grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_542_srcYUV_read;

assign sub10_i_fu_1036_p2 = ($signed(height_val_cast15_fu_1018_p1) + $signed(17'd131071));

assign sub35_i_fu_1030_p2 = ($signed(width_val_cast14_fu_979_p1) + $signed(17'd131071));

assign sub_i_i_i_fu_1024_p2 = ($signed(barHeight_cast_fu_1021_p1) + $signed(11'd2047));

assign tmp_fu_747_p4 = {{colorFormat_val_dout[7:1]}};

assign ult348_fu_1111_p2 = ((y_fu_290 < passthruEndY_val_read_reg_1421) ? 1'b1 : 1'b0);

assign ult_fu_1106_p2 = ((y_fu_290 < passthruStartY_val_read_reg_1431) ? 1'b1 : 1'b0);

assign width_val10_c5_din = width_val_dout;

assign width_val_cast14_fu_979_p1 = loopWidth_reg_1441;

assign zext_ln1257_fu_781_p1 = rampVal;

assign zext_ln1412_fu_797_p1 = vBarSel;

assign zext_ln1545_fu_805_p1 = tpgPatternTartanColorBars_unsigned_short_unsigned_short_unsigned_short_unsign_1;

assign zext_ln1775_fu_833_p1 = vBarSel_1;

assign zext_ln563_1_fu_841_p1 = tpgPatternDPColorSquare_unsigned_short_unsigned_short_unsigned_char_unsigned_1;

assign zext_ln563_2_fu_1102_p1 = y_fu_290;

assign zext_ln563_fu_821_p1 = tpgPatternCheckerBoard_unsigned_short_unsigned_short_unsigned_short_unsigned_1;

assign zext_ln750_fu_1141_p1 = motionSpeed_val_read_reg_1406;

always @ (posedge ap_clk) begin
    conv2_i_i10_i267_reg_1469[5:4] <= 2'b11;
    conv2_i_i10_i267_reg_1469[8] <= 1'b1;
    conv2_i_i_i_cast_cast_reg_1474[1:0] <= 2'b00;
    conv2_i_i10_i270_reg_1479[1:0] <= 2'b00;
    conv2_i_i10_i270_reg_1479[3:3] <= 1'b0;
    conv2_i_i10_i270_reg_1479[5:5] <= 1'b0;
    conv2_i_i10_i270_reg_1479[8:7] <= 2'b00;
    conv2_i_i_i271_cast_cast_reg_1484[1:0] <= 2'b00;
    conv2_i_i_i271_cast_cast_reg_1484[3:3] <= 1'b0;
    conv2_i_i_i271_cast_cast_reg_1484[5] <= 1'b0;
    conv2_i_i10_i285_cast_cast_cast_cast_reg_1489[1:0] <= 2'b00;
    conv2_i_i10_i285_cast_cast_cast_cast_reg_1489[3] <= 1'b0;
    conv2_i_i_i286_reg_1494[3:2] <= 2'b11;
    conv2_i_i_i286_reg_1494[5:5] <= 1'b1;
    conv2_i_i_i286_reg_1494[8:7] <= 2'b11;
    conv2_i_i_i299_reg_1499[8:0] <= 9'b000000000;
    conv2_i_i_i313_reg_1504[9] <= 1'b1;
    shl_i_reg_1551[7:0] <= 8'b00000000;
end

endmodule //system_v_tpg_0_0_tpgBackground
