// ==============================================================
// Generated by Vitis HLS v2024.2
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2024 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

module system_v_tpg_0_0_MultiPixStream2AXIvideo (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_continue,
        ap_idle,
        ap_ready,
        ovrlayYUV_dout,
        ovrlayYUV_empty_n,
        ovrlayYUV_read,
        ovrlayYUV_num_data_valid,
        ovrlayYUV_fifo_cap,
        m_axis_video_TDATA,
        m_axis_video_TVALID,
        m_axis_video_TREADY,
        m_axis_video_TKEEP,
        m_axis_video_TSTRB,
        m_axis_video_TUSER,
        m_axis_video_TLAST,
        m_axis_video_TID,
        m_axis_video_TDEST,
        height_val5_dout,
        height_val5_empty_n,
        height_val5_read,
        height_val5_num_data_valid,
        height_val5_fifo_cap,
        width_val10_dout,
        width_val10_empty_n,
        width_val10_read,
        width_val10_num_data_valid,
        width_val10_fifo_cap,
        colorFormat_val27_dout,
        colorFormat_val27_empty_n,
        colorFormat_val27_read,
        colorFormat_val27_num_data_valid,
        colorFormat_val27_fifo_cap,
        fid_in_val12_dout,
        fid_in_val12_empty_n,
        fid_in_val12_read,
        fid_in_val12_num_data_valid,
        fid_in_val12_fifo_cap,
        fid,
        fid_ap_vld,
        field_id_val11_dout,
        field_id_val11_empty_n,
        field_id_val11_read,
        field_id_val11_num_data_valid,
        field_id_val11_fifo_cap
);

parameter    ap_ST_fsm_state1 = 4'd1;
parameter    ap_ST_fsm_state2 = 4'd2;
parameter    ap_ST_fsm_state3 = 4'd4;
parameter    ap_ST_fsm_state4 = 4'd8;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
input   ap_continue;
output   ap_idle;
output   ap_ready;
input  [29:0] ovrlayYUV_dout;
input   ovrlayYUV_empty_n;
output   ovrlayYUV_read;
input  [4:0] ovrlayYUV_num_data_valid;
input  [4:0] ovrlayYUV_fifo_cap;
output  [31:0] m_axis_video_TDATA;
output   m_axis_video_TVALID;
input   m_axis_video_TREADY;
output  [3:0] m_axis_video_TKEEP;
output  [3:0] m_axis_video_TSTRB;
output  [0:0] m_axis_video_TUSER;
output  [0:0] m_axis_video_TLAST;
output  [0:0] m_axis_video_TID;
output  [0:0] m_axis_video_TDEST;
input  [11:0] height_val5_dout;
input   height_val5_empty_n;
output   height_val5_read;
input  [2:0] height_val5_num_data_valid;
input  [2:0] height_val5_fifo_cap;
input  [12:0] width_val10_dout;
input   width_val10_empty_n;
output   width_val10_read;
input  [2:0] width_val10_num_data_valid;
input  [2:0] width_val10_fifo_cap;
input  [7:0] colorFormat_val27_dout;
input   colorFormat_val27_empty_n;
output   colorFormat_val27_read;
input  [2:0] colorFormat_val27_num_data_valid;
input  [2:0] colorFormat_val27_fifo_cap;
input  [0:0] fid_in_val12_dout;
input   fid_in_val12_empty_n;
output   fid_in_val12_read;
input  [3:0] fid_in_val12_num_data_valid;
input  [3:0] fid_in_val12_fifo_cap;
output  [0:0] fid;
output   fid_ap_vld;
input  [15:0] field_id_val11_dout;
input   field_id_val11_empty_n;
output   field_id_val11_read;
input  [3:0] field_id_val11_num_data_valid;
input  [3:0] field_id_val11_fifo_cap;

reg ap_done;
reg ap_idle;
reg ap_ready;
reg[31:0] m_axis_video_TDATA;
reg[3:0] m_axis_video_TKEEP;
reg[3:0] m_axis_video_TSTRB;
reg[0:0] m_axis_video_TUSER;
reg[0:0] m_axis_video_TLAST;
reg[0:0] m_axis_video_TID;
reg[0:0] m_axis_video_TDEST;
reg height_val5_read;
reg width_val10_read;
reg colorFormat_val27_read;
reg fid_in_val12_read;
reg[0:0] fid;
reg fid_ap_vld;
reg field_id_val11_read;

reg    ap_done_reg;
(* fsm_encoding = "none" *) reg   [3:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
reg   [0:0] fidStored;
reg   [15:0] counter;
reg    height_val5_blk_n;
reg    width_val10_blk_n;
reg    colorFormat_val27_blk_n;
reg    fid_in_val12_blk_n;
reg    field_id_val11_blk_n;
reg   [7:0] colorFormat_val27_read_reg_411;
reg    ap_block_state1;
reg   [0:0] fid_in_val12_read_reg_416;
reg   [12:0] cols_reg_421;
reg   [11:0] rows_reg_426;
wire   [12:0] sub_i_fu_207_p2;
reg   [12:0] sub_i_reg_431;
wire   [0:0] cmp104_i_fu_213_p2;
reg   [0:0] cmp104_i_reg_436;
wire   [0:0] cmp20177_i_fu_219_p2;
reg   [0:0] cmp20177_i_reg_441;
wire   [0:0] switch_i_fu_225_p2;
reg   [0:0] switch_i_reg_445;
wire   [0:0] icmp_ln1038_fu_249_p2;
reg   [0:0] icmp_ln1038_reg_450;
wire   [0:0] icmp_ln1038_1_fu_255_p2;
reg   [0:0] icmp_ln1038_1_reg_455;
wire   [11:0] i_2_fu_293_p2;
reg   [11:0] i_2_reg_463;
wire    ap_CS_fsm_state2;
wire    grp_MultiPixStream2AXIvideo_Pipeline_VITIS_LOOP_981_2_fu_173_ap_start;
wire    grp_MultiPixStream2AXIvideo_Pipeline_VITIS_LOOP_981_2_fu_173_ap_done;
wire    grp_MultiPixStream2AXIvideo_Pipeline_VITIS_LOOP_981_2_fu_173_ap_idle;
wire    grp_MultiPixStream2AXIvideo_Pipeline_VITIS_LOOP_981_2_fu_173_ap_ready;
wire    grp_MultiPixStream2AXIvideo_Pipeline_VITIS_LOOP_981_2_fu_173_ovrlayYUV_read;
wire   [31:0] grp_MultiPixStream2AXIvideo_Pipeline_VITIS_LOOP_981_2_fu_173_m_axis_video_TDATA;
wire    grp_MultiPixStream2AXIvideo_Pipeline_VITIS_LOOP_981_2_fu_173_m_axis_video_TVALID;
wire    grp_MultiPixStream2AXIvideo_Pipeline_VITIS_LOOP_981_2_fu_173_m_axis_video_TREADY;
wire   [3:0] grp_MultiPixStream2AXIvideo_Pipeline_VITIS_LOOP_981_2_fu_173_m_axis_video_TKEEP;
wire   [3:0] grp_MultiPixStream2AXIvideo_Pipeline_VITIS_LOOP_981_2_fu_173_m_axis_video_TSTRB;
wire   [0:0] grp_MultiPixStream2AXIvideo_Pipeline_VITIS_LOOP_981_2_fu_173_m_axis_video_TUSER;
wire   [0:0] grp_MultiPixStream2AXIvideo_Pipeline_VITIS_LOOP_981_2_fu_173_m_axis_video_TLAST;
wire   [0:0] grp_MultiPixStream2AXIvideo_Pipeline_VITIS_LOOP_981_2_fu_173_m_axis_video_TID;
wire   [0:0] grp_MultiPixStream2AXIvideo_Pipeline_VITIS_LOOP_981_2_fu_173_m_axis_video_TDEST;
wire   [15:0] grp_MultiPixStream2AXIvideo_Pipeline_VITIS_LOOP_981_2_fu_173_counter_loc_1_i_out;
wire    grp_MultiPixStream2AXIvideo_Pipeline_VITIS_LOOP_981_2_fu_173_counter_loc_1_i_out_ap_vld;
wire   [0:0] grp_MultiPixStream2AXIvideo_Pipeline_VITIS_LOOP_981_2_fu_173_phi_ln1036_out;
wire    grp_MultiPixStream2AXIvideo_Pipeline_VITIS_LOOP_981_2_fu_173_phi_ln1036_out_ap_vld;
wire   [15:0] grp_MultiPixStream2AXIvideo_Pipeline_VITIS_LOOP_981_2_fu_173_counter;
wire    grp_MultiPixStream2AXIvideo_Pipeline_VITIS_LOOP_981_2_fu_173_counter_ap_vld;
reg    grp_MultiPixStream2AXIvideo_Pipeline_VITIS_LOOP_981_2_fu_173_ap_start_reg;
wire   [0:0] icmp_ln979_fu_288_p2;
wire    ap_CS_fsm_state3;
reg   [31:0] m_axis_video_TDATA_reg;
reg   [3:0] m_axis_video_TKEEP_reg;
reg   [3:0] m_axis_video_TSTRB_reg;
reg   [0:0] m_axis_video_TUSER_reg;
reg   [0:0] m_axis_video_TLAST_reg;
reg   [0:0] m_axis_video_TID_reg;
reg   [0:0] m_axis_video_TDEST_reg;
reg   [15:0] counter_loc_1_i_loc_fu_132;
reg   [0:0] phi_ln1036_loc_fu_128;
reg   [11:0] i_fu_112;
wire    ap_CS_fsm_state4;
reg   [15:0] counter_loc_0_i_fu_116;
reg   [0:0] sof_fu_120;
reg   [0:0] empty_fu_124;
wire   [0:0] select_ln1038_fu_344_p3;
reg   [0:0] fid_preg;
wire   [14:0] tmp_s_fu_231_p4;
wire   [15:0] tmp_17_fu_241_p3;
wire   [0:0] and_ln1038_fu_322_p2;
wire   [0:0] xor_ln1053_fu_332_p2;
wire   [0:0] or_ln1038_fu_327_p2;
wire   [0:0] select_ln1051_fu_338_p3;
reg   [3:0] ap_NS_fsm;
reg    ap_ST_fsm_state1_blk;
wire    ap_ST_fsm_state2_blk;
reg    ap_ST_fsm_state3_blk;
wire    ap_ST_fsm_state4_blk;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_done_reg = 1'b0;
#0 ap_CS_fsm = 4'd1;
#0 fidStored = 1'd0;
#0 counter = 16'd0;
#0 grp_MultiPixStream2AXIvideo_Pipeline_VITIS_LOOP_981_2_fu_173_ap_start_reg = 1'b0;
#0 i_fu_112 = 12'd0;
#0 counter_loc_0_i_fu_116 = 16'd0;
#0 sof_fu_120 = 1'd0;
#0 empty_fu_124 = 1'd0;
#0 fid_preg = 1'd0;
end

system_v_tpg_0_0_MultiPixStream2AXIvideo_Pipeline_VITIS_LOOP_981_2 grp_MultiPixStream2AXIvideo_Pipeline_VITIS_LOOP_981_2_fu_173(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_MultiPixStream2AXIvideo_Pipeline_VITIS_LOOP_981_2_fu_173_ap_start),
    .ap_done(grp_MultiPixStream2AXIvideo_Pipeline_VITIS_LOOP_981_2_fu_173_ap_done),
    .ap_idle(grp_MultiPixStream2AXIvideo_Pipeline_VITIS_LOOP_981_2_fu_173_ap_idle),
    .ap_ready(grp_MultiPixStream2AXIvideo_Pipeline_VITIS_LOOP_981_2_fu_173_ap_ready),
    .counter_loc_0_i(counter_loc_0_i_fu_116),
    .sof(sof_fu_120),
    .cols(cols_reg_421),
    .ovrlayYUV_dout(ovrlayYUV_dout),
    .ovrlayYUV_empty_n(ovrlayYUV_empty_n),
    .ovrlayYUV_read(grp_MultiPixStream2AXIvideo_Pipeline_VITIS_LOOP_981_2_fu_173_ovrlayYUV_read),
    .ovrlayYUV_num_data_valid(5'd0),
    .ovrlayYUV_fifo_cap(5'd0),
    .colorFormat_val27_load(colorFormat_val27_read_reg_411),
    .m_axis_video_TDATA(grp_MultiPixStream2AXIvideo_Pipeline_VITIS_LOOP_981_2_fu_173_m_axis_video_TDATA),
    .m_axis_video_TVALID(grp_MultiPixStream2AXIvideo_Pipeline_VITIS_LOOP_981_2_fu_173_m_axis_video_TVALID),
    .m_axis_video_TREADY(grp_MultiPixStream2AXIvideo_Pipeline_VITIS_LOOP_981_2_fu_173_m_axis_video_TREADY),
    .m_axis_video_TKEEP(grp_MultiPixStream2AXIvideo_Pipeline_VITIS_LOOP_981_2_fu_173_m_axis_video_TKEEP),
    .m_axis_video_TSTRB(grp_MultiPixStream2AXIvideo_Pipeline_VITIS_LOOP_981_2_fu_173_m_axis_video_TSTRB),
    .m_axis_video_TUSER(grp_MultiPixStream2AXIvideo_Pipeline_VITIS_LOOP_981_2_fu_173_m_axis_video_TUSER),
    .m_axis_video_TLAST(grp_MultiPixStream2AXIvideo_Pipeline_VITIS_LOOP_981_2_fu_173_m_axis_video_TLAST),
    .m_axis_video_TID(grp_MultiPixStream2AXIvideo_Pipeline_VITIS_LOOP_981_2_fu_173_m_axis_video_TID),
    .m_axis_video_TDEST(grp_MultiPixStream2AXIvideo_Pipeline_VITIS_LOOP_981_2_fu_173_m_axis_video_TDEST),
    .sub_cast_i(sub_i_reg_431),
    .counter_loc_1_i_out(grp_MultiPixStream2AXIvideo_Pipeline_VITIS_LOOP_981_2_fu_173_counter_loc_1_i_out),
    .counter_loc_1_i_out_ap_vld(grp_MultiPixStream2AXIvideo_Pipeline_VITIS_LOOP_981_2_fu_173_counter_loc_1_i_out_ap_vld),
    .phi_ln1036_out(grp_MultiPixStream2AXIvideo_Pipeline_VITIS_LOOP_981_2_fu_173_phi_ln1036_out),
    .phi_ln1036_out_ap_vld(grp_MultiPixStream2AXIvideo_Pipeline_VITIS_LOOP_981_2_fu_173_phi_ln1036_out_ap_vld),
    .counter(grp_MultiPixStream2AXIvideo_Pipeline_VITIS_LOOP_981_2_fu_173_counter),
    .counter_ap_vld(grp_MultiPixStream2AXIvideo_Pipeline_VITIS_LOOP_981_2_fu_173_counter_ap_vld)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((1'b1 == ap_CS_fsm_state2) & (icmp_ln979_fu_288_p2 == 1'd1))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        fid_preg <= 1'd0;
    end else begin
        if (((1'b1 == ap_CS_fsm_state4) & (cmp20177_i_reg_441 == 1'd0))) begin
            fid_preg <= select_ln1038_fu_344_p3;
        end else if (((1'b1 == ap_CS_fsm_state1) & (1'b0 == ap_block_state1))) begin
            fid_preg <= fidStored;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_MultiPixStream2AXIvideo_Pipeline_VITIS_LOOP_981_2_fu_173_ap_start_reg <= 1'b0;
    end else begin
        if (((1'b1 == ap_CS_fsm_state2) & (icmp_ln979_fu_288_p2 == 1'd0))) begin
            grp_MultiPixStream2AXIvideo_Pipeline_VITIS_LOOP_981_2_fu_173_ap_start_reg <= 1'b1;
        end else if ((grp_MultiPixStream2AXIvideo_Pipeline_VITIS_LOOP_981_2_fu_173_ap_ready == 1'b1)) begin
            grp_MultiPixStream2AXIvideo_Pipeline_VITIS_LOOP_981_2_fu_173_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state1) & (1'b0 == ap_block_state1))) begin
        counter_loc_0_i_fu_116 <= counter;
    end else if ((1'b1 == ap_CS_fsm_state4)) begin
        counter_loc_0_i_fu_116 <= counter_loc_1_i_loc_fu_132;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state1) & (1'b0 == ap_block_state1))) begin
        empty_fu_124 <= fidStored;
    end else if (((1'b1 == ap_CS_fsm_state4) & (cmp20177_i_reg_441 == 1'd0))) begin
        empty_fu_124 <= select_ln1038_fu_344_p3;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state1) & (1'b0 == ap_block_state1))) begin
        i_fu_112 <= 12'd0;
    end else if ((1'b1 == ap_CS_fsm_state4)) begin
        i_fu_112 <= i_2_reg_463;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state1) & (1'b0 == ap_block_state1))) begin
        sof_fu_120 <= 1'd1;
    end else if (((1'b1 == ap_CS_fsm_state4) & (cmp20177_i_reg_441 == 1'd0))) begin
        sof_fu_120 <= 1'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state1) & (1'b0 == ap_block_state1))) begin
        cmp104_i_reg_436 <= cmp104_i_fu_213_p2;
        cmp20177_i_reg_441 <= cmp20177_i_fu_219_p2;
        colorFormat_val27_read_reg_411 <= colorFormat_val27_dout;
        cols_reg_421 <= width_val10_dout;
        fid_in_val12_read_reg_416 <= fid_in_val12_dout;
        icmp_ln1038_1_reg_455 <= icmp_ln1038_1_fu_255_p2;
        icmp_ln1038_reg_450 <= icmp_ln1038_fu_249_p2;
        rows_reg_426 <= height_val5_dout;
        sub_i_reg_431 <= sub_i_fu_207_p2;
        switch_i_reg_445 <= switch_i_fu_225_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state3) & (grp_MultiPixStream2AXIvideo_Pipeline_VITIS_LOOP_981_2_fu_173_counter_ap_vld == 1'b1))) begin
        counter <= grp_MultiPixStream2AXIvideo_Pipeline_VITIS_LOOP_981_2_fu_173_counter;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state3) & (grp_MultiPixStream2AXIvideo_Pipeline_VITIS_LOOP_981_2_fu_173_counter_loc_1_i_out_ap_vld == 1'b1))) begin
        counter_loc_1_i_loc_fu_132 <= grp_MultiPixStream2AXIvideo_Pipeline_VITIS_LOOP_981_2_fu_173_counter_loc_1_i_out;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state2) & (icmp_ln979_fu_288_p2 == 1'd1))) begin
        fidStored <= empty_fu_124;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        i_2_reg_463 <= i_2_fu_293_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state3) & (grp_MultiPixStream2AXIvideo_Pipeline_VITIS_LOOP_981_2_fu_173_m_axis_video_TVALID == 1'b1))) begin
        m_axis_video_TDATA_reg <= grp_MultiPixStream2AXIvideo_Pipeline_VITIS_LOOP_981_2_fu_173_m_axis_video_TDATA;
        m_axis_video_TDEST_reg <= grp_MultiPixStream2AXIvideo_Pipeline_VITIS_LOOP_981_2_fu_173_m_axis_video_TDEST;
        m_axis_video_TID_reg <= grp_MultiPixStream2AXIvideo_Pipeline_VITIS_LOOP_981_2_fu_173_m_axis_video_TID;
        m_axis_video_TKEEP_reg <= grp_MultiPixStream2AXIvideo_Pipeline_VITIS_LOOP_981_2_fu_173_m_axis_video_TKEEP;
        m_axis_video_TLAST_reg <= grp_MultiPixStream2AXIvideo_Pipeline_VITIS_LOOP_981_2_fu_173_m_axis_video_TLAST;
        m_axis_video_TSTRB_reg <= grp_MultiPixStream2AXIvideo_Pipeline_VITIS_LOOP_981_2_fu_173_m_axis_video_TSTRB;
        m_axis_video_TUSER_reg <= grp_MultiPixStream2AXIvideo_Pipeline_VITIS_LOOP_981_2_fu_173_m_axis_video_TUSER;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state3) & (grp_MultiPixStream2AXIvideo_Pipeline_VITIS_LOOP_981_2_fu_173_phi_ln1036_out_ap_vld == 1'b1))) begin
        phi_ln1036_loc_fu_128 <= grp_MultiPixStream2AXIvideo_Pipeline_VITIS_LOOP_981_2_fu_173_phi_ln1036_out;
    end
end

always @ (*) begin
    if ((1'b1 == ap_block_state1)) begin
        ap_ST_fsm_state1_blk = 1'b1;
    end else begin
        ap_ST_fsm_state1_blk = 1'b0;
    end
end

assign ap_ST_fsm_state2_blk = 1'b0;

always @ (*) begin
    if ((grp_MultiPixStream2AXIvideo_Pipeline_VITIS_LOOP_981_2_fu_173_ap_done == 1'b0)) begin
        ap_ST_fsm_state3_blk = 1'b1;
    end else begin
        ap_ST_fsm_state3_blk = 1'b0;
    end
end

assign ap_ST_fsm_state4_blk = 1'b0;

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state2) & (icmp_ln979_fu_288_p2 == 1'd1))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = ap_done_reg;
    end
end

always @ (*) begin
    if (((ap_start == 1'b0) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state2) & (icmp_ln979_fu_288_p2 == 1'd1))) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    if ((~((ap_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        colorFormat_val27_blk_n = colorFormat_val27_empty_n;
    end else begin
        colorFormat_val27_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state1) & (1'b0 == ap_block_state1))) begin
        colorFormat_val27_read = 1'b1;
    end else begin
        colorFormat_val27_read = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state4) & (cmp20177_i_reg_441 == 1'd0))) begin
        fid = select_ln1038_fu_344_p3;
    end else if (((1'b1 == ap_CS_fsm_state1) & (1'b0 == ap_block_state1))) begin
        fid = fidStored;
    end else begin
        fid = fid_preg;
    end
end

always @ (*) begin
    if ((((1'b1 == ap_CS_fsm_state1) & (1'b0 == ap_block_state1)) | ((1'b1 == ap_CS_fsm_state4) & (cmp20177_i_reg_441 == 1'd0)))) begin
        fid_ap_vld = 1'b1;
    end else begin
        fid_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if ((~((ap_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        fid_in_val12_blk_n = fid_in_val12_empty_n;
    end else begin
        fid_in_val12_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state1) & (1'b0 == ap_block_state1))) begin
        fid_in_val12_read = 1'b1;
    end else begin
        fid_in_val12_read = 1'b0;
    end
end

always @ (*) begin
    if ((~((ap_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        field_id_val11_blk_n = field_id_val11_empty_n;
    end else begin
        field_id_val11_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state1) & (1'b0 == ap_block_state1))) begin
        field_id_val11_read = 1'b1;
    end else begin
        field_id_val11_read = 1'b0;
    end
end

always @ (*) begin
    if ((~((ap_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        height_val5_blk_n = height_val5_empty_n;
    end else begin
        height_val5_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state1) & (1'b0 == ap_block_state1))) begin
        height_val5_read = 1'b1;
    end else begin
        height_val5_read = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state3) & (grp_MultiPixStream2AXIvideo_Pipeline_VITIS_LOOP_981_2_fu_173_m_axis_video_TVALID == 1'b1))) begin
        m_axis_video_TDATA = grp_MultiPixStream2AXIvideo_Pipeline_VITIS_LOOP_981_2_fu_173_m_axis_video_TDATA;
    end else begin
        m_axis_video_TDATA = m_axis_video_TDATA_reg;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state3) & (grp_MultiPixStream2AXIvideo_Pipeline_VITIS_LOOP_981_2_fu_173_m_axis_video_TVALID == 1'b1))) begin
        m_axis_video_TDEST = grp_MultiPixStream2AXIvideo_Pipeline_VITIS_LOOP_981_2_fu_173_m_axis_video_TDEST;
    end else begin
        m_axis_video_TDEST = m_axis_video_TDEST_reg;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state3) & (grp_MultiPixStream2AXIvideo_Pipeline_VITIS_LOOP_981_2_fu_173_m_axis_video_TVALID == 1'b1))) begin
        m_axis_video_TID = grp_MultiPixStream2AXIvideo_Pipeline_VITIS_LOOP_981_2_fu_173_m_axis_video_TID;
    end else begin
        m_axis_video_TID = m_axis_video_TID_reg;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state3) & (grp_MultiPixStream2AXIvideo_Pipeline_VITIS_LOOP_981_2_fu_173_m_axis_video_TVALID == 1'b1))) begin
        m_axis_video_TKEEP = grp_MultiPixStream2AXIvideo_Pipeline_VITIS_LOOP_981_2_fu_173_m_axis_video_TKEEP;
    end else begin
        m_axis_video_TKEEP = m_axis_video_TKEEP_reg;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state3) & (grp_MultiPixStream2AXIvideo_Pipeline_VITIS_LOOP_981_2_fu_173_m_axis_video_TVALID == 1'b1))) begin
        m_axis_video_TLAST = grp_MultiPixStream2AXIvideo_Pipeline_VITIS_LOOP_981_2_fu_173_m_axis_video_TLAST;
    end else begin
        m_axis_video_TLAST = m_axis_video_TLAST_reg;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state3) & (grp_MultiPixStream2AXIvideo_Pipeline_VITIS_LOOP_981_2_fu_173_m_axis_video_TVALID == 1'b1))) begin
        m_axis_video_TSTRB = grp_MultiPixStream2AXIvideo_Pipeline_VITIS_LOOP_981_2_fu_173_m_axis_video_TSTRB;
    end else begin
        m_axis_video_TSTRB = m_axis_video_TSTRB_reg;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state3) & (grp_MultiPixStream2AXIvideo_Pipeline_VITIS_LOOP_981_2_fu_173_m_axis_video_TVALID == 1'b1))) begin
        m_axis_video_TUSER = grp_MultiPixStream2AXIvideo_Pipeline_VITIS_LOOP_981_2_fu_173_m_axis_video_TUSER;
    end else begin
        m_axis_video_TUSER = m_axis_video_TUSER_reg;
    end
end

always @ (*) begin
    if ((~((ap_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        width_val10_blk_n = width_val10_empty_n;
    end else begin
        width_val10_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state1) & (1'b0 == ap_block_state1))) begin
        width_val10_read = 1'b1;
    end else begin
        width_val10_read = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if (((1'b1 == ap_CS_fsm_state1) & (1'b0 == ap_block_state1))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_state2 : begin
            if (((1'b1 == ap_CS_fsm_state2) & (icmp_ln979_fu_288_p2 == 1'd1))) begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state3;
            end
        end
        ap_ST_fsm_state3 : begin
            if (((1'b1 == ap_CS_fsm_state3) & (grp_MultiPixStream2AXIvideo_Pipeline_VITIS_LOOP_981_2_fu_173_ap_done == 1'b1))) begin
                ap_NS_fsm = ap_ST_fsm_state4;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state3;
            end
        end
        ap_ST_fsm_state4 : begin
            ap_NS_fsm = ap_ST_fsm_state2;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign and_ln1038_fu_322_p2 = (phi_ln1036_loc_fu_128 & icmp_ln1038_reg_450);

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state2 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_state3 = ap_CS_fsm[32'd2];

assign ap_CS_fsm_state4 = ap_CS_fsm[32'd3];

always @ (*) begin
    ap_block_state1 = ((ap_start == 1'b0) | (field_id_val11_empty_n == 1'b0) | (fid_in_val12_empty_n == 1'b0) | (colorFormat_val27_empty_n == 1'b0) | (width_val10_empty_n == 1'b0) | (height_val5_empty_n == 1'b0) | (ap_done_reg == 1'b1));
end

assign cmp104_i_fu_213_p2 = ((field_id_val11_dout == 16'd3) ? 1'b1 : 1'b0);

assign cmp20177_i_fu_219_p2 = ((width_val10_dout == 13'd0) ? 1'b1 : 1'b0);

assign grp_MultiPixStream2AXIvideo_Pipeline_VITIS_LOOP_981_2_fu_173_ap_start = grp_MultiPixStream2AXIvideo_Pipeline_VITIS_LOOP_981_2_fu_173_ap_start_reg;

assign grp_MultiPixStream2AXIvideo_Pipeline_VITIS_LOOP_981_2_fu_173_m_axis_video_TREADY = (m_axis_video_TREADY & ap_CS_fsm_state3);

assign i_2_fu_293_p2 = (i_fu_112 + 12'd1);

assign icmp_ln1038_1_fu_255_p2 = ((tmp_17_fu_241_p3 != 16'd1) ? 1'b1 : 1'b0);

assign icmp_ln1038_fu_249_p2 = ((field_id_val11_dout != 16'd0) ? 1'b1 : 1'b0);

assign icmp_ln979_fu_288_p2 = ((i_fu_112 == rows_reg_426) ? 1'b1 : 1'b0);

assign m_axis_video_TVALID = grp_MultiPixStream2AXIvideo_Pipeline_VITIS_LOOP_981_2_fu_173_m_axis_video_TVALID;

assign or_ln1038_fu_327_p2 = (icmp_ln1038_1_reg_455 | and_ln1038_fu_322_p2);

assign ovrlayYUV_read = grp_MultiPixStream2AXIvideo_Pipeline_VITIS_LOOP_981_2_fu_173_ovrlayYUV_read;

assign select_ln1038_fu_344_p3 = ((switch_i_reg_445[0:0] == 1'b1) ? or_ln1038_fu_327_p2 : select_ln1051_fu_338_p3);

assign select_ln1051_fu_338_p3 = ((cmp104_i_reg_436[0:0] == 1'b1) ? xor_ln1053_fu_332_p2 : fid_in_val12_read_reg_416);

assign sub_i_fu_207_p2 = ($signed(width_val10_dout) + $signed(13'd8191));

assign switch_i_fu_225_p2 = ((field_id_val11_dout < 16'd3) ? 1'b1 : 1'b0);

assign tmp_17_fu_241_p3 = {{tmp_s_fu_231_p4}, {1'd1}};

assign tmp_s_fu_231_p4 = {{field_id_val11_dout[15:1]}};

assign xor_ln1053_fu_332_p2 = (phi_ln1036_loc_fu_128 ^ 1'd1);

endmodule //system_v_tpg_0_0_MultiPixStream2AXIvideo
